openshift/assisted-test-infra

- Makefile
- discovery-infra/start_discovery.py
- discovery-infra/update_bm_inventory_cm.py
- scripts/assisted_deployment.sh
In order to ensure registration of unique DNS records,
the cluster name should be randomly generated.
Hence, passed --managed-dns-domains to start_discovery.py
as an indication. Also, parsed the base domain from
args.managed_dns_domains map.
> start_discovery: handle managed-dns-domains

- discovery-infra/consts.py
- discovery-infra/install_cluster.py
To support asny install command first need to validate that cluster reached installing status
> Check cluster state after install_cluster is called.

- discovery-infra/start_discovery.py
- requirements.txt
Used dns.resolver (dnspython) to validate DNS authority and resolvability.
Note: added 'dnspython' package to requirements, so a new image of test-infra should be pushed to quay.
> validate DNS authority using dnspython

- Makefile
- scripts/test_ui.sh
New `make test_ui` target is added.
Assuption prior executing the tests:
- clean environment produced by `make redeploy_all`, especially just a single `test-infra` cluster in the Ready state with 3 `Known` hosts.
Test execution needs to be fired manually so far. Once stabilized, they can be added as a mandatory target after UI deployment.
Optional parameters (env variables):
- `CYPRESS_BASE_URL` - URL of already running UI, default: `[NODE_IP]:[UI_PORT]`
- `PULL_SECRET` - content of the pull-secret file to enable installation test
- `BASE_DIR` - folder on local filesystem to store screenshots from test execution, default `./[date_time]`
- `DEPLOY_TAG` - usually either `latest` or `stable`, one from https://quay.io/repository/ocpmetal/ocp-metal-ui-tests?tab=tags
Additional info: 
- …
> Add execution of containerized UI E2E tests

- discovery-infra/update_bm_inventory_cm.py
Added a comment for explaining the behaviour when an env var is overridden to an empty string in Makefile.
> update_cm: added a comment about empty string handling

- scripts/assisted_deployment.sh
Skip dnsmasq flow when BASE_DNS_DOMAINS env var is set.
> set_dns: skip when base_dns_domains is set

- Dockerfile.test-infra
There’s a known issue [“scp / sftp / ssh from an OpenShift Pod gives an error "No user exists for uid $someUid"”](https://access.redhat.com/solutions/4665281).
To overcome it there are multiple approaches each project configuration solves differently.
* Make /etc/passwd writable
* Add the UID to /etc/passwd
Sources:
https://access.redhat.com/articles/4859371
> Make /etc/passwd writable to allow SSH from a pod

- Makefile
- README.md
- Added new target called `make deploy_monitoring` on the `Makefile` that involves the deployment of Grafana and Prometheus used on [bm-inventory repo](https://github.com/filanov/bm-inventory/#deploy-monitoring) directly from test-infra repo
> Adding the deployment of monitoring used on bm-inventory repo

- discovery-infra/delete_nodes.py
When there's an exception when trying to delete nodes - no exception details being printed.
This PR changes this.
> Print exception details on delete nodes error

- scripts/deploy_ui.sh
Since the namespace argument was added, we should use the
up to date latest image.
> MGMT-1231: deploy_ui.sh pull image before generating ui yaml

- .yaspeller.json
- README.md
- ansible-bm-install/README.adoc
- ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/boot_iso/tasks/boot_iso.yml
- ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/create_iso/tasks/main.yml
- ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/host_iso/tasks/main.yml
- ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/validations/tasks/main.yml
- ansible-bm-install/inventory/hosts_with_os.sample
- ansible-bm-install/inventory/hosts_without_os.sample
Added samba share for mounting ISO for SuperMicro servers, added commands to properly mount and boot an ISO for supermicroservers, modified REMOTE_INVENTORY_URL to REMOTE_SERVICE_URL parameter for creating ISO, REMOTE_SERVICE_URL part of the inventory/hosts file for easy modification of your environment
> Updating Ansible playbook to support SuperMicro

- discovery-infra/assisted_service_api.py
When testing this, the jenkins worker node was 3-5 minutes behind
the correct time. This meant that we thought the token was still
valid when it was not.
> Refresh token early to be resilient to time skew

- discovery-infra/utils.py
Communication with assisted-service on PSI changed to use ssl.
This cause certificate errors in the nodes deployment against assisted-service on PSI.
> MGMT-2044: Deploy nodes without ssl verification

- Makefile
- scripts/assisted_deployment.sh
To use namespace index to determine network bridge.
> MGMT-2096: fix set dns

- discovery-infra/assisted_service_api.py
- discovery-infra/install_cluster.py
This issues an update which should have no effect as it matches the
current default, but it will test the API and that the override logic
doesn't throw any errors.
@romfreiman is this what you had in mind?
> MGMT-1883 - Update the install config before installing the cluster

- discovery-infra/delete_nodes.py
- discovery-infra/install_cluster.py
Since it is required for creating the assisted-service client in local mode.
Traceback (most recent call last):
File "/home/raz/go/src/assisted-test-infra/discovery-infra/utils.py", line 396, in wrapped
return fn(*args, **kwargs)
File "discovery-infra/delete_nodes.py", line 29, in try_to_delete_cluster
url=utils.get_assisted_service_url_by_args(args=args, wait=False)
File "/home/raz/go/src/assisted-test-infra/discovery-infra/utils.py", line 301, in get_assisted_service_url_by_args
kwargs['deploy_target'] = args.deploy_target
AttributeError: 'Namespace' object has no attribute 'deploy_target'
> Added deploy-target argument to deploy_nodes and install_cluster

- Dockerfile.test-infra
We were getting errors in CI related to dockerhub rate limiting
> Pull centos from registry.centos.org

- Makefile
- discovery-infra/ocp.py
- scripts/deploy_assisted_service.sh
- scripts/deploy_ui.sh
- scripts/ocp.sh
- scripts/utils.sh
- Added 'deploy-on-ocp-cluster' target: automates the deployemnt of
service and UI on the test OCP cluster (using build/kubeconfig by default).
- Added 'ocp.py': for updating /etc/hosts.
- Added 'ocp.sh': for deploying service/ui using assited-service (invoked with 'skipper run').
> MGMT-2462 AI on OCP cluster

- Makefile
In order to pass `-cvo` flag as a configuration I need to use `ADDITIONAL_PARAMS`
So we would be able to run a normal flow like
```bash
make
make run_full_flow_with_install 
make deploy_nodes_with_install
```
And also the same processes passing parameters `-cvo` flag
```bash
export ADDITIONAL_PARAMS=-cvo && make
make deploy_nodes_with_install ADDITIONAL_PARAMS=-cvo 
```
This way providing configuration, it is much easier to compound different workflows.
> Move CVO_PARAMS to be as part of ADDITIONAL_PARAMS

- discovery-infra/test_infra/helper_classes/cluster.py
- discovery-infra/tests/base_test.py
- discovery-infra/tests/test_cancel_and_reset.py
The idea is to migrate helper functions from BaseTest to Cluster. 
No breaking changes yet. Subsequent PRs will rebase existing tests to use Cluster object
test_cancel_reset_before_node_boot is rebased to use Cluster object
> Adds Cluster class to perform operations on cluster within the tests

- scripts/install_environment.sh
The existing code returns an error:
./scripts/install_environment.sh: line 67: elseif: command not found
> syntax fix in install_environment.sh

- discovery-infra/add_triage_signature.py
Example output:
`
h1. Host extra details:
|| id                                   || hostname   || requested_hostname   || last_contacted      || installation_disk   || product_name                                                  || manufacturer   ||   disks_count ||
| 86d3f0d0-271e-4dba-ac4f-1f19e45e9878 | master1    |                      | 2020-11-05 17:52:14 | /dev/vda            | KVM                                                           | Red Hat        |             1 |
| 51aed157-123f-4a11-8b64-ee10e06ce857 | master2    |                      | 2020-11-05 17:52:16 | /dev/vda            | KVM                                                           | Red Hat        |             1 |
| 1161fba5-f8af-cab3-f198-c64880a6bf96 | worker3    |                      | 2020-11-05 …
> Add disks_count to signature

- discovery-infra/test_infra/consts.py
- discovery-infra/test_infra/helper_classes/cluster.py
- discovery-infra/test_infra/helper_classes/nodes.py
- discovery-infra/tests/pytest.ini
- discovery-infra/tests/test_wrong_boot_order.py
These tests will include the new cluster status "installing-pending-user-action".
Update the existing test: "Installation succeeded after master node had incorrect boot order".
Create "Installation succeeded on incorrect boot order - timeout is ignored".
Create "Installation succeeded after all nodes have an incorrect boot order".
Create "Reset\Cancel from Incorrect boot order"
> MGMT-2881: e2e tests: added wrong boot order tests

- discovery-infra/test_infra/assisted_service_api.py
- discovery-infra/test_infra/helper_classes/cluster.py
- discovery-infra/test_infra/utils.py
- discovery-infra/tests/test_cancel_and_reset.py
- discovery-infra/tests/test_wrong_boot_order.py
- Change test_wrong_boot_order.test_reset_cancel_from_incorrect_boot_order: to reduce execution time (now 15 min).
- Fix flaky test_cancel_and_reset.test_cancel_reset_after_installation_failure_and_wrong_boot: to check specific host state before kill its installer
> fix e2e tests

- Makefile
- scripts/deploy_controller.sh
- scripts/ocp.sh
- As OCP cluster id is required for the controller, fetched the it form clusters list on deploy_controller.sh.
- Removed CLUSTER_ID from config_etc_hosts_for_ocp_cluster target (not required as build/kubeconfig is used).
> MGMT-2465: fetch ocp cluster id on deploy_controller

- Dockerfile.test-infra
app-sre restricted their mirrored upstream images, this change pulls base image from official cenotos quay.io repo
> pull base image from official cenotos quay.io repo

- Makefile
The service is going to be default with 1 replica in a development environment. https://github.com/openshift/assisted-service/pull/807
e2e should run with 3 replicas.
> Set default of 3 service replicas

- discovery-infra/start_discovery.py
- discovery-infra/test_infra/utils.py
- scripts/install_environment.sh
- Change default subnets and prefixes
- During cluster installation, query cluster for host statuses, and do not query libvirt for DHCP leases
/cc @YuviGold 
/cc @tsorya
> MGMT-3269 IPv6 fixes

- discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py
Tests sometimes fail on timeout for node to boot into ISO. Adding a retry to start_node to cut down on flaky tests
> Adding retry to libvirt_controller.start_node

- discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py
- discovery-infra/test_infra/controllers/node_controllers/node_controller.py
- discovery-infra/test_infra/controllers/node_controllers/qe_vm_controler.py
- discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
- discovery-infra/test_infra/helper_classes/nodes.py
- discovery-infra/tests/base_test.py
- skipper.yaml
In some cases the nodes fails to get IPs when booting. Not yet sure if its ISO issue or libvirt or lack of machine resources.
This PR collect more logs (mainly libvirt logs) on test failure, in order to properly understand the root cause when reproduces.
> Adding libvirt logs

- discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py
- discovery-infra/test_infra/controllers/node_controllers/node.py
- discovery-infra/test_infra/controllers/node_controllers/node_controller.py
- discovery-infra/test_infra/helper_classes/nodes.py
(Ignore the branch name, it's a mistake and can't be changed in GitHub after a PR is created)
Adds ability to attach disks to hosts. This in order to allow writing tests for the "Show all disks" epic (where we show all disks, and why they aren't eligible for installation, rather than just disks that are eligible for installation).
> MGMT-3292 - Added test infrastructure for attaching disks

- Jenkinsfile
tl;dr Prevent rare kubectl apply error due to problematic random namespace form 
_____
This bug is rather interesting:
1. Groovy Jenkinsfile sometimes generates a RUN_ID that looks something like `18371e12`
2. NAMESPACE env var gets set to "18371e12"
```groovy
RUN_ID = UUID.randomUUID().toString().take(8)
PROFILE = "${RUN_ID}"
NAMESPACE = "${RUN_ID}"
```
3. `assisted-service/tools/deploy_postgres.py` generates a `postgres-secret.yaml` file that contains:
```yaml
apiVersion: v1
kind: Secret
metadata:
labels:
app: postgres
name: assisted-installer-rds
namespace: 18371e12
stringData:
db.host: postgres
db.name: installer
db.password: admin
db.port: '5432'
db.user: admin
type: Opaque
```
Most importantly, notice the namespace line - and specifically, the lack of quotes around the namespace …
> NO-ISSUE - Prevent rare CI failure due to YAML quirks

- discovery-infra/install_cluster.py
- discovery-infra/test_infra/assisted_service_api.py
- Making hard coded network type prevents IPv6 installation flow
- This reverts https://github.com/openshift/assisted-test-infra/pull/107
/cc @YuviGold
> MGMT-3468 Remove hard coded network type from install flow

- discovery-infra/test_infra/controllers/node_controllers/node.py
- discovery-infra/test_infra/controllers/node_controllers/ssh.py
- discovery-infra/tests/base_test.py
In cases where a test fails before the nodes register to the service or in cases of connectivity issues with the machine running the tests collecting journalctl from the vms can provide helpful insight into the failure
> Collecting journalctl from nodes

- Dockerfile.test-infra
Adding nss_wrapper provides for a local, unprivileged passwd file to be specified,
allowing the container to map the required user information to a random UID without 
having to modify the containers /etc/passwd file directly.
Full explanation on https://access.redhat.com/articles/4859371
> Add nss_wrapper to Dockerfile.test-infra

- Dockerfile.test-infra
Since nss_wrapper addition on #405
we don't need it anymore.
> Remove writable /etc/passwd

- discovery-infra/test_infra/helper_classes/cluster.py
Adding following methods to cluster.py:
`def set_advanced_networking` - Updates Cluster CIDR, Service CIDR, and Cluster Host Prefix under AI Advanced Networking
`def set_advanced_cluster_cidr` - Updates Cluster Network CIDR under AI Advanced Networking
`def set_advanced_service_cidr` - Updates Service Network CIDR under AI Advanced Networking
`def set_advanced_cluster_host_prefix` - Updates Cluster Network Host Prefix under AI Advanced Networking
> Add advanced networking cluster methods

- discovery-infra/test_infra/controllers/proxy_controller/proxy_controller.py
Pulling the container image for proxy server from quay instead of dockerhub, in order to avoid pull rate limits
> pulling squid container image from quay

- discovery-infra/start_discovery.py
- discovery-infra/test_infra/helper_classes/cluster.py
- terraform_files/baremetal/main.tf
- Send machine CIDR to assisted-service in user-managed-networking single with IPv6
- Set all dns names to point to the node IP address
/cc @empovit 
/cc @tsorya
> MGMT-3603 Changes for single node IPv6

- discovery-infra/test_infra/assisted_service_api.py
Includes ManagedDomainsApi so we can validate domain and provider used by the api_client.
> Add managed domains to assisted_service_api

- discovery-infra/tests/base_test.py
In collect logs there is a retry and sleep of 5 minutes, which is unnecessary when test passes. Therefore collecting logs only on failures
> Collecting log only on failure to reduce execution time

- discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py
- discovery-infra/test_infra/controllers/node_controllers/node.py
- discovery-infra/test_infra/utils.py
- discovery-infra/tests/base_test.py
Modifies `attach_test_disk` node method and dependencies to allow for attaching bootable disks. This is useful for test cases that require a disk with the `(bootable)` flag to be set
> Add bootable option for newly attached disks

- discovery-infra/day2.py
- discovery-infra/start_discovery.py
- discovery-infra/test_infra/utils.py
Setting hostnames via Terraform doesn't work with IPv6. Work that around by setting the hostnames of a cluster via assisted service API. Day 2 scenario similar to how it's done in day 1.
> MGMT-3065 Set hostnames via API in IPv6 setups

- discovery-infra/test_infra/helper_classes/cluster.py
- discovery-infra/update_assisted_service_cm.py
- terraform_files/baremetal/limit_ipv6_dhcp_range.xsl
- terraform_files/baremetal/main.tf
/hold
/cc @ronniel1 @ori-amizur 
Not pretty, but can be easily replaced when someone implement dmacvicar/terraform-provider-libvirt#794
> MGMT-3838: limit libvirt's DHCP allocation range on IPv6

- scripts/deploy_assisted_service.sh
Make it possible to override the installer, controller, and agent images when running test-infra for onprem.
> MGMT-3841: Inject images onprem

- README.md
Adding a note to unset the KUBECONFIG variable.
Otherwise the deployment may get stuck.
Signed-off-by: Alexander Chuzhoy <achuzhoy@redhat.com>
> unset KUBECONFIG note

- requirements.txt
Pin the cryptography dependency to the latest version before 3.4 to fix
ModuleNotFoundError: No module named 'setuptools_rust'
> NO-ISSUE Pin cryptography Python dependency to 3.3.2

- Dockerfile.test-infra
- requirements.txt
Upgrade pip to solve `No module named 'setuptools_rust'`, 
and force-ignore installed PyYAML to solve 
```
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and 
thus we cannot accurately determine which files belong to it which would 
lead to only a partial uninstall.
```
> NO-ISSUE Fix setuptools_rust module not found

- discovery-infra/test_infra/helper_classes/cluster.py
Adds `get_host_disks` cluster method for retrieving host disk information. Includes an optional filter that can be a regular function or a lambda function. Returns a list of disks matching the filter criteria, or if no filter is included, returns all disks.
> Add get_host_disks cluster method

- scripts/deploy_assisted_service.sh
By passing ENABLE_KUBE_API env.
Use the skipper image of assisted-service which has all
the relevant dependencies required to generate and deploy
relevant definitions and deploy the service with the kube
controller enabled.
> MGMT-3370: Allow running in kube api mode

- discovery-infra/test_infra/consts.py
- discovery-infra/test_infra/helper_classes/kube_helpers.py
- discovery-infra/tests/base_test.py
- discovery-infra/tests/conftest.py
Provides infra to create and destroy a ClusterDeployment CRD
to be used by e2e tests.
There's a PR for e2e test using this infra as well:
https://gitlab.cee.redhat.com/ocp-edge-qe/kni-assisted-installer-auto/-/merge_requests/112
> MGMT-3370: Added KubeAPI helpers for e2e test infra

- discovery-infra/test_infra/helper_classes/kube_helpers.py
By given filepath (optional) deploy ClusterDeployment from
its data instead of environment variables.
> MGMT-3370: Allow deploying ClusterDeployment from file

- Dockerfile.test-infra
- Makefile
- discovery-infra/start_discovery.py
- discovery-infra/test_infra/controllers/load_balancer_controller.py
- discovery-infra/test_infra/helper_classes/cluster.py
- discovery-infra/test_infra/utils.py
- scripts/install_environment.sh
- skipper.yaml
- terraform_files/none/main.tf
- terraform_files/none/variables-libvirt.tf
Add load balancer
The load balancer runs in its own container.  The setup of the container is in install_environment.sh.
It runs nginx as load balancer.
The nginx in the container is refreshed every 60 seconds.  It looks at directory /etc/nginx/stream.d/ , where load balancing definitions can be added or removed.
The load balancing definitions are managed by terraform (using local_file resource) which is driver by python code.  They are generated currently only for none platform.
/cc @tsorya 
/cc @empovit
> MGMT-3420 Make test infra work with none platform and IPv6

- Dockerfile.test-infra
Must-gather after ibip installation is complaining that it doesn't have rsync
> NO-ISSUE - Rsync for sno must-gather

- discovery-infra/test_infra/helper_classes/cluster.py
This moves wait_and_kill_installer into Cluster from downstream test for shared use
> Moving wait_and_kill_installer into Cluster for shared use

- Jenkinsfile
No need to keep running the Jenkins job hourly against the master branch
since we already moved our periodics to Prow on OpenShift CI.
> Remove hourly cron trigger from Jenkinsfile

- Jenkinsfile.download_logs
The collector is unable to reach the cluster to get the must-gather
logs from the outside.
Hence, we would have to rely on assisted-service to collect the
must-gather logs.
No reason to keep executing that command from test-infra.
> Remove --must-gather flag on Jenkinsfile.download_logs

- discovery-infra/test_infra/assisted_service_api.py
Fixing the case the URL already contains an ``https`` scheme:
```
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='https', port=80): Max retries exceeded with url: //api.openshift.com/metrics (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc59b05ca90>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```
> not prepending 'http://' to URLs that already include a scheme

- discovery-infra/tests/base_test.py
When attaching 2 disk to the same node, than detach_all_test_disks fails.
This PR is for resolving this teardown failure
> Fix detach_all_test_disks during teardown

- discovery-infra/test_infra/helper_classes/kube_helpers/__init__.py
- discovery-infra/test_infra/helper_classes/kube_helpers/agent.py
- discovery-infra/test_infra/helper_classes/kube_helpers/base_resource.py
- discovery-infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py
- discovery-infra/test_infra/helper_classes/kube_helpers/common.py
- discovery-infra/test_infra/helper_classes/kube_helpers/secret.py
- discovery-infra/tests/base_test.py
KubeAPIContext is an object which holds information about the resources
created during a test. It will be used in a fixture
called kube_api_context and provides the kube_api_client. By doing that,
there will be no need to worry about cleanup of any resource that will be
created in the test (i.e no need to run the test within contextmanager).
> NO-ISSUE: Added KubeAPIContext

- scripts/run_minikube.sh
Increase minikube disk allocation so that the VM
has enough space for minikube components and ephemeral storage.
> MGMT-4604 Fix scality ephemeral storage error

- discovery-infra/install_cluster.py
- discovery-infra/start_discovery.py
- discovery-infra/test_infra/assisted_service_api.py
- discovery-infra/test_infra/consts.py
- discovery-infra/test_infra/helper_classes/cluster.py
- discovery-infra/test_infra/utils.py
- discovery-infra/tests/conftest.py
As part of waiting for installation to complete - we look for hosts and cluster to be "installed". Now we watch for operators to be "Available" or "Failed" as well.
Remove "-cvo" flag to inspect cvo status since it's being done by the service.
```
2021-03-25 14:10:23,067 INFO       - 139877912267648 - Asked operators to be in one of the statuses from ['available', 'failed'] and currently operators statuses are [('console', 'available', 'All is well')]    (/home/assisted-test-infra/discovery-infra/test_infra/utils.py:232)
```
> MGMT-3334 Wait for operators to finish

- scripts/run_minikube.sh
In order for k8s services to have external IPs accessible from kubectl
- minikube have to be started with a LoadBalancer.
By default minikube isn't starting with a LoadBalancer and for that we
have to run `minikube tunnel` on a separate process, since it is running
in the foreground.
> Run minikube tunnel when starting minikube

- Makefile
Before
```bash
➜  assisted-test-infra git:(master) make bring_assisted_service SERVICE_BRANCH=1639cf2c9b3ddaa34525757a2caaa5884bb0e997
Fetching origin
fatal: ambiguous argument 'origin/1639cf2c9b3ddaa34525757a2caaa5884bb0e997': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
make: *** [Makefile:365: bring_assisted_service] Error 128
```
After
```bash
➜  assisted-test-infra git:(get-assisted-service-by-sha) make bring_assisted_service SERVICE_BRANCH=1639cf2c9b3ddaa34525757a2caaa5884bb0e997
Cloning into 'assisted-service'...
remote: Enumerating objects: 76, done.
remote: Counting objects: 100% (76/76), done.
remote: Compressing objects: 100% (67/67), done.
remote: Total 19909 (delta 23), …
```
> Support SHAs for SERVICE_BRANCH and INSTALLER_BRANCH

- discovery-infra/test_infra/assisted_service_api.py
- discovery-infra/test_infra/utils.py
get_cluster_operators is an agent operation.
We weren't notified about this usage because test-infra by default isn't
running with auth but staging is
> Bugfix get cluster operators to avoid agentAuth

- discovery-infra/start_discovery.py
- discovery-infra/test_infra/helper_classes/kube_helpers/base_resource.py
- discovery-infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py
- discovery-infra/test_infra/helper_classes/kube_helpers/secret.py
Current code is just too long, and the behavior we want is a simple 'kubectl apply'.
So I replaced deletion and creation with the new methods.
Kubernetes python client doesn't support apply right now, so it will be a simple substitution for now (until we'll mimic the 3-way patch of apply).
/hold
/cc @RazRegev
> NO-ISSUE implement a 'kubectl apply' like interface

- Makefile
Deploy assisted-service with support for kube-api interface by default on our testing environment.
/cc @filanov 
/hold
> MGMT-4852 enable kube-api by default

- discovery-infra/test_infra/controllers/nat_controller.py
- discovery-infra/test_infra/helper_classes/cluster.py
- discovery-infra/test_infra/helper_classes/nodes.py
- discovery-infra/tests/base_test.py
Put `configure_nat` and `unconfigure_nat` methods in nodes.py and tear them down if needed in the nodes fixture. Also, make NatController a static class, no `self` is needed.
> MGMT-3335 teardown iptables in nodes

- scripts/install_minikube.sh
Instead of maintaining different URLS for tools installations,
arkade provides a portable marketplace for downloading devops CLIs.
- Bumping minikube to v1.18.1
- Bumping kubectl to v1.20.0
stdout:
```bash
Installing minikube and oc
Installing arkade...
x86_64
Downloading package https://github.com/alexellis/arkade/releases/download/0.7.10/arkade as /tmp/arkade
Download complete.
Running with sufficient permissions to attempt to move arkade to /usr/local/bin
New version of arkade installed to /usr/local/bin
which: no ark in (/sbin:/bin:/usr/sbin:/usr/bin)
Creating alias 'ark' for 'arkade'.
main: line 176: arkade: command not found
Installing minikube...
Downloading minikube
https://github.com/kubernetes/minikube/releases/download/v1.18.1/minikube-linux-amd64
9.20 MiB / 57.02 MiB …
```
> Install minikube and kubectl using arkade

- scripts/run_minikube.sh
Instead of 
```bash
[root@f13-h20-b08-5039ms assisted-test-infra]# make start_minikube 
scripts/run_minikube.sh
Configuring minikube...
eval 
```
Now we will know if it runs a new instance of minikube or not
```bash
[root@f13-h20-b08-5039ms assisted-test-infra]# make start_minikube 
scripts/run_minikube.sh
+ export PROFILE=minikube
+ PROFILE=minikube
+ '[' minikube '!=' minikube ']'
+ configure_minikube
+ echo 'Configuring minikube...'
Configuring minikube...
+ minikube config set ShowBootstrapperDeprecationNotification false
+ minikube config set WantUpdateNotification false
+ minikube config set WantReportErrorPrompt false
+ minikube config set WantKubectlDownloadMsg false
+ as_singleton init_minikube
+ func=init_minikube
+ interval=15s
+ lockfile=/tmp/init_minikube.lock
+ '[' -e …
```
> Add xtrace for run_minikube script

- discovery-infra/install_cluster.py
What sometimes happens is the following:
* We define a cluster deployment
* Cluster installation doesn't start yet, and we get a ready state from it
* We attempt to install cluster from REST instead of kubeapi
So adding a condition not not do the REST installation.
/cc @YuviGold 
/hold
> NO-ISSUE do not attemp to install from REST if kubeapi cluster is ready

- Makefile
- README.md
Seems like we don't pull latest code on ``assisted-service`` and ``assisted-installer``.
Added now reference to the ``origin`` remote and not the saved ``master`` branch.
/hold
/cc @YuviGold @filanov
> NO-ISSUE pull latest code on origin remote

- scripts/install_minikube.sh
Currently, 'install_minikube' checks only whether minikube is installed.
To avoid a stale version, updating minikube when necessary.
This seems to prevent issues like "Wait for http://<pending>:8090/ready",
when using 'tunnel --cleanup':
https://github.com/openshift/assisted-test-infra/blob/1132db6444569f074efa62b27bc646f33a5a420b/scripts/run_minikube.sh#L29
> NO-ISSUE update minikube version if stale

- Makefile
- README.md
Reverts openshift/assisted-test-infra#673
It breaks the CI, not supporting SHAs
```bash
➜  assisted-test-infra git:(master) SERVICE_BRANCH=200a658589c6986a3888ac29fc4247b7e21f716c make bring_assisted_service 
Cloning into 'assisted-service'...
remote: Enumerating objects: 828, done.
remote: Counting objects: 100% (828/828), done.
remote: Compressing objects: 100% (439/439), done.
remote: Total 20358 (delta 482), reused 616 (delta 377), pack-reused 19530
Receiving objects: 100% (20358/20358), 32.34 MiB | 7.57 MiB/s, done.
Resolving deltas: 100% (15070/15070), done.
fatal: Could not parse object '200a658589c6986a3888ac29fc4247b7e21f716c'.
make: *** [Makefile:367: bring_assisted_service] Error 128
```
> Revert "NO-ISSUE pull latest code on origin remote"

- Makefile
The previous solution, fetched the remote origin/master but resetted
HEAD (master) to the same location, instead of the remote
(origin/master).
This solution uses FETCH_HEAD which points to the latest fetch
operation.
Tested for tags, detached commits (PRs), and branches.
> Fix sync branches for assisted-service

- discovery-infra/test_infra/helper_classes/kube_helpers/agent.py
- discovery-infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py
- discovery-infra/test_infra/helper_classes/kube_helpers/global_vars.py
- discovery-infra/test_infra/helper_classes/kube_helpers/installenv.py
- discovery-infra/test_infra/helper_classes/kube_helpers/nmstate_config.py
To reduce future work in case of any change, use
global variables for api group and version instead
of duplicated values in every object.
> NOISSUE centralized kube api group and version vars

- discovery-infra/test_infra/helper_classes/cluster.py
- discovery-infra/test_infra/utils.py
Adding wait_for_cluster_to_be_in_finalizing_status and is_operator_in_status methods for e2e that simulate operator failure
> Adding cluster methods for e2e

- scripts/install_minikube.sh
1. Use awk instead of jq because older `minikube version` commands
doen't have the `-o` modifier.
2. Replace the minikube binary at its original location instead of
`/usr/local/bin/`.
> NO-ISSUE Fix minikube upgrades on older systems

- discovery-infra/test_infra/helper_classes/kube_helpers/__init__.py
- discovery-infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py
- discovery-infra/test_infra/helper_classes/kube_helpers/common.py
- discovery-infra/test_infra/helper_classes/kube_helpers/global_vars.py
Instead of waiting 2 hours to find out the installation has failed,
raise error immediately if the status changes to error.
> NOISSUE: raise error if ClusterDeployment status changed to error

- discovery-infra/download_logs.py
example: https://auto-jenkins-csb-kniqe.apps.ocp4.prod.psi.redhat.com/view/Assisted-Installer/job/ocp-assisted-installer-virt/223/testReport/junit/test_disk_selection/TestDiskSelection/test_remove_disk_boot_flag_2/
> Catching must gather exception to avoid Runtime error

- discovery-infra/test_infra/assisted_service_api.py
- discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py
- discovery-infra/test_infra/controllers/node_controllers/node_controller.py
- discovery-infra/tests/base_test.py
Support attach disk with a WWN(World Wide Name)
Having a WWN creates a disk by-id link (/dev/disk/by-id)
> MGMT-4050 	E2E tests for disk ID

- discovery-infra/start_discovery.py
- discovery-infra/test_infra/helper_classes/kube_helpers/__init__.py
- discovery-infra/test_infra/helper_classes/kube_helpers/infraenv.py
- discovery-infra/test_infra/kubeapi_utils.py
As the assisted-service KubeAPI approaches a point in which it starts to integrate
with other projects, we make final changes to the API naming.
This PR renames InstallEnv to InfraEnv in our tests.
It follows the footsteps of:  https://github.com/openshift/assisted-service/pull/1485
> MGMT-4921 Rename InstallEnv --> InfraEnv

- discovery-infra/test_infra/helper_classes/cluster.py
Currently wait_till_all_operators_are_in_status in most cases will end with success, even when operators finish with failure. This PR fix that - in any case where operator fails - then test should fail, unless specified otherwise (fall_on_error_status=True)
> Fix operator status when waiting for operator to finish

- discovery-infra/start_discovery.py
- discovery-infra/test_infra/consts.py
- discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
- discovery-infra/test_infra/utils.py
Based on `OLM_OPERATORS` environment variable we need to add enough resources to nodes vms so validations for those operators would pass. Before running terraform we add resources as specified by `consts.OPERATOR_PARAMS` for corresponding operators.
Signed-off-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>
> MGMT-4792 Dynamically change vm resources based on enabled operators

- discovery-infra/update_assisted_service_cm.py
This PR adds `HW_VALIDATOR_REQUIREMENTS` env variable handling in update_assisted_service_cm.py
The purpose of this change is to make sure assisted-service is always configured with expected default host requirements after legacy, separate env variable values (`HW_VALIDATOR_MIN_*` at https://github.com/openshift/assisted-service/blob/0ec56929f077cd512e4ef91e3a242ad20d3a7bd4/internal/hardware/validator.go#L41-L46)  are removed from the assisted-service and `HW_VALIDATOR_REQUIREMENTS` takes the full responsibility for setting the host requirements.
> MGMT-4640 Using HW_VALIDATOR_REQUIREMENTS

- README.md
Briefly describes the new environment variable to allow disabling host validations at runtime.
> MGMT-5265 Add doc reference to DISABLED_HOST_VALIDATIONS environment variable

- discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
Due to rebase glitch list_nodes was removed accidentially. This PR restores it.
Signed-off-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>
> Restore list_nodes

- Makefile
Couldn't test this locally as the service wouldn't deploy with these errors:
```
E0420 13:59:27.974475       1 leaderelection.go:325] error retrieving resource lock assisted-installer/77190dcb.agent-install.openshift.io: Get "https://10.96.0.1:443/api/v1/namespaces/assisted-installer/configmaps/77190dcb.agent-install.openshift.io": context deadline exceeded
I0420 13:59:27.974768       1 leaderelection.go:278] failed to renew lease assisted-installer/77190dcb.agent-install.openshift.io: timed out waiting for the condition
time="2021-04-20T13:59:27Z" level=fatal msg="failed to run manager" func=main.main.func1 file="/go/src/github.com/openshift/origin/cmd/main.go:167" error="leader election lost"
```
Hopefully CI has better luck :sweat_smile:
> MGMT-4482 Use local auth with kube-api by default

- discovery-infra/install_cluster.py
- discovery-infra/start_discovery.py
- discovery-infra/test_infra/helper_classes/kube_helpers/__init__.py
- discovery-infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py
- discovery-infra/test_infra/helper_classes/kube_helpers/global_vars.py
The ClusterDeployment CRD will now support the following conditions:
- SpecSynced
- ReadyForInstallation
- Installed
- Validated
Before, the hive condition `UnreachableCondition` was used.
Implemented in:  https://github.com/openshift/assisted-service/pull/1524
> MGMT-3879 Update ClusterDeployment conditions

- discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py
- discovery-infra/test_infra/controllers/node_controllers/node_controller.py
- discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
- discovery-infra/test_infra/helper_classes/nodes.py
`NodeController.list_nodes` now return List[Node] instead of List[virDomain]
https://issues.redhat.com/browse/MGMT-5275
> MGMT-5275 - Fix NodeController.list_nodes to return List[Node]

- discovery-infra/start_discovery.py
- discovery-infra/test_infra/utils.py
As only 4.8 is supported when KUBE_API is enabled (see scripts/deploy_assisted_service.sh),
the relevant release image should be fetched accordingly.
> MGMT-4577 kube_api: use 4.8 release image

- discovery-infra/start_discovery.py
- discovery-infra/test_infra/assisted_service_api.py
- discovery-infra/test_infra/utils.py
Removing unnecessary huge JSONS printed for hosts.
For hosts printing name and role
```
2021-04-27 14:23:17,335 INFO       - 140210914888576 - Asked hosts to be in one of the statuses from ['installed'] and currently hosts statuses are [(1, '40e11568-89e1-45b1-9360-4a2b743b5892', 'test-infra-cluster-assisted-installer-worker-0', 'worker', 'installing', 'Installation is in progress'), (2, 'ea884ec8-c334-4bca-9327-5e5e294a0c40', 'test-infra-cluster-assisted-installer-master-1', 'master', 'installing', 'Installation is in progress'), (3, '29d027f8-1038-4b9b-a663-23e9e953c819', 'test-infra-cluster-assisted-installer-worker-1', 'worker', 'installing', 'Installation is in progress'), (4, '883ecc98-4a40-4e17-8a73-8fef4419037d', 'test-infra-cluster-assisted-installer-master-2', 'master', …
```
> Remove some unnecessary debug prints

- discovery-infra/start_discovery.py
- discovery-infra/test_infra/consts/__init__.py
- discovery-infra/test_infra/consts/consts.py
- discovery-infra/test_infra/consts/olm_operators.py
- discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
- discovery-infra/test_infra/helper_classes/cluster.py
- discovery-infra/test_infra/utils.py
https://issues.redhat.com/browse/MGMT-5411
Changes:
-  Create OLM Operators consts classes 
-  Create consts package instead of consts module - preparation for consts total refactoring
Node: Keys in environment variables with the same name as the operators resource keys will be modified on later tasks.
> MGMT-5411 - Refactor operator resource consts

- discovery-infra/bootstrap_in_place.py
- discovery-infra/download_logs.py
It turns out that ``Nodes`` class doesn't set SSH private keys on its nodes.
As a fix, using the controller class to make access to the nodes.
> NO-ISSUE another fix for sosreport on ibip flow

- discovery-infra/test_infra/controllers/node_controllers/ssh.py
Looking here, it looks like sometimes connecting to VMs requires more connection time:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/18239/rehearse-18239-periodic-ci-openshift-release-master-nightly-4.8-e2e-metal-assisted/1388753965369266176/artifacts/e2e-metal-assisted/baremetalds-assisted-gather/build-log.txt
```
Traceback (most recent call last):
File "./discovery-infra/download_logs.py", line 255, in gather_sosreport_from_node
node.upload_file(SOSREPORT_SCRIPT, "/tmp/man_sosreport.sh")
File "/home/assisted/discovery-infra/test_infra/controllers/node_controllers/node.py", line 57, in upload_file
with self.ssh_connection as _ssh:
File "/home/assisted/discovery-infra/test_infra/controllers/node_controllers/ssh.py", line 22, in …
```
> NO-ISSUE increase timeout of SSH connection action

- discovery-infra/test_infra/helper_classes/cluster.py
After adding events for validations we need to make sure we don't spam
the DB in the process.
Signed-off-by: Yoni Bettan <ybettan@redhat.com>
> MGMT-3470: Extending events test to make sure we don't spam events.

- discovery-infra/install_cluster.py
- discovery-infra/test_infra/helper_classes/cluster.py
- discovery-infra/test_infra/utils.py
Builtin operators have to succeed. Otherwise, the cluster isn't
accessible. OLM could fail and then the cluster would be declared as
degraded.
/cc @lalon4
> MGMT-6049 Wait for operators to finish first wait for builtin then to OLM

- discovery-infra/test_infra/controllers/node_controllers/ssh.py
Right now we're using the wrong IP family on ipv6 hosts:
```
2021-05-11 04:55:04,460 INFO       - 139918223341312 - Wait for 1001:db8::19 to be available 	(/home/assisted/discovery-infra/test_infra/controllers/node_controllers/ssh.py:50)
2021-05-11 04:56:04,540 ERROR      - 139918457161472 - Failed accessing node test-infra-cluster-assisted-installer-worker-0 for sosreport data gathering 	(./discovery-infra/download_logs.py:262)
Traceback (most recent call last):
File "./discovery-infra/download_logs.py", line 255, in gather_sosreport_from_node
node.upload_file(SOSREPORT_SCRIPT, "/tmp/man_sosreport.sh")
File "/home/assisted/discovery-infra/test_infra/controllers/node_controllers/node.py", line 57, in upload_file
with self.ssh_connection as _ssh:
File …
```
> NO-ISSUE fix sosreport gathering from ipv6 nodes

- scripts/deploy_assisted_service.sh
As [MGMT-4554](https://issues.redhat.com/browse/MGMT-4554) is already merged (https://github.com/openshift/assisted-service/pull/1319),
the versions json can include only rhcos_image and rhcos_version properties
when deploying the service.
I.e. when ENABLE_KUBE_API is true, OPENSHIFT_VERSIONS env var should be in the following format:
```
{
"4.8": {
"rhcos_image": "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.7/4.7.0/rhcos-4.7.0-x86_64-live.x86_64.iso",
"rhcos_version": "47.83.202102090044-0"
}
}
```
Instead of:
```
{
"4.8": {
"display_name": "4.8.0-fc.0",
"release_version": "4.8.0-fc.0",
"release_image": "quay.io/openshift-release-dev/ocp-release:4.8.0-fc.0-x86_64",
"rhcos_image": "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.7/4.7.0/rhcos-4.7.0 …
```
> MGMT-4554 kube-api: include only rhcos in deploy service

- scripts/deploy_assisted_service.sh
Adjusting make target to a new name: `generate-ocp-version` in assisted-service Makefile became `generate-configuration`.
> MGMT-4640 Renamed generate-ocp-version target

- Makefile
- README.md
- scripts/assisted_deployment.sh
- scripts/deploy_assisted_service.sh
- scripts/install_environment.sh
- skipper.yaml
- terraform_files/none/main.tf
Add new 'operator' DEPLOY_TARGET to deploy_assisted_service.sh that
calls deploy/operator/deploy.sh script from assisted-service repository.
The current workflow to install an operator is to make a regular
installation with AI, and afterwards use its KUBECONFIG to deploy the
assisted-operator on top of it.
A cluster installed with test-infra is provisoned with nat networking.
It created iptables rules by design to ignore inbound connections except
from the host.
Hence, in order to make new VMs from a new network to reach the
assisted operator that is installed on the cluster - we have to pass the
communication through the host. It is made by overriding
SERVICE_BASE_URL.
Before deploying, we will start an nginx load balacer and configure it
to listen to http and proxy pass the …
> MGMT-5274 Deploy assisted operator

- discovery-infra/download_logs.py
The file is constructed right, but has an incorrect name.
/cc @YuviGold 
/hold
> NO-ISSUE fix extension of sosreport tar.bz2 file

- scripts/deploy_assisted_service.sh
Following to https://github.com/openshift/assisted-service/pull/1697,
'rhcos_rootfs' property should now be included in OPENSHIFT_VERSIONS
env var for the kube-api flow.
> NO-ISSUE deploy service kube-api: added rhcos_rootfs to versions

- discovery-infra/download_logs.py
- discovery-infra/test_infra/controllers/node_controllers/node.py
- discovery-infra/test_infra/controllers/node_controllers/ssh.py
When configuring a SSH connection, we need to decide which IP address to use.
Currently we get all DHCP leases from libvirt, and use the first provided address. It will work on IPv4 because DHCP will always return the same address to the hosts, but on IPv6 environment the returned addresses are not constant.
This change is making a complete traversal over all IP addresses of the node, over all networks. This will ensure that as long as the node is up, we'll be able to reach it.
> SSH through all available node IPs

- scripts/deploy_assisted_service.sh
In case of on prem deployment `HW_VALIDATOR_MIN_DISK_SIZE_GIB` variable has been set to 20 and after `HW_VALIDATOR_REQUIREMENTS` variable has been introduced, it should be changed there; this PR makes sure that it happens.
> MGMT-6438 Setting custom minimum disk size in HW_VALIDATOR_REQUIREMENTS for onprem

- discovery-infra/download_logs.py
I changed the returned exception where no IPs have been assigned to the node, and forgot to change it in the using function.
/cc @YuviGold 
/hold
> NO-ISSUE catch RuntimeError when node has no IPs

- discovery-infra/events.html
In the case of a path in the server that contains underscore, we might miscalculate the UUID of the cluster.
So this logic should first extract the directory name of the UUID, and afterwards parse the directory name.
/cc @YuviGold @rollandf 
/hold
> fix events.html fetching events JSON

- discovery-infra/download_logs.py
On kube-api we cannot create the REST client, which makes a too early failure before gathering sosreport.
/cc @YuviGold @filanov 
/hold
> NO-ISSUE define REST client after gathering sosreport

- discovery-infra/start_discovery.py
It seems like we don't label infraenv with the cluster-name (as we do with nmstate-config), making the cluster not configuring static IPs.
/cc @YuviGold @RazRegev @filanov 
/hold
> NO-ISSUE add a label to the infraenv to match labels of nmstate-config

- scripts/download_logs.sh
Collect data and description of cluster deployment, agent cluster install,
InfraEnv, and the agents in kube-api mode.
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_assisted-test-infra/826/pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-kube-api/1396781858645086208/artifacts/e2e-metal-assisted-kube-api/baremetalds-assisted-gather/artifacts/
> MGMT-6579: download_logs.sh: collect kube-api CRs

- discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py
- discovery-infra/test_infra/controllers/node_controllers/node.py
- discovery-infra/test_infra/controllers/node_controllers/node_controller.py
- discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
On https://github.com/openshift/assisted-test-infra/pull/772 disks names
were changed in order to support creation of multiple disks.
Now instead of the disk name to be the same as the node name
<cluster_name>-<node_role>-<node_index>, it is now
<cluster_name>-<node_role>-<node_index>-disk-<disk_index>
For now, format_disk will receive the disk index as a parameter.
cc @lalon4 @patrickdillon @tsorya  @omertuc
> MGMT-6587 Include disk_index as part of disk name on format_disk

- discovery-infra/test_infra/assisted_service_api.py
Exposing `/clusters/{cluster_id}/preflight-requirements` operation in the Python Assisted Service client wrapper.
> MGMT-6480 Exposing /clusters/{cluster_id}/preflight-requirements

- discovery-infra/update_assisted_service_cm.py
- scripts/deploy_assisted_service.sh
his PR removes last traces of env variables removed in #1715:
- HW_VALIDATOR_MIN_CPU_CORES_WORKER
- HW_VALIDATOR_MIN_CPU_CORES_MASTER
- HW_VALIDATOR_MIN_RAM_GIB_WORKER
- HW_VALIDATOR_MIN_RAM_GIB_MASTER
- HW_VALIDATOR_MIN_DISK_SIZE_GIB
Currently all of the above requirements have to be set using `HW_VALIDATOR_REQUIREMENTS`.
> MGMT-6438 remove references to deprecated env variables

- discovery-infra/update_assisted_service_cm.py
- scripts/deploy_assisted_service.sh
This PR adds "sno" requirements to code handling `HW_VALIDATOR_REQUIREMENTS` env variable and config map key updates.
Related to https://github.com/openshift/assisted-service/pull/1818
> MGMT-6550 Add sno requirements to versioned requirements

- discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py
It changed on https://github.com/openshift/assisted-test-infra/pull/335 but not on the controller
> NO-ISSUE - Replace libvirt list_leases usage with utils usage to support ipv6

- discovery-infra/test_infra/helper_classes/cluster.py
- discovery-infra/test_infra/utils/logs_utils.py
- discovery-infra/test_infra/utils/utils.py
Deprecated functions on `test_infra.utils` are used at https://gitlab.cee.redhat.com/ocp-edge-qe/kni-assisted-installer-auto/-/blob/master/api_tests/test_logs.py
> MGMT-6521 - move logs methods from utils to logs_utils

- scripts/assisted_deployment.sh
- terraform_files/baremetal/main.tf
- terraform_files/baremetal/terraform.tfvars.json
For running conformance tests, API VIP must be accessible by
DNS name 'api.test-infra-cluster-assisted-installer.redhat.com'.
In order for that to work
1. Make sure the libvirt network has a dns-host entry for API,
(created by Terraform).
2. Update the entry with the correct IP address as soon as it
becomes known by updating a Terraform variable. This is
already done in the Python code, so removing the Shell function
because the logic there is incomplete.
3. Make dnsmasq use the libvirt network's address to handle DNS
resolution, so that the DNS entry for API can be resolved from
the host (already implemented by `set_dns()`).
Tested scenarios:
* multinode + IPv4
* SNO + IPv4
* multinode + static network config + IPv4
* SNO + static network config + IPv4
* multinode + IPv6
* SNO + IPv6
* …
> MGMT-6544 Create API VIP DNS

- Makefile
Setting DNS must be done as part of every `deploy_nodes_with_install`,
this way it will cover all possible installation flows.
If DNS is not set, API VIP of the installed cluster cannot be reached
by its DNS name from the host.
In case of `deploy_nodes`, which doesn't install a cluster automatically
(with installation from the UI / API afterwards), API VIP is still
unknown. Therefore `make set_dns` and changes to dns-host of the
libvirt network must be done manually.
> MGMT-6602 Make set_dns run after each installation

- discovery-infra/test_infra/tools/tf_network_pool.json
Changed the values in the tf_network_pool.json so they won't collide
with default parameters of the run_full_flow_with_install flow. 
In this way it should support parallel installations alongside cluster
that was already installed.
> MGMT-6408 - update tf_network_pool.json values

- discovery-infra/start_discovery.py
- discovery-infra/test_infra/helper_classes/cluster.py
When VIP allocation is done using DHCP, the API VIP DNS has to be published after it is allocated.
This flow is irrelevant for non DHCP allocation since the VIPs are static when this flow is used
so they are set before running terraform the first time.
/cc @eliorerz
> OCPBUGSM-26780 api_vip_dns_name resolves to incorrect IP leading to API VIP connection validation failure

- discovery-infra/test_infra/helper_classes/kube_helpers/__init__.py
- discovery-infra/test_infra/helper_classes/kube_helpers/agent_cluster_install.py
- discovery-infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py
- discovery-infra/test_infra/helper_classes/kube_helpers/common.py
- discovery-infra/test_infra/helper_classes/kube_helpers/idict.py
- discovery-infra/test_infra/helper_classes/kube_helpers/infraenv.py
On this PR:
-  Run `black` command on `kube_helpers`
-  Run `isort` command on `kube_helpers`
-  Removed unused function on `cluster_deployment` - `deploy_default_cluster_deployment`
-  Fix return value bug on `agent_cluster_install` and `cluster_deployment`
> MGMT-6698 - Fix PEP8 violations on kube_helpers. Delete unused deploy_default_cluster_deployment

- discovery-infra/day2.py
- discovery-infra/start_discovery.py
It looks like libvirt won't have a hostname in the DHCP lease of a VM
that has IPv6, even if it also has an IPv4 address. In this case we
need to get the hostname from Terraform, like we do with IPv6-only
hosts.
This is in preparation for dual stack support (`IPv4=yes IPv6=yes`).
> MGMT-6744 Use hostnames from TF if hosts have IPv6

- discovery-infra/tests/test_e2e_install.py
Currently, in case of the service skipping the operator or not including
it at all from some reason at the installation - then the installation
could proceed without it. This change makes sure that the expected
operator reached AVAILABLE status.
> NO-ISSUE Verify operator is actually available

- scripts/install_minikube.sh
This PR upgrades the minikube version to install if none exists from 1.18.1 to 1.20.0.
@YuviGold can you take a look?
Thanks!
> NO-ISSUE: Bump minikube from 1.18.1 to 1.20.0

- discovery-infra/download_logs.py
- discovery-infra/test_infra/helper_classes/kube_helpers/agent_cluster_install.py
- discovery-infra/test_infra/utils/utils.py
- discovery-infra/tests/test_kube_api.py
In case of a cluster install failure, events and logs
should be collected using Status.DebugInfo in AgentClusterInstall CRD.
* DebugInfo contains eventsURL and logsURL.
* In case of "InstallationFailed" condition, the URLs are queried
and the responses are stored in build folder (events.json and logs.tar).
> MGMT-6581 collect debuginfo on cluster install failure

- scripts/assisted_deployment.sh
Dnsmasq would only be requested to resolve in case localhost can be
found under /etc/resolv.conf. For that - the localhost ip(127.0.0.1) is
added at the top of the nameservers on /etc/resolv.conf after
NetworkManager was restarted.
/cc @tsorya  @yevgeny-shnaidman
> Add localhost nameserver on set_dns

- discovery-infra/bootstrap_in_place.py
- discovery-infra/test_infra/helper_classes/config/nodes_config.py
- discovery-infra/test_infra/utils/cluster_name.py
Forcing cluster name to be of `ClusterName` type instead of str
> NO-ISSUE - Fix e2e-metal-single-node-live-iso test fails on cluster_name type mismatch

- scripts/run_minikube.sh
Sometimes ``minikube start`` fails.
Let's do a retry several times until it succeed.
/cc @YuviGold 
/hold
> MGMT-7048: retry if minikube creation failed

- Jenkinsfile.test
https://github.com/openshift/assisted-service/pull/2071 renamed
the pod when replacing scality with minio
> MGMT-7054: Get logs from new object-store pod

- discovery-infra/test_infra/helper_classes/kube_helpers/infraenv.py
The `agentLabelSelector` is not part of the InfraEnv Spec anymore.
> NO-ISSUE Remove AgentLabelSelector from InfraEnv

- discovery-infra/test_infra/consts/consts.py
- discovery-infra/test_infra/helper_classes/kube_helpers/agent.py
This is a follow-up PR for https://issues.redhat.com/browse/MGMT-6660 PR  https://github.com/openshift/assisted-test-infra/pull/895. This PR checks for the newly adjusted agent condition from https://github.com/openshift/assisted-service/pull/2135
> NO-ISSUE: Check agent's RequirementsMet condition

- discovery-infra/bootstrap_in_place.py
- discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
- discovery-infra/test_infra/helper_classes/cluster.py
- discovery-infra/test_infra/helper_classes/config/base_config.py
- discovery-infra/test_infra/helper_classes/config/nodes_config.py
- discovery-infra/test_infra/utils/cluster_name.py
- discovery-infra/test_infra/utils/global_variables/env_variables_utils.py
- discovery-infra/tests/base_test.py
- discovery-infra/tests/config/__init__.py
- discovery-infra/tests/config/global_configs.py
- discovery-infra/tests/test_e2e_install.py
- discovery-infra/tests/test_kube_api.py
- Move cluster name to cluster config scope
- Create configs fixture for getting single instance of configs per test.
-  Remove some of duplicate variables from ClusterConfig.
/cc @YuviGold @lalon4 
/test system-test-ipv6 system-test-olm system-test-operator e2e-metal-assisted-none e2e-metal-single-node-live-iso e2e-metal-assisted-single-node
QE PR: https://gitlab.cee.redhat.com/ocp-edge-qe/kni-assisted-installer-auto/-/merge_requests/369
> MGMT-7060 - Move cluster name to cluster config scope

- discovery-infra/download_logs.py
It's another one of those exceptions that we don't have a lot to do about.
/cc @YuviGold 
/hold
> MGMT-7155: ignore SCPException when sosreport gathering fails

- discovery-infra/test_infra/assisted_service_api.py
There is new `get_preflight_requirements` which replaces `get_host_requirements`. This PR removes obsolete method.
Signed-off-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>
> MGMT-6480 remove get_host_requirements

- discovery-infra/tests/base_test.py
To avoid failures like: https://auto-jenkins-csb-kniqe.apps.ocp4.prod.psi.redhat.com/job/ocp-assisted-installer-virt/2079/testReport/junit/test_ocs_validations/TestOCSValidations/Run_assisted_installer_Functional_API_Tests___test_ocs_standard_mode_three_workers_multiple_insufficient_disks/
> Avoid libvirt error during disks teardown

- discovery-infra/bootstrap_in_place.py
- discovery-infra/download_logs.py
- discovery-infra/test_infra/consts/consts.py
- discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py
- discovery-infra/test_infra/controllers/node_controllers/node_controller.py
- discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
- discovery-infra/test_infra/helper_classes/cluster.py
- discovery-infra/test_infra/helper_classes/config/cluster_config.py
- discovery-infra/test_infra/helper_classes/config/controller_config.py
- discovery-infra/test_infra/helper_classes/config/nodes_config.py
- discovery-infra/test_infra/helper_classes/nodes.py
- discovery-infra/test_infra/utils/global_variables/global_variables.py
- discovery-infra/test_infra/utils/terraform_util.py
- discovery-infra/test_infra/utils/utils.py
- discovery-infra/tests/base_test.py
- discovery-infra/tests/config/__init__.py
- discovery-infra/tests/config/global_configs.py
- discovery-infra/tests/conftest.py
- discovery-infra/tests/test_e2e_install.py
Adding a new simple fixture in addition to the generators fixtures
The purpose of fixtures is build the infrastructure before the act (which is the operation this we are testing) and the test (which is the actual assert statement)
The best practice about fixtures is to create a short single responsibility fixture to avoid tear down issues
Most of our tests just changing the configuration before continue with the installation
In this PR we have created a new flow with simple short fixtures to override that supports multi-platform installation
so you can just set the platform variable to for instance vsphere and that's it
In addition we organized the common configuration into a base classes with a minimum duplication
> MGMT-7153 support multi-platform test

- discovery-infra/tests/base_test.py
This PR fix error: https://auto-jenkins-csb-kniqe.apps.ocp4.prod.psi.redhat.com/job/ocp-assisted-installer-virt/2170/testReport/junit/test_ocs_validations/TestOCSValidations/Run_assisted_installer_Functional_API_Tests___test_ocs_standard_mode_three_workers_multiple_insufficient_disks/
which mistakenly removed here: https://github.com/openshift/assisted-test-infra/commit/e0d79b8148a0373433c27800828001d08b7e0146#diff-6162d2a9234339ec7bb76b9037da27056716d9d64db599e223c8d132bc05787dL5
> Fix libvirt error

- discovery-infra/test_infra/assisted_service_api.py
Remove the hard-coded domain and get it using `urlparse`
> NO-ISSUE - Improve the way of setting the API host address

- Makefile
When fetching multiple branches they are all being written to `FETCH_HEAD`
file.
```
➜  assisted-service git:(master) cat .git/FETCH_HEAD 
3f35d6cfad5156591fd76eb74dc37ffc5856a965		branch 'master' of https://github.com/rollandf/assisted-service
cd89ac9f840be3c1615bc1aefc1930adf2118858		branch 'MGMT-7148' of https://github.com/rollandf/assisted-service
```
It would be wiser not to depend on the `FETCH_HEAD` structure and just tag
the new branch as `FETCH_NEW`.
```bash
From https://github.com/rollandf/assisted-service
* [new branch]        master     -> FETCH_BASE
* [new branch]        MGMT-7148  -> FETCH_NEW
```
/cc @rollandf @osherdp
> Replace FETCH_BASE with FETCH_NEW

- Makefile
Reverts openshift/assisted-test-infra#986
It broke assisted-service e2e jobs.
```
Rebasing (1/1)
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: unable to auto-detect email address (got 'root@ipi-ci-op-x8p1cjjc-3bd5c-1419405114711478272.(none)')
```
> Revert "Replace FETCH_BASE with FETCH_NEW"

- discovery-infra/download_logs.py
- discovery-infra/log_scrap.py
- discovery-infra/monitoring/process.py
- discovery-infra/test_infra/utils/utils.py
From [here](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.9-e2e-metal-assisted-ipv6/1419634763982966784):
```
/home/assisted/discovery-infra/download_logs.py:175: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
So using ```log.warning``` instead.
/cc @YuviGold
> Move from log.warn to log.warning

- discovery-infra/tests/pytest.ini
Without this fix, you'll get:
```
discovery-infra/tests/test_kube_api.py:45
/home/assisted/discovery-infra/tests/test_kube_api.py:45: PytestUnknownMarkWarning: Unknown pytest.mark.kube_api - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
@pytest.mark.kube_api
```
(from https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_assisted-service/2301/pull-ci-openshift-assisted-service-ocm-2.3-e2e-metal-assisted-kube-api/1420643061754499072/artifacts/e2e-metal-assisted-kube-api/baremetalds-assisted-setup/build-log.txt)
/cc @YuviGold @michaellevy101 
/hold
> Add kube-api mark to pytest markers list

- discovery-infra/test_infra/helper_classes/cluster.py
Configure DNS on none-platform before waiting for AI to be ready for install
Since new DNS validations have been added to AI for none-platform installations,
AI will not become ready to install until DNS is properly configured.
Until now, the test infra configured the DNS entries for none-platform
only AFTER it waited for AI to become ready. But now AI will not become
ready until those DNS entries have been configured. This caused the waiting
function to time-out in none-platform tests ever since the DNS
validations PR has been merged.
This commit fixes that problem by configuring the relevant DNS entries before
waiting for AI to become ready.
References:
https://github.com/openshift/assisted-service/pull/1884 - DNS Validations PR
> NO-ISSUE: fix for None platform CI

- scripts/ibmcloud_post_install.sh
- scripts/install_environment.sh
This PR creates a post-install script that can be used on the IBM Cloud
machines so that they are deployed with a set of reasonable defaults.
> Create post-install script for IBM Cloud machines

- requirements.txt
This reverts commit 28876018 due to some issues on version > v0.1.24
/cc @YuviGold 
junit-report 0.1.32 uses new mechanism for handling pytest fixtures. Is cases some of the reports to show partially reports or no report at all.
It will probably will fix in the next version of junit-report
> Revert "Bump junit-report from 0.1.24 to 0.1.32 (#1013)"

- scripts/run_minikube.sh
Those removed configurations don't exist in newer versions of minikube.
Signed-off-by: Yoni Bettan <ybettan@redhat.com>
> NO-ISSUE: Removed some minikube configurations.

- discovery-infra/tests/base_test.py
There is a race between bootstrap rebooting and logs tests
actions that kills the installer on the bootstrap node
By making the interval for querying the controller 'Running' state
shorter and also considerably shorten the wait for log 'required'
state (see test_logs.py in kni-assisted-installer-auto) we hope
to reduce this race condition frequency
> NO-ISSUE: adjust wait for controller interval

- discovery-infra/download_logs.py
- discovery-infra/logger.py
Each cluster logs directory will have its own execution logs alongside the main one including all of them at the root directory.
```
➜  assisted-test-infra git:(MGMT-7571-attach-download-logs-file-handler) find -name test_infra.log -print -exec bash -c "cat {} | wc -l" \; 
./test_infra.log
404
./build/2021-08-16_06:41:04_5a0db5bd-ecb7-4328-96cf-f7f327088f8d/test_infra.log
49
./build/2021-08-14_00:06:23_98b65add-664a-4b8a-b257-e0f8d13390c4/test_infra.log
60
./build/2021-08-16_01:16:40_070bd54d-698d-428e-b0ae-a49795106f97/test_infra.log
49
./build/2021-07-12_03:12:51_c3f6a6fc-452b-4b37-8008-b06d26fd738d/test_infra.log
53
./build/2021-08-16_08:04:24_2ed6c980-bd2f-40cf-b805-57b9fd476a8b/test_infra.log
49
./build/2021-08-12_18:29:51_ea253f07-b5e5-4044-a7be-b80f49b189b4/test_infra.log
28 …
```
> MGMT-7571: Attach download logs directory with python logs

- discovery-infra/download_logs.py
When collecting logs, we make sure that must-gather is present and retry if not only if 2 nodes are in Joined state.
We need to support also when 2 nodes are in Done or Joined.
> MGMT-7577: Retry must-gather collection also when hosts are in Done state

- discovery-infra/test_infra/assisted_service_api.py
Asserting on return codes which are not 200 is probably not right and assertion message is not indicative enough about the error.
/cc @YuviGold 
/cc @nmagnezi 
/hold
> NO-ISSUE: raise an error for only relevant error codes

- discovery-infra/download_logs.py
Now when we're raising on an illegal HTTP status code, it makes sense to catch it and suppress it accordingly.
Relates to #1046 
/cc @nmagnezi @empovit @YuviGold 
/hold
> NO-ISSUE: catch also HTTPError when metrics endpoint is not accessible

- Dockerfile.test-infra
For some reason pip was not upgrading properly so it had issues when trying to build in the cryptography package. 
This moves the pip upgrade to the same image layer as the pip install commands.
[Link to failing build](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/21268/rehearse-21268-periodic-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-kube-api-periodic/1430217366439989248)
> NO-ISSUE: Fix pip not upgrading correctly in image build

- discovery-infra/bootstrap_in_place.py
machine
Added retry decorator in order to overcome SSL_ERROR_SYSCALL
> NO-ISSUE: Removed --retry-all-errors due to old curl version in the CI

- discovery-infra/test_infra/helper_classes/cluster.py
fix test failures:
https://auto-jenkins-csb-kniqe.apps.ocp4.prod.psi.redhat.com/job/ocp-assisted-installer-virt/2995/testReport/junit/test_ocm_integration/TestOCMIntegration/Run_assisted_installer_Functional_API_Tests___test_ocm_subscription_is_updated_with_display_name/
https://auto-jenkins-csb-kniqe.apps.ocp4.prod.psi.redhat.com/job/ocp-assisted-installer-virt/2997/testReport/junit/test_validations/TestValidations/Run_assisted_installer_Functional_API_Tests___test_hosts_and_cluster_max_length/
caused by change: https://github.com/openshift/assisted-test-infra/pull/1057
> Fix broken set_cluster_name method

- discovery-infra/test_infra/controllers/node_controllers/node.py
Adding service restart method, for tests that require service restarts on non-persistent changes
> Adding service restart method

- scripts/deploy_assisted_service.sh
Modified the ocp_versions filterring for kube-api/operator to support versions >= 4.8.
> MGMT-7643: supporting versions newer than 4.8 on deploy

- discovery-infra/resources/man_sosreport.sh
The previous one we used doesn't always exist: only on the bootstrap and during bootstrapping phase.
/cc @eranco74 @tsorya 
/test e2e-metal-assisted-ipv6
/hold
> Use kubeconfig path that always exists

- discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py
Got into this error while calling the node.mac[0]
```
def _get_domain_ips_and_macs(domain):
interfaces = dict(
**domain.interfaceAddresses(libvirt.VIR_DOMAIN_INTERFACE_ADDRESSES_SRC_LEASE),
>           **domain.interfaceAddresses(libvirt.VIR_DOMAIN_INTERFACE_ADDRESSES_SRC_ARP)
)
E       TypeError: type object got multiple values for keyword argument 'vnet31'
```
> Fix dictionary update for _get_domain_ips_and_macs()

- Makefile
- discovery-infra/tests/conftest.py
- discovery-infra/tests/test_e2e_install.py
The test will run the different networking options assisted supports
like `network_type` and `static_ips` modes.
> MGMT-7744: Add test_networking test

- discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py
Sometimes the interfaces aren't available
```
File "/home/assisted/discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py", line 459, in _get_domain_ips_and_macs
interfaces = dict(domain.interfaceAddresses(libvirt.VIR_DOMAIN_INTERFACE_ADDRESSES_SRC_LEASE))
File "/usr/local/lib64/python3.6/site-packages/libvirt.py", line 1657, in interfaceAddresses
raise libvirtError('virDomainInterfaceAddresses() failed')
libvirt.libvirtError: Requested operation is not valid: domain is not running
```
We should try to get all the available IPs and ignore failures in that case.
/cc @osherdp
> Ignore libvirt errors when trying to get domain ips and macs

- discovery-infra/install_cluster.py
- discovery-infra/test_infra/consts/consts.py
- discovery-infra/test_infra/helper_classes/kube_helpers/agent.py
- discovery-infra/test_infra/utils/global_variables/env_variables_defaults.py
- discovery-infra/tests/base_test.py
- discovery-infra/tests/test_kube_api.py
- scripts/deploy_assisted_service.sh
- Update load balancer endpoint dynamically according to the
assisted-service route.
- [MGMT-6788](https://issues.redhat.com/browse/MGMT-6788): Fix `ClusterName` to be an object instead of a string.
- [MGMT-7082](https://issues.redhat.com/browse/MGMT-7082): Use a different namespace for the hub and the spoke
clusters. By default `assisted-spoke-cluster`. Can be overriden with
`SPOKE_CLUSTER` environment variable.
/cc @eliorerz 
Depends on https://github.com/openshift/release/pull/21441
/test system-test-operator
/hold
> MGMT-5274: Fix test_kube_api

- scripts/install_environment.sh
https://rpmfind.net/linux/centos/8.3.2011/ path is [depricated](https://rpmfind.net/linux/centos/8.3.2011/readme). Using https://rpmfind.net/linux/centos/8 instead
> Use rpmfind.net/linux/centos/8 path to install libgcrypt

- Makefile
We've noticed that, depending on whether you run with podman, docker,
`--net=host` and also the time you run the container all have the
potential to give the `/etc/resolv.conf` inside the container different
values. Instead of relying on these parameters, we now force the container
to use the host DNS server by passing `podman` the `--dns=127.0.0.1` flag
(along with the `--net=host` flag that was already there).
It seems that when running the load balancer in the CI, its DNS
configuration had an incorrect value and as a result the load balancer
could not connect to the hub cluster's assisted service, resulting in
agents that rely on this load balancer to not be able to register with
the service.
/cc @YuviGold
> NO-ISSUE: Force load balancer container to use the host as DNS

- discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py
- discovery-infra/test_infra/helper_classes/cluster.py
- discovery-infra/test_infra/helper_classes/infra_env.py
- discovery-infra/test_infra/helper_classes/nodes.py
- discovery-infra/test_infra/utils/operators_utils.py
/cc @tsorya 
/cc @carbonin 
/cc @osherdp 
/cc @eliorerz 
/hold
/test e2e-metal-assisted-networking
> NO-ISSUE: Check IPS on static IPs mode

- discovery-infra/download_logs.py
- discovery-infra/logger.py
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.9-e2e-metal-assisted-ipv6/1420661063333974016/artifacts/e2e-metal-assisted-ipv6/baremetalds-assisted-gather/build-log.txt
```
2021-07-29 09:52:04,989 ERROR      - 140416225086336 - <class 'assisted_service_client.rest.ApiException'> 	(/home/assisted/discovery-infra/logger.py:37)
Traceback (most recent call last):
File "./discovery-infra/download_logs.py", line 143, in download_logs
os.path.join(output_folder, "cluster_files", cluster_file))
File "/home/assisted/discovery-infra/test_infra/assisted_service_api.py", line 253, in download_and_save_file
cluster_id=cluster_id, file_name=file_name, _preload_content=False
File …
```
> NO-ISSUE - Fix logs failing while trying to download custom_manifests.yaml file

- discovery-infra/test_infra/assisted_service_api.py
- discovery-infra/test_infra/helper_classes/cluster.py
- discovery-infra/test_infra/helper_classes/config/base_infra_env_config.py
- discovery-infra/test_infra/helper_classes/infra_env.py
- discovery-infra/tests/base_test.py
This PR:
- uses infraenv to create and download cluster image
- moves api client to use v2_register_cluster to create a new cluster
- use infraenv to update host roles and names
> MGMT-7928: Use infrenv api to generate and download image

- Makefile
Detect if we are running in an assisted-service pull request in Openshift CI or not.
```
[lranjbar@fedora assisted-test-infra]$ make bring_assisted_service 
Running in assisted-service pull request
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 5 (delta 3), reused 5 (delta 3), pack-reused 0
Unpacking objects: 100% (5/5), 2.92 KiB | 995.00 KiB/s, done.
From https://github.com/openshift/assisted-service
* [new ref]           refs/pull/2829/head -> assisted-service-pr-2829
Switched to branch 'assisted-service-pr-2829'
```
vs
```
[lranjbar@fedora assisted-test-infra]$ make bring_assisted_service 
From https://github.com/openshift/assisted-service
* branch              master     -> FETCH_HEAD
HEAD …
```
> MGMT-8058: Add logic to detect if running in Openshift CI

- discovery-infra/test_infra/utils/global_variables/global_variables.py
When using ``NETWORK_TYPE=OVNKubernetes`` the cluster cannot become ready.
That leaves the cluster in a state that has no apparent affect, so we should change the default mode we're working with.
/cc @eliorerz
> NO-ISSUE: disable VIP DHCP allocation when using OVNKubernetes

- discovery-infra/test_infra/tools/terraform_utils.py
Without ``capture_output=True`` the returned error do not contain stdout and stderr of the failing command.
Adding that to have more verbosity when errors occur.
/cc @lalon4 @eliorerz
> NO-ISSUE: capture stdout and stderr on terraform failure

- discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py
- discovery-infra/test_infra/helper_classes/cluster.py
- discovery-infra/test_infra/helper_classes/config/base_config.py
- discovery-infra/test_infra/helper_classes/nodes.py
- discovery-infra/test_infra/utils/global_variables/global_variables.py
- discovery-infra/test_infra/utils/global_variables/triggerable.py
- discovery-infra/tests/test_e2e_install.py
Fix flaky networking test,
Fixes in this PR:
-  It's seems like the API returns MAC address that are not yet available on libvirt, so now the test is waiting for all test-infra nodes to have MAC and IP address before setting hostnames and roles
- Fix `VIP DHCP allocation is not supported when the cluster is configured to use OVNKubernetes` error message by adding trigger that set `vip_dhcp_allocation` to False when `OVNKubernetes` is selected
- Fix triggering mechanism not working with pytest parametrize
https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/periodic-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-networking-periodic
/cc @tsorya @osherdp
> MGMT-7983 - Fix e2e-metal-assisted-networking flaky test

- discovery-infra/start_discovery.py
- discovery-infra/test_infra/consts/consts.py
- discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
- discovery-infra/test_infra/tools/static_network.py
- discovery-infra/test_infra/utils/kubeapi_utils.py
- discovery-infra/test_infra/utils/utils.py
- terraform_files/baremetal/main.tf
- terraform_files/baremetal_host/consolemodel.xsl
- terraform_files/baremetal_host/main.tf
- terraform_files/baremetal_host/variables.tf
- terraform_files/baremetal_infra_env/main.tf
- terraform_files/none/main.tf
Currently we have a couple of terraform templates, each for a different installation flow:
* One for most scenarios, including (but not limited) to: ipv4, ipv6, static-networking, defining multiple disks for olm operators like lso, bootstrap-in-place mode for installing SNO just via openshift installer, and more
* None platform scenario. In this case it has a different networking structure where masters and workers are split between several L3 networks
* infra-env template for late-binding scenarios
This PR should remove some of the existing duplication by creating a module for baremetal hosts, and including it in the larger template.
It (currently) doesn't solve some of the duplication that we have regarding networks, DNS configuration etc., but that should be a good start either way.
> Refactor terraform templates to use baremetal_host module

- discovery-infra/day2.py
- discovery-infra/start_discovery.py
- discovery-infra/test_infra/tools/static_network.py
After refactoring on #1201, it seems like we're duplicating the ``baremetal`` template dir in the path:
```
def generate_static_network_data_from_tf(tf_folder: str) -> List[Dict[str, List[dict]]]:
tfvars_json_file = os.path.join(tf_folder, consts.Platforms.BARE_METAL, consts.TFVARS_JSON_NAME)
>       with open(tfvars_json_file) as _file:
E       FileNotFoundError: [Errno 2] No such file or directory: 'build/terraform/test-infra-cluster-dd1a1a93/baremetal/baremetal/terraform.tfvars.json'
```
(taken from https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-test-infra/1144/pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-networking/1455801552945025024)
This should fix the duplications.
/cc @eliorerz  …
> NO-ISSUE: fix static IP mode after terraform refactoring

- discovery-infra/test_infra/tools/terraform_utils.py
From time to time we are failing to init tf during regression runs i.e
"Failed to\nrequest discovery document: Get\n"https://registry.terraform.io/.well-known/terraform.json": dial tcp: lookup\nregistry.terraform.io on 127.0.0.1:53: read udp 127.0.0.1:53546->127.0.0.1:53:\ni/o timeout\n\x1b[0m\x1b[0m\n'"
This PR add a retry on tf init.
We have same retry on other flows in our QE Jenkins and seems like this retry helps to reduce the occurrence of such failure
> Adding a retry on tf init

- discovery-infra/test_infra/helper_classes/cluster.py
- discovery-infra/test_infra/helper_classes/events_handler.py
- discovery-infra/test_infra/helper_classes/nodes.py
- discovery-infra/test_infra/tools/terraform_utils.py
- discovery-infra/tests/base_test.py
See https://github.com/openshift/assisted-test-infra/pull/1153 for more information and motivation
/cc @osherdp
FYI @nshidlin @lalon4 
Deprecated methods on this PR:
1. `Cluster.get_events` - Now can be used as part of `EventsHandler`, note that cluster_id is no longer part of this class.
2. `Cluster.wait_for_event` - Now can be used as part of `EventsHandler`, note that cluster_id is no longer part of this class.
3. `Cluster.EVENTS_THRESHOLD` - Will permanently be removed after will no longer be in use (if needed on specific test - it can be declared there)
> MGMT-7977 - Move test-infra events from Cluster to separate object

- scripts/install_minikube.sh
* Updates minikube to the latest version [1.23.2](https://github.com/kubernetes/minikube/releases/tag/v1.23.2) as I started facing the known issue where the IP of the host was <pending> when waiting for the assisted-service to be ready:
```
python3 ./tools/wait_for_assisted_service.py --target local --namespace "assisted-installer" \
--domain "" --apply-manifest True
Wait for http://<pending>:8090/ready
Wait for http://<pending>:8090/ready
```
Using the 1.23.2 version I am now able to see the IP reflected:
```
python3 ./tools/wait_for_assisted_service.py --target local --namespace "assisted-installer" \
--domain "" --apply-manifest True
Wait for http://10.99.47.174:8090/ready
Wait for http://10.99.47.174:8090/ready
```
* Pins the OCP client to use the …
> NO-ISSUE: Update minikube to 1.23.2 and pin OCP client to stable-4.8

- scripts/install_minikube.sh
Seems like on #1196 we installed by accident openshift-installer instead of oc.
/cc @eliorerz @eranco74 @jordigilh 
/hold
/test e2e-metal-single-node-live-iso
> NO-ISSUE: fix installation of oc with the right artifact

- discovery-infra/test_infra/assisted_service_api.py
- discovery-infra/test_infra/helper_classes/cluster.py
- discovery-infra/test_infra/helper_classes/entity.py
- discovery-infra/test_infra/helper_classes/infra_env.py
- discovery-infra/test_infra/utils/utils.py
From [MGMT-8193](https://issues.redhat.com/browse/MGMT-8193):
> Currently whenever we need to download the discovery iso during a CI test we're using some API client which assumes we're using the download endpoint on assisted service.
> 
> When we move to the image service, that download url will no longer work and our tests will fail even though the flow for users would be unchanged.
> 
> We should be relying on the same url we present to users when we run CI (the one in the cluster image info and infraEnv).
> 
Deprecated methods in this PR:
1. `assisted_service_client._download`
2. `assisted_service_client.download_infraenv_image`
3. `assisted_service_client.download_image`
/cc @carbonin @osherdp 
FYI @lalon4 @nshidlin
> MGMT-8193 - Remove download_image logic from assisted_service_api.py and use infra_env.download_url to download it

- scripts/install_environment.sh
Bump libgcrypt version form `1.8.5-4` to `1.8.5-6` since version `1.8.5-4` can no longer be found in `rpmfind.net`:
```
$> curl --head -w "${http_code}" https://rpmfind.net/linux/centos/8/BaseOS/x86_64/os/Packages/libgcrypt-1.8.5-4.el8.x86_64.rpm
HTTP/1.1 404 Not Found
Date: Tue, 16 Nov 2021 16:14:58 GMT
Server: Apache/2.4.51 (Fedora) OpenSSL/1.1.1l
Content-Type: text/html; charset=iso-8859-1
```
But for version `1.8.5-6` it can be found:
```
$> curl --head -w "${http_code}" https://rpmfind.net/linux/centos/8/BaseOS/x86_64/os/Packages/libgcrypt-1.8.5-6.el8.x86_64.rpm
HTTP/1.1 200 OK
Date: Tue, 16 Nov 2021 16:15:35 GMT
Server: Apache/2.4.51 (Fedora) OpenSSL/1.1.1l
Last-Modified: Tue, 29 Jun 2021 20:39:30 GMT
ETag: "73a84-5c5ed9a5444c3"
Accept-Ranges: bytes
Content-Length: 473732 …
```
> NO-ISSUE: Bump libgcrypt version

- requirements.txt
It's probably a left-over from having triage creation in assisted-test-infra (it has been moved to assisted-installer-deployment)
/cc @eliorerz
> NO-ISSUE: remove jira from requirements.txt as it's not being used

- Makefile
- discovery-infra/day2.py
- discovery-infra/deprecated_utils.py
- discovery-infra/test_infra/consts/env_defaults.py
- discovery-infra/tests/test_day2.py
As e2e flows are now invoked using pytest, fixed day2 on cloud flow to accommodate for the new infra:
* Added test_day2.py - initialize and execute day2_cloud_flow
* Note: For simplicity, used day2.py mostly as-is. We can rewrite and move its logic into test_day2 later on. Also, should add support for the ocp flow.
> MGMT-8181: added day2 cloud flow to e2e tests

- scripts/install_environment.sh
Some fedora-like distributions come with a pretty outdated version of libgcrypt, making use of kvm unsustainable
Previously we tried installing a specific version from some source, but this source seems to remove versions from time to time which is inconvenient
This change will just make sure we upgrade the package to its latest version by using the official repositories of the distribution, which should be fine for all cases
> NO-ISSUE: always upgrade libgcrypt package using regular sources

- Dockerfile.assisted-test-infra
When copying the whole dir of assisted-tes-infra, we get:
```
tar: ./usr/libexec/utempter/utempter: Cannot open: Permission denied
```
Meaning it tries to copy the entire root directory.
This should change the working directory of the image to a different dir.
/cc @eliorerz
> Changing workdir to a different directory than /

- scripts/install_environment.sh
Basically a backport of #1248
Some fedora-like distributions come with a pretty outdated version of libgcrypt, making use of kvm unsustainable
Previously we tried installing a specific version from some source, but this source seems to remove versions from time to time which is inconvenient
This change will just make sure we upgrade the package to its latest version by using the official repositories of the distribution, which should be fine for all cases
Failing build for example:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/24063/rehearse-24063-pull-ci-openshift-assisted-test-infra-v1-e2e-metal-assisted/1465295302687723520
/cc @eliorerz
> Always upgrade libgcrypt package using regular sources (#1248)

- Makefile
The container command is being set before invoking the rules.
The Makefile rules should be using the variable instead of an explicit
container command, as it might not be avaiable in certain systems.
Signed-off-by: Moti Asayag <masayag@redhat.com>
> Use container command variable

- Jenkinsfile.download_logs
This should allow us testing triage-tickets automation with Jenkins.
The parameter will use master branch (as before) by default, but we'll be able to set it to other values when using "Build with Parameters".
/cc @eliorerz
> add a new parameter for setting assisted-installer-deployment branch

- Jenkinsfile.download_logs
Building up from openshift-assisted/assisted-installer-deployment#163, this should make our logs gathering jobs use personal access token.
/cc @eliorerz
> Use access-token when accessing Jira on Jenkins

- scripts/install_golang.sh
- scripts/setup_capi_provider_agent_env.sh
Added install_golang.sh that will install golang in case go isn't installed already
Call install_golang.sh from setup_capi_provider_agent_env.sh
Golang is required for the setup_capi_provider_agent_env.sh to work
> NO-ISSUE: Install Golang when setting up capi-provider env

- discovery-infra/test_infra/helper_classes/cluster.py
With https://github.com/openshift/assisted-service/pull/3042 we are
making it possible to create a dual-stack cluster in a single API call.
At the same time, it's no longer possible to create a dual-stack cluster
without providing Machine Networks from the very beginning. Because of
that, we are adapting test-infra to send the full cluster payload
instead of splitting it into two separate steps.
Contributes-to: [MGMT-8300](https://issues.redhat.com/browse/MGMT-8300)
> MGMT-8300: Apply dual-stack configuration in a single step

- discovery-infra/test_infra/helper_classes/hypershift.py
- discovery-infra/tests/test_kube_api.py
the test should end with a working hypershift cluster with at least one ready node
otherwise the minimal conformence test that runs afterwards fail due to
missing networks.operator.openshift.io "cluster"
> NO-ISSUE: updated the capi test

- Makefile
- scripts/utils.sh
```
...
New version of arkade installed to /usr/local/bin
/usr/bin/which: no ark in (/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin)
main: line 176: arkade: command not found
...
```
> NO-ISSUE - Fix arkade not found in PATH on some machines. Add /usr/local/bin to PATH.

- src/assisted_test_infra/test_infra/helper_classes/hypershift.py
Without passing the arg the wait_for_nodes return regardless of the
nodes ready status
> NO-ISSUE: wait_for_nodes should pass the ready option to the get_nodes method

- Makefile
- scripts/deploy_assisted_service.sh
- scripts/download_logs.sh
Seems like onprem deployment is broken for the following reasons:
* No value provided for ``ASSISTED_SERVICE_HOST``, which means that the service provides its URL with ``localhost:<port>`` domain, which of course not an appropriate address for the agent.
* Variable ``PUBLIC_CONTAINER_REGISTRIES`` has no default value alternative when used, and bash options forbid from having unbound variables.
* Variable ``ASSISTED_SERVICE_HOST`` not being propagated to the service deployment script.
/cc @eliorerz
> MGMT-8598: fix provided variables for onprem deploy target

- scripts/override_os_images.py
Previously this script would edit the image entry in place as well as
appending a new image to the list.
The existing entry should not be edited and the new entry should be made
unique by manufacturing a "version" value. This will prevent the image
service from failing due to [MGMT-8661](https://issues.redhat.com/browse/MGMT-8661).
https://issues.redhat.com/browse/MGMT-8660
https://issues.redhat.com/browse/MGMT-8661
https://bugzilla.redhat.com/show_bug.cgi?id=2012844
Failing job https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.10-e2e-metal-assisted/1472933614353125376
> MGMT-8660: Fix os image override script

- terraform_files/baremetal/main.tf
- terraform_files/baremetal_host/main.tf
- terraform_files/baremetal_infra_env/main.tf
- terraform_files/none/main.tf
Back in #1254, we decided to use forked libvirt-provider until we have a newer version.
Now that there's a new version, we can use the upstream provider again.
/cc @nmagnezi @eliorerz
> Go back to using upstream terraform-libvirt-provider

- scripts/download_logs.sh
On openshift/assisted-service#3096, we will use a new container name for assisted-service.
This should gather logs from both names, until we'll do the transition.
/cc @eliorerz
> allow gathering from the new name of assisted-service container

- README.md
Update README, no need to disable the api-vip-connected validation
> MGMT-8423: remove hack for disable day2 validation

- scripts/run_minikube.sh
When the CI jobs fail to start minikube it instructs to get the logs with this command.
Hopefully, this will help us understand why minikube fail to start
https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/rehearse-24867-pull-ci-openshift-cluster-api-provider-agent-master-e2e-capi-provider-hypershift
> NO-ISSUE: Get minikube logs in case it failed to start properly

- scripts/run_minikube.sh
`minikube logs` return non 0 exit code in case minikube API isn't available
Failure to restartlibvirtd shouldn't fail the script as well
> NO-ISSUE: don't fail the run_minikube script in case of failure to get the logs

- terraform_files/baremetal/main.tf
- terraform_files/baremetal_host/main.tf
- terraform_files/baremetal_host/variables.tf
- terraform_files/baremetal_infra_env/main.tf
- terraform_files/none/main.tf
- terraform_files/none/variables-libvirt.tf
On some occasions, the none-platform environment test is getting into the following situation:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-none-periodic/1474880968832585728
In this case, the libvirt domains have an unintended network device attached, which is of type ``user``. When declaring part of the terraform fields for a network, it seems like it creates those kind of networks of type ``Userspace SLIRP stack``, and it probably adds some flakiness. This yielded the unintended generation of those networks.
This change should only declare whole networks, with the added benefit of being more general and provide ``networks`` (and not ``primary_network`` and ``secondary_network``).
> Fixing none-platform network interfaces

- Makefile
- scripts/download_logs.sh
Assisted-test-infra can run cluster-api-provider-agent e2e tests.
This PR adds log gathering of the provider pod and the relevant CRs content
> MGMT-8705: Collect capi-provider-agent logs

- Jenkinsfile
- Jenkinsfile.download_all_logs
- Jenkinsfile.download_logs
- Jenkinsfile.test
- Makefile
- scripts/deploy_assisted_service.sh
- scripts/deploy_ui.sh
Seems like there's a simpler way to make skipper interactive every time it's being called, which is the ``SKIPPER_INTERACTIVE`` environment variable.
It's not enabling to customize skipper params, but I don't really think it's in wide use.
/cc @eliorerz
> Use skipper interactive env-var

- Dockerfile.assisted-test-infra
Seems like it's missing from the new Dockerfile, since #1290
/cc @eliorerz
> install go on py39 Dockerfile

- src/assisted_test_infra/test_infra/helper_classes/config/base_config.py
- src/assisted_test_infra/test_infra/utils/operators_utils.py
- src/consts/olm_operators.py
- src/tests/base_test.py
- src/tests/test_e2e_install.py
Use cluster fixture in test_olm_operator instead of outdated fixture get_cluster.
Raise error on new_cluster_configuration on missing ClusterConfig attribute
/cc @osherdp
> MGMT-8769- Fail olm test on operator failure.

- scripts/deploy_assisted_service.sh
Probably because of #1341, we have the following failures in all periodic jobs:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-networking-periodic/1477610760195543040
When calculating overridden ``RELEASE_IMAGES``, it complains with this error:
```
time="2022-01-02T12:21:52Z" level=warning msg="The input device is not a TTY. The --tty and --interactive flags might not work properly"
```
If possibly brings an output will line-break at start:
```
RELEASE_IMAGES='
[{"openshift_version":"4.6","cpu_ ...
```
and when trying to use it, it complains:
```
python3 ./tools/deploy_assisted_installer_configmap.py --target "local" --domain "" \
--base-dns-domains """" --namespace "assisted-installer" \
--auth-type "none"  \ …
```
> Use interactive mode when running skipper externally

- .github/dependabot.yml
Seems reasonable we're mostly concerned about those packages than others.
/cc @eliorerz
> Assign pip packages maintainers when bumping dependencies

- src/tests/global_variables/triggers.py
Seems like we always override SNO installations with OCP 4.8, instead of going with what the user chose on ``OPENSHIFT_VERSION`` or ``OPENSHIFT_INSTALL_RELEASE_IMAGE``.
/cc @eliorerz
> fix SNO installations always picking OCP 4.8

- src/assisted_test_infra/test_infra/helper_classes/config/base_config.py
`typing` objects are a bit different on python 3.9.
> NO-ISSUE - Fix type checking on python 3.9

- src/assisted_test_infra/download_logs/download_logs.py
- src/service_client/assisted_service_api.py
For debugging cluster installation failures in triage and CI
we need to inspect the custom manifests that the user uses
for the installation
This code download the user custom manifests into
cluster_files/manifest folder when invoking
download_logs.sh
> NO-ISSUE: download manifests

- scripts/deploy_assisted_service.sh
Before this change, we just tried to use assisted-service's makefile with dependencies installed by assisted-test-infra on the host.
I brought up the following error on [onprem-periodic jobs](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-onprem-periodic/1479975943459049472):
```
make[1]: Leaving directory '/home/assisted/assisted-service'
+ sed -i 's|HW_VALIDATOR_REQUIREMENTS=.*|HW_VALIDATOR_REQUIREMENTS=[{"version":"default","master":{"cpu_cores":4,"ram_mib":16384,"disk_size_gb":120,"installation_disk_speed_threshold_ms":10,"network_latency_threshold_ms":100,"packet_loss_percentage":0},"worker":{"cpu_cores":2,"ram_mib":8192,"disk_size_gb":120,"installation_disk_speed_threshold_ms":10,"network_latency_threshold …
```
> install assisted-service-build dependencies before using makefile

- src/tests/global_variables/triggers.py
Some jobs like ``assisted-ipv6`` or ``assisted-kube-api`` will always choose OCP 4.8 because of the triggering mechanism:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/24876/rehearse-24876-pull-ci-openshift-assisted-service-master-e2e-metal-assisted-kube-api/1480177853029945344
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/24876/rehearse-24876-pull-ci-openshift-assisted-service-master-e2e-metal-assisted-ipv6/1480177852476297216
Removing it, since anyway we're using 4.9 by default.
/cc @eliorerz
> remove overriding ocp version when on ipv6

- Jenkinsfile.download_logs
It's no longer used, as we have notifications and reports for it.
/cc @mkowalski @eliorerz
> remove creating tickets based on failed CI tests

- src/assisted_test_infra/test_infra/helper_classes/cluster.py
- src/assisted_test_infra/test_infra/helper_classes/entity.py
- src/assisted_test_infra/test_infra/helper_classes/infra_env.py
- src/service_client/assisted_service_api.py
When using `make deploy_nodes CLUSTER_ID="<id>"` test-infra is not checking for an existing InfraEnv, and will instead create a new one (per each run).
This PR added infra_env check before creating a new one, and if it is already exists it's using the existing one.
/cc @osherdp
> MGMT-8670 - Fix deploy_nodes with CLUSTER_ID creates a new InfraEnv.

- Makefile
Fix kubeapi e2e makefile target returning the wrong return-code and causing failures in the test not to fail the job.
> MGMT-8967 - Change kubeapi test Makefile target return code

- scripts/deploy_assisted_service.sh
The service config when deploying with podman is now defined in a
ConfigMap instead of a flat file.
> MGMT-8716: uses new way of configuring podman deployment

- src/tests/test_bootstrap_in_place.py
The purpose of this workflow is to save costs after this change as currently this test demands a 45GB virtual machine.
Coupled with work in [MGMT-8844](https://issues.redhat.com/browse/MGMT-8844) where the SNO validation limit has been reduced to 16GB, it would make sense to reduce this also.
So we have done this.
> MGMT-9037:  Use a cheaper packet plan for baremetalds-sno-workflow

- Dockerfile.assisted-test-infra
Seems like starting today we get the following errors:
```
STEP 5: RUN dnf -y install   make   gcc   unzip   wget   curl   git   podman   httpd-tools   jq   nss_wrapper   python39   python39-devel   libvirt-client   libvirt-devel   libguestfs-tools   dnf-plugins-core     && dnf config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo     && dnf -y install packer     && dnf clean all
CentOS Linux 8 - AppStream                      124  B/s |  38  B     00:00    
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```
I couldn't find any official message about CentOS deprecation, but either way it's a good idea to do that change.
/cc @eliorerz
> NO-ISSUE: use stream8 distribution as centos 8 is EOL

- Dockerfile.assisted-test-infra
govc is a vSphere CLI used by the CI job
> MGMT-7105: adding govc to the test-infra docker file

- src/day2.py
- src/service_client/assisted_service_api.py
Ensured only v2 APIs are used in day2 test:
* v2_import_cluster (instead of register_add_hosts_cluster)
* create_infra_env (instead of generate_cluster_iso)
> MGMT-8103: day2 test - migrate to v2 API

- Dockerfile.assisted-test-infra
Openshift runs containers as root group and assigns user IDs arbitrarily for security reasons.
Since this image has been built as root, the arbitrarily user does not have permission to write to the assisted-test-infra folder.
Allow root group write access to the folder, so that arbitrary users can write there
Please see: https://docs.openshift.com/container-platform/4.9/openshift_images/create-images.html#images-create-guide-openshift_create-images
> Supporting arbitrary user ids

- Makefile
Backport of:
- https://github.com/openshift/assisted-test-infra/pull/1306
/cc @osherdp
> [release-ocm-2.4] MGMT-9102: Fix kubeapi makefile target

- Dockerfile.assisted-test-infra
The Hashicorp Packer tool conflicts with the Arch Linux packer on Centos.
Below are the error messages we are seeing:
/usr/share/cracklib/pw_dict.pwd: Permission denied
/usr/share/cracklib/pw_dict: Permission denied
Due to this error, we are renaming Hashcorp packer to packer.io
> Fixing a conflict with the packer executable

- src/assisted_test_infra/test_infra/helper_classes/infra_env.py
- src/consts/consts.py
Added a condition to get either cluster events or infra env events,
In addition - minimal iso flow is broken. Fixed by passing image_type to infra_env creation.
> Fix image_type param in infra_env and adding minimal iso event

- src/tests/test_bootstrap_in_place.py
Single Node installations in the near future are going to default to
OVNKubernetes, we want to test beforehand that it works as expected.
This commit will make Single Node baremetal CI use OVNKubernetes rather
than OpenShiftSDN.
> MGMT-9178: single-node CI should use OVNKubernetes as the network type

- src/assisted_test_infra/test_infra/helper_classes/hypershift.py
- src/tests/test_kube_api.py
As a workaround, the test will wait for the hypershift kube-api to return
a response before adding nodes to it
> MGMT-9183: capi test fail while waiting for machine controller to setowner ref on agentMachine

- src/tests/test_kube_api.py
On the new libvirt version we will get error while trying to change the `bootstrap_in_place` variable.
Also we don't need to set bootstrap_in_place in kube-api test flow.
/cc @tsorya
> Remove set of `bootstrap_in_place` in kubeapi test

- create_full_environment.sh
- scripts/install_environment.sh
Following [MGMT-9273](https://issues.redhat.com/browse/MGMT-9273), we should first allow installations on Rocky Linux.
This change mainly enables usage and make sure test-infra stay our of the way, but it also does the following temporary hack (and only for Rocky Linux):
```sudo dnf install libvirt-6.0.0-37.module+el8.5.0+670+c4aa478c```
This is because Rocky installs by default a slightly newer version which brings up the following error when deploying the hosts:
```
module.masters[2].libvirt_domain.host: Creating...
module.masters[1].libvirt_domain.host: Creating...
module.masters[0].libvirt_domain.host: Creating...
Warning: Experimental feature "module_variable_optional_attrs" is active
on ../baremetal_host/main.tf line 9, in terraform:
9:   experiments = …
```
> MGMT-9273: allow installation on rocky linux

- Makefile
Fixes the `all` target by replacing `full_flow_with_install` with  `deploy_nodes_with_install` target as it is documented in the [README.md](https://github.com/openshift/assisted-test-infra/blob/master/README.md#run-full-flow-with-install), since the `run_full_flow_with_install` no longer exists due to this [PR](https://github.com/openshift/assisted-test-infra/commit/87ef5d0e1492a69e975419e165f73ae0afbdb234#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L252).
@osherdp can you take a look at your convenience?
> NO-ISSUE: Fix make all target

- create_full_environment.sh
- requirements.txt
- scripts/install_environment.sh
Since https://github.com/openshift/release/pull/25960, we provision Rocky Linux in our CI workflows.
This is a manual backport of #1462, which is required for test-infra to allow Rocky Linux OS to be used, and to install the specific libvirt version we need in that OS.
/cc @eliorerz @michaellevy101
> NO-ISSUE: allow usage of Rocky Linux OS

- src/tests/conftest.py
https://github.com/openshift/assisted-service/pull/3380 caused KeyError when trying to get the default version (if `OPENSHIFT_VERSION` is set to version different than the default version). 
In that case we tried to get the default version even if it's not exists in the service. 
The solution to this issue is: moving the `default_version` after the 'override_version' (`OPENSHIFT_VERSION`). 
/cc @osherdp
> NO-ISSUE - Fix missing default version on specific openshift version

- scripts/install_minikube.sh
Update arkade domain due to changes made on
https://github.com/alexellis/arkade/commit/d7d1e59e18663c74ae538270cc3b4d9b3a637c24
This is a backport of #1487, as it happens for this branch as well:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-service/2961/pull-ci-openshift-assisted-service-release-ocm-2.4-e2e-metal-assisted/1498302543682342912
> NO-ISSUE: fix arkade DNS to the updated one

- scripts/install_minikube.sh
Currently we are using `arkade` to install minikube and kubectl during environment setup.
After the change of `arkade` domains (that caused our CI to fail), we reconsidered the usage in this tool.
This PR also upgrade:
- `minikube` - from v1.20.0 to latest (v1.25.2)
- `kubectl` - from v1.20.1 to latest (v1.22.0)
/cc @osherdp
> NO-ISSUE - Remove arkade dependency

- .flake8
See comments in diff for more information
F403 (https://www.flake8rules.com/rules/F403.html) was removed because
we don't seem to be violate it anywhere anyway
> NO-ISSUE: Improve .flake8 rules and documentation

- src/assisted_test_infra/test_infra/utils/release_image_utils.py
- src/deprecated_utils.py
- src/tests/test_bootstrap_in_place.py
We've been hardcoding the URL for the 4.8 RHCOS, we should use an RHCOS image associated with the
OCP release being tested instead. We can get the URL for that RHCOS from
the installer
Also added retry loop to the ignition embed function, to deal with occasional
quay hiccups
> NO-ISSUE: Bootstrap-in-place test flow should use RHCOS images fitting the OCP version tested

- src/tests/test_bootstrap_in_place.py
Seems like #1452 broken sosreport gathering by passing in a non-existing log parameter to this function.
/cc @eliorerz 
/hold
> MGMT-9471: fix sosreport gathering on BIP test

- src/triggers/default_triggers.py
OpenShiftSDN network type is not supported with SNO,
so use OVNKubernetes for SNO targets.
> MGMT-9177: Make OVN network type for SNO

- Makefile
Currently the kubeapi flow for `deploy_nodes_with_install` is not implemented.
Until we do implement it, lets print a proper error message.
```bash
$ ENABLE_KUBE_API=true make deploy_nodes_with_install 
Not implemented
make: *** [Makefile:236: deploy_nodes_with_install] Error 1
```
/cc @osherdp
> NO-ISSUE - Notify on not implemented kubeapi deploy_nodes_with_install deploy target

- Makefile
With https://github.com/openshift/release/pull/26831 we now publish a
valid index in edge-infrastructure.
This reverts commit f132534d550239d7fb59f80c90c1396654dd2756.
> MGMT-9470: Use edge-infrastructure index

- Makefile
- scripts/setup_capi_env.sh
This should allow the capi jobs to run without cloning and building the hypershift repo
> Use hypershift-operator image for installing hypershift

- src/tests/test_bootstrap_in_place.py
The curl `-L/--redirect` flag tells curl it should follow HTTP 302
redirect responses. Without it, the ISO file we get is invalid:
```
$ cat installer-image.iso
<html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.16.1</center>
</body>
</html>
```
During single-node-bootstrap-in-place tests, we download the RHCOS image
corresponding to the openshift release we're testing.
Looks like recently the ISO file corresponding to the 4.9 release image
we're testing is behind a redirect, which caused all single-node 4.9
live-iso jobs to fail.
This should fix that
> NO-ISSUE: RHCOS ISO download links sometimes have a 302 redirect, handle it with curl

- src/assisted_test_infra/test_infra/utils/utils.py
- src/service_client/assisted_service_api.py
Removed client.update_hosts func and usage in utils.
Should use update_host instead for fixing day2 flow.
> NO-ISSUE: remove deprecated client.update_hosts func

- src/assisted_test_infra/test_infra/helper_classes/day2_cluster.py
- src/assisted_test_infra/test_infra/utils/utils.py
* Moved update_hosts from utils to day2_cluster.
* Used client.update_host instead of deprecated client.update_hosts.
> MGMT-9568: use client.update_host instead of update_hosts

- src/consts/consts.py
- src/tests/global_variables/default_variables.py
- src/triggers/default_triggers.py
It has been observed that while testing against production, there is an
issue with disk validation on workers. It has been found that setting
the disk size of a worker to 128GB resolves the issue. This trigger has
been added to ensure that this happens.
> MGMT-9549:Trigger for remote deploy HW specs

- Makefile
- README.md
This PR removes the deprecated/broken Makefile rule `install_cluster`, introduced in PR #1393.
> Fixup on PR 1393

- src/tests/test_kube_api.py
This should solve the failing tests due to ` Timeout of 60 seconds expired waiting for clusterDeployment to get created`
e.g.
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_assisted-service/3406/pull-ci-openshift-assisted-service-master-e2e-metal-assisted-capi/1498926596482928640/artifacts/e2e-metal-assisted-capi/assisted-baremetal-setup/build-log.txt
> MGMT-8859: The creation of cluster deployment depends on the control plane so the test should wait for thee control plane first

- src/tests/pytest.ini
- Prevent from pytest to log warning at the end of the test.
e.g.
```
src/tests/test_kube_api.py:336
/home/assisted/src/tests/test_kube_api.py:336: PytestUnknownMarkWarning: Unknown pytest.mark.override_controller_configuration - is this a typo?
```
/cc @osherdp
> MGMT-9558: Adding the custom fixtures to pytest.ini file.

- src/service_client/assisted_service_api.py
patch_cluster_discovery_ignition is not used and referenced
V1 DiscoveryIgnitionParams that is going away from assisted API.
> MGMT-9609: Remove unused V1 patch_cluster_discovery_ignition

- scripts/ibmcloud_post_install.sh
With CentOS being deprecated, we need to install epel-release from
Fedora repositories so that when using RHEL, we have access to all the
required packages.
> Improve IBM provision script to support RHEL

- scripts/download_logs.sh
- src/assisted_test_infra/test_infra/helper_classes/hypershift.py
- src/tests/test_kube_api.py
[MGMT-9691](https://issues.redhat.com/browse/MGMT-9691): CAPI e2e test is failing due to hypershift control plane operator image mismatch
[MGMT-9213](https://issues.redhat.com/browse/MGMT-9213): Add test_prepare_late_binding_kube_api_ipv4_highly_available to test_kube_api
This can be used by capi test for setting up the env
Save hypershift logs to file
> MGMT-9691: Allow overriding hypershift control plane operator image

- Makefile
- src/consts/consts.py
- src/service_client/client_validator.py
- src/tests/conftest.py
Validating that the client version exists on the assisted-service deployment is equal to the version that is used by out tests (installed in assisted-test-infra image)
Failure warning will be similar to:
```bash
2022-03-14 21:17:01,194 WARNING    - 139723800326400 - Mismatch client versions found! Version on assisted-service-54764b758b-78v9v=v2.1.0-132-g8c54328 != installed_version=v2.1.0-163-gfade32b
```
Note: It looks like that we sometimes have mismatch versions (test-infra client is always more updated than the client on the service deployment) on existing environments
/cc @osherdp
> NO-ISSUE - Add python client version validation before running test suite

- src/assisted_test_infra/test_infra/utils/env_var.py
- src/tests/global_variables/default_variables.py
```
...
2022-03-30 21:36:32,300  root DEBUG      - 139625652396288 - DefaultVariables - Trigger set vip_dhcp_allocation to False, Condition: ('masters_count', 1)     (/assisted-test-infra/src/triggers/env_trigger.py:36)
...
2022-03-30 21:41:53,580  root INFO       - 139625652396288 - Handling ipv6_required_configurations trigger     (/assisted-test-infra/src/triggers/env_trigger.py:78)
ImportError while loading conftest '/assisted-test-infra/src/tests/conftest.py'.
src/tests/conftest.py:9: in <module>
from service_client.client_validator import verify_client_version
src/service_client/client_validator.py:10: in <module>
global_variables = DefaultVariables()
src/tests/global_variables/default_variables.py:32: in __post_init__
Trigger.trigger_configurations([self], get_default_triggers()) …
```
> MGMT-9822 - Fix test-infra test failure when trigger is applied twice to the same variable

- Dockerfile.assisted-test-infra
Looks like Hashcorp rpm repo isn't stable we are getting
Removing ansible from the image since we use dev-scripts image for ansible Hashicorp Stable.
Partial backport of https://github.com/openshift/assisted-test-infra/pull/1558
/cc @osherdp @michaellevy101
> MGMT-9770: Fix issue with Hashicorp RPM during test-infra image build

- create_full_environment.sh
- scripts/pull_dockerfile_images.sh
Add `best-effort script` for pulling all the images that exists in test-infra and assisted-service Dockerfiles (prevent CI jobs to fail due to networking issue)
/cc @adriengentil
> MGMT-9852 - Fix image build failed during CI job

- src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
- src/assisted_test_infra/test_infra/helper_classes/config/nodes_config.py
- src/tests/base_kubeapi_test.py
- src/tests/global_variables/env_variables_defaults.py
This should allow users to get route for cluster ingress configured to one of the workers
(users can pass CLUSTER_NAME and CLUSTER_BASE_DOMAIN)
This is useful for late binding tests that don't use Baremetal platform (e.g. None, HyperShift)
> MGMT-9213: add ingress_dns option to terraform_controller

- Makefile
Allow git fetch to update the head which corresponds to the given PULL_NUMBER. Adding the `--update-head-ok` flag disables the check.
/cc @osherdp
> NO-ISSUE - Fix fetching pull-request when running `bring_assisted_service` twice

- terraform_files/baremetal/terraform.tfvars.json
- terraform_files/baremetal_infra_env/terraform.tfvars.json
- terraform_files/none/terraform.tfvars.json
192.168.122.0/24 is the default network that libvirt creates to spawn
VMs in it... except when the machine is already on this network
(e.g.: nested virtualization).
Use the unix socket instead because skipper is configured to mount it
from the host.
> NO-ISSUE: Use unix socket in libvirt_uri

- Dockerfile.assisted-test-infra
Use centos stream 9 in infra test Dockerfile, it has the benefits to
bring an updated version of dracut that stop polluting the logs when it
tries to build the initramfs from inside a container.
> MGMT-9909: Use centos stream 9 in Dockerfile

- Dockerfile.assisted-test-infra
Reverts openshift/assisted-test-infra#1603
Using stream9 somehow caused docker/podman to fail during image build.
```
STEP 2: FROM quay.io/centos/centos:stream9
STEP 3: RUN dnf -y install --enablerepo=crb   make   gcc   unzip   wget   curl-minimal   git   podman   httpd-tools   jq   nss_wrapper   python3   python3-devel   libvirt-client   libvirt-devel   libguestfs-tools   libxslt    && dnf clean all
CentOS Stream 9 - BaseOS                        0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'baseos':
- Curl error (6): Couldn't resolve host name for https://mirrors.centos.org/metalink?repo=centos-baseos-9-stream&arch=x86_64&protocol=https,http [getaddrinfo() thread failed to start]
```
/cc @osherdp
> Revert "MGMT-9909: Use centos stream 9 in Dockerfile"

- Makefile
Back in https://github.com/openshift/assisted-test-infra/pull/1442, we've had changed our makefile targets to remove some of
the redundancy. Most important one to handle is the ``create_full_environment`` -> ``setup`` change, because ``create_full_environment`` is heavily referenced in CI.
This PR introduce ``setup`` target so that we can use it in cross-branches places, e.g. assisted-baremetal-setup step.
> Handle forward-compatibility with 'setup' target

- src/assisted_test_infra/download_logs/resources/man_sosreport.sh
In addition to bootkube, kubelet and crio, the release-image service is the first one to start by pulling the relevant OCP image.
This is important to gather especially on IPv6 tests (where IPv6 connectivity depends on proxy or an internal registry and might not work properly).
/cc @eliorerz @eranco74 
/hold
> Gather release-image.service log

- Makefile
We have the following scenario:
- A commit is pushed to master that updates the 'deploy/' directory (e.g., RBAC) as well as updates code that relies on those changes.
- A PR is submitted that isn't rebased on the above change
The PR won't pass tests because:
- When building the service image, the repo is rebased and therefore includes the code changes
- Assisted-test-infra doesn't rebase and therefore the 'deploy/' changes won't be applied
- The test is using rebased code without rebased deploy, and therefore the service will fail
/cc @osherdp
> MGMT-9840 - assisted-test-infra doesn't rebase assisted-service in PRs

- Makefile
Reverts openshift/assisted-test-infra#1611
Seems like it doesn't work:
```
From https://github.com/openshift/assisted-service
* [new ref]           refs/pull/3674/head -> assisted-service-pr-3674
Switched to branch 'assisted-service-pr-3674'
git rebase origin/master
fatal: invalid upstream 'origin/master'
make[1]: Leaving directory '/home/assisted'
make[1]: *** [Makefile:282: bring_assisted_service] Error 128
```
Taken from [this job](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-service/3674/pull-ci-openshift-assisted-service-master-e2e-metal-assisted-onprem/1516019380054396928)
/cc @eliorerz
> Revert "MGMT-9840 - assisted-test-infra doesn't rebase assisted-service in PRs"

- src/service_client/assisted_service_api.py
For user managed networking API VIP may not be set, so api_vip may not be set in cluster info.
This should fix failing `download_logs` test in https://testgrid.k8s.io/redhat-assisted-installer#periodic-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-none-periodic
> assisted_service_api: get_api_vip should work when API VIP is not set

- src/assisted_test_infra/test_infra/helper_classes/cluster.py
To support a scenario where disk encryption turned on while not set on the node's BIOS, and for other cases, added a method to set  disk_encryption params
Corresponding e2e test: https://gitlab.cee.redhat.com/ocp-edge-qe/kni-assisted-installer-auto/-/merge_requests/763/diffs
> Adding a cluster method to set encryption params

- src/service_client/assisted_service_api.py
If user_managed_networking is not set in cluster info it should default to False
This should fix failing download_logs test in testgrid.k8s.io/redhat-assisted-installer#periodic-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-none-periodic, follow-up for #1619
> NO-ISSUE: get_api_vip: allow unset user_managed_networking

- requirements.txt
- src/service_client/assisted_service_api.py
This ensures "cluster_events" test name is static, so that test name would be persistent across runs.
> NO-ISSUE: Remove cluster ID suffix from cluster_event junit tests

- Makefile
- scripts/deploy_assisted_service.sh
For some targets, we see those kind of errors:
```
make[1]: Entering directory
'/mnt/nvme/assisted-test-infra/assisted-service'
/bin/sh: /mnt/nvme/assisted-test-infra/data/default_must_gather_versions.json: No such file or directory
cat: /mnt/nvme/assisted-test-infra/data/default_hw_requirements.json: No such file or directory
/bin/sh: /mnt/nvme/assisted-test-infra/data/default_release_images.json: No such file or directory
/bin/sh: /mnt/nvme/assisted-test-infra/data/default_os_images.json: No such file or directory
```
It turns out that assisted-service uses ``MAKEFILE_LIST`` in order to determine the relevant Makefile root-dir, taking into account cases like ``make -f <file>`` and ``include`` statements in makefiles. Outcome of that actually makes it take the path of assisted-test-infra …
> Fix errors when test-infra tries to access data/

- Makefile
- scripts/bring_assisted_service.sh
- scripts/install_environment.sh
On assisted-service, when opening a new PR, on some cases (e.g. change on  the `deploy/` directory) the test is using rebased code without rebased all the service code, and therefore the service will fail.
This PR moves the `bring_assisted_service` target code from Makefile to a new bsah script and rebase assisted-service with `PULL_BASE_REF` after checking out the PR branch
> MGMT-9840 - Move bring_assisted_service Makefile target to bash script

- scripts/bring_assisted_service.sh
Some git commands require user/email to be set, use a dummy global
user/email for CI if one is not already configured
This should fix CI failures such as https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-service/3705/pull-ci-openshift-assisted-service-master-e2e-metal-assisted/1519244251358040064
> NO-ISSUE: Set global git user & email address when running in CI

- Makefile
Use `ocm-2.5` tag instead of `latest` for `INDEX_IMAGE`, similar change were made for 2.4:
https://github.com/openshift/assisted-test-infra/pull/1602/files
> [release-ocm-2.5] NO-ISSUE: Change catalog image to target ocm-2.5

- src/assisted_test_infra/test_infra/helper_classes/cluster.py
- src/assisted_test_infra/test_infra/utils/utils.py
- src/assisted_test_infra/test_infra/utils/waiting.py
Sometimes a host has issues and blocks the installation, but this information is not logged
DNS errors, for instance, prevent the cluster from becoming ready
> Log hosts' statuses while waiting for the cluster status update

- src/assisted_test_infra/resources/bootstrap_in_place/install-config.yaml
In recent versions of OCP `OVNKubernetes` replaced `OpenShiftSDN` as the
default network type for Single Node clusters (currently just in
Assisted Installer's default configuration, in the future it would be
the default for the regular installer / OCP documentation). Later SNO
OpenShiftSDN would be completely forbidden.
We want our BIP flow in this repo to also use OVNKubernetes so we'll
be testing the default network type customers are likely to use in the
future and not the older default OpenShiftSDN.
> MGMT-9179 - Single node bootstrap-in-place flow should use OVNKubernetes

- scripts/install_environment.sh
On Rocky (and some RHEL releases) we used to need to install a downgraded libvirt version, because of a malformed version which is the latest available in the relevant registries. Seems like they've updated the registries, so we no longer need to do that.
> revert libvirt downgrade on Rocky Linux

- scripts/install_environment.sh
On Rocky (and some RHEL releases) we used to need to install a downgraded libvirt version, because of a malformed version which is the latest available in the relevant registries. Seems like they've updated the registries, so we no longer need to do that.
Backports #1660
> [release-ocm-2.4] revert libvirt downgrade on Rocky Linux

- Makefile
- create_full_environment.sh
Seems like since openshift/assisted-test-infra#1595 we no longer trying to pull the assisted-service base image in assisted-test-infra Dockerfile. This is true anytime someone does ``make image_build``
without doing ``make setup`` before.
To make it more convenient, I moved this part to the former target which either way seems like the right place for it.
> Always pulling referenced service image

- discovery-infra/tests/test_kube_api.py
Use `infraenv_config` fixture instead of `infraenv_configuration` as it
was not backported with
https://github.com/openshift/assisted-test-infra/pull/1389
> [release-ocm-2.4] NO-ISSUE: Fix late binding job

- scripts/setup_capi_env.sh
- src/assisted_test_infra/test_infra/helper_classes/hypershift.py
- src/assisted_test_infra/test_infra/helper_classes/kube_helpers/secret.py
- src/tests/test_kube_api.py
NO-ISSUE: Fixing capi test by adding label worker to minikube
In 4.11 ovn is a default network for hypershift cluster and it requires
worker label to run
NO-ISSUE: small improvements to case deploy scripts to cleanup
hypershift image locally before pulling
> NO-ISSUE: Fixing capi test by adding label worker to minikube

- src/assisted_test_infra/test_infra/helper_classes/hypershift.py
This is required since recently hypershift is installing ocp 4.11 which
uses OVNKubernetes, this seems to cause a delay when starting the
control plane pods
> NO-ISSUE: added 20 minutes WAIT_FOR_HYPERSHIFT_CONTROL_PLANE_TIMEOUT

- src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py
- src/assisted_test_infra/test_infra/utils/utils.py
- src/consts/resources.py
Reverts openshift/assisted-test-infra#1681
Seems to not set DNS entries correctly in QE's tests. Reverting until we can figure out what exactly happened
/cc @michaellevy101 @lalon4
> Revert "Update etc hosts file append a mapping to the api and ingress vips"

- src/assisted_test_infra/test_infra/utils/oc_utils.py
Apparently sometimes resources don't have a "status", this is probably
rare and only happens for a brief period after a resource is created.
Anyway, we should handle it more gracefully.
See:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-test-infra/1653/pull-ci-openshift-assisted-test-infra-master-e2e-metal-single-node-live-iso/1537022236752351232
```
[0;34m2022-06-15 11:12:20,434  root DEBUG      - 140053192167680 - List of operators seems to still be empty... Retrying 	(/home/sno/src/tests/test_bootstrap_in_place.py:210)[0m
[1;31m2022-06-15 11:12:40,467  root ERROR      - 140053192167680 - An unexpected error has occurred while waiting for installation to complete 	(/home/sno/src/tests/test_bootstrap_in_place.py:273)
Traceback (most recent call …
```
> NO-ISSUE: Don't assume all resources have a status

- src/assisted_test_infra/test_infra/helper_classes/day2_cluster.py
- terraform_files/baremetal/main.tf
Starting OCP 4.11 there is a requirement to support day-2 installation
of worker nodes on SNO clusters as opposed to just multi-node clusters.
We want Assisted REST to support it as well, so we want to run periodic
tests to make sure it works.
The existing Day2Cluster test flow first installs OpenShift using the
REST assisted-installer and then attempts to add worker nodes to the
resulting cluster. It worked fine in multi-node clusters but had some
bugs for single-node clusters (NUM_MASTERS=1 and NUM_WORKERS=0) which
this commit aims to solve.
The first bug is the missing `api-int.` DNS entry in the terraform
libvirt dnsmasq configuration. Only the `api.` entry was present. Since
multi-node clusters use the baremetal platform rather than the "none"
platform, this wasn't a problem for them …
> MGMT-9378 - Bug fixes to make day-2 Assisted REST flow support SNO

- src/tests/test_kube_api.py
This should allow this branch to pass this release image to hypershift instead of letting hypershift defaulting to 4.11
> MGMT-10717: set OCP-4.10 as the default ASSISTED_OPENSHIFT_INSTALL_RELEASE_IMAGE

- src/tests/test_kube_api.py
NO-ISSUE: it takes time to hypershift to create namespace and we should add secret only after it was created
> NO-ISSUE: it takes time to hypershift to create namespace and we should add secret only after it was created

- src/assisted_test_infra/test_infra/controllers/containerized_controller.py
- src/assisted_test_infra/test_infra/controllers/ipxe_controller/ipxe_controller.py
- src/assisted_test_infra/test_infra/controllers/proxy_controller/proxy_controller.py
- src/assisted_test_infra/test_infra/controllers/tang_controller/tang_controller.py
- src/tests/base_test.py
Join base logic for test-infra containerized controllers
After adding tang support to test-infra we have 3 duplicated code/behaviors on the containerized controller: ipxe_controller, tang_controller, and on proxy_controller. This PR move the base controller behavior under new base class.
/cc @osherdp
> MGMT-10830 - Create base class for test-infra containerized controllers

- src/tests/base_test.py
QE CI machines having hundreds of dnsmasq files. This PR clean this file as part of nodes teardown
> NO-ISSUE: Clean dnsmasq files

- GUIDE.md
- README.md
- scripts/create_full_environment.sh
Users are not recommended to run the code in this repo on their local
machine, as it makes some surprising opinionated configuration changes
that users might not expect (installing packages, configuring libvirt,
etc). We should give a clear warning about that in the README.
Also since we don't support Fedora, our `create_full_environment.sh`
should be modified to reflect that and block users trying to install
on Fedora. If we detect an OS we don't support, on top of saying we
don't support it, we give the same warning as in the README.
> NO-ISSUE: Remove Fedora support, add warning about this repo

- src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
Since we moved to 100GB disk limitation, we get a different output for
the used disk. This leads to the following error:
```
E           RuntimeError: command: qemu-img create -f qcow2
/home/test/assisted-test-infra/storage_pool/test-infra-cluster-742fe912/test-infra-cluster-742fe912-master-2-disk-
0 93.1 exited with an error: qemu-img: Invalid image size specified. You
may use k, M, G, T, P or E suffixes for
E           qemu-img: kilobytes, megabytes, gigabytes, terabytes,
petabytes and exabytes. code: 1
```
This changes how we get the existing disk size by using ``--output
json`` that returns a nicer format for being able to parse the disk
size. ``qemu-img create`` command is capable of getting disk sizes
either in bytes or with quantifiers like G/M/K/etc. so we should stay
compatible …
> Fix disk size calculation when formatting disks.

- src/assisted_test_infra/test_infra/helper_classes/cluster.py
- src/consts/consts.py
@eliorerz @lalon4
Function wait_for_specific_host_status , will have a new parameter (timeout) 
new Parameter in host events : DISCONNECTED
change is needed to support kni test , which validate that cluster installation is timeout after 3 min when a host which already reached the state "write to disk" is now disconnected for 3 min+
> additional parameter(timeout) for method wait_for_specific_host_status  and new host event parameter DISCONNECTED

- src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
Since recently one of our e2e test is failing (test_unique_vip_hostname). 
The test create cluster and nodes, and than delete created cluster and nodes, and create another set of cluster and nodes. Issue is that lately it is failing to create the second set of nodes - tf apply get an error: 
"Storage pool not found: no storage pool with matching name".
Turns out that whenever we clear the nodes we use libvirt cleanup (instead of tf) so tf state assume disks are already exists, while in reality they were cleaned by delete all virsh resources.
This PR clean tf state file to avoid this failure.
> Delete tfstate file during destroy nodes

- Makefile
`_deploy_nodes` is gone for a while now, this PR removes all the leftovers of the `_deploy nodes` depend on targets
/cc @osherdp
> NO-ISSUE - Remove `_deploy_nodes` deprecated targets

- GUIDE.md
- README.md
- scripts/create_full_environment.sh
This allows AlmaLinux as a backup plan so that we'll be able to use it if Rocky fails us as a CI candidate.
I tested full installation with AlmaLinux 8 via Equinix, it passed successfully.
> Allow usage of AlmaLinux OS in assisted-test-infra

- scripts/install_environment.sh
This is a workaround for MGMT-8707, until we get the fixed RPMs to land in CentOS / RHEL 8.x
> MGMT-11119: CI workaround: Get swtpm from source 

- scripts/pull_dockerfile_images.sh
assisted-service has now a Dockerfile for building it's content for OCP
payload, and it references images that require authentication against
registry.ci (e.g. ``registry.ci.openshift.org/ocp/4.11:cli``).
This change omits those kind of files so that we won't pull for nothing.
> Do not pull images from Dockerfile.*.ocp files

- src/assisted_test_infra/download_logs/__main__.py
- src/assisted_test_infra/download_logs/download_logs.py
- src/tests/base_test.py
Allow the user to skip on the download logs part using KeyboardInterrupt signal.
At the current situation, the test is to trying to download the logs 3 times with 300 seconds sleep between them. Pressing sending KeyboardInterrupt signal is not always working (on sleep) and the test is exit without a proper cleanup.
Also removing the unused `pull_secret` field from `download_logs` function.
/cc @osherdp
> NO-ISSUE - Allow KeyboardInterrupt during download logs

- src/assisted_test_infra/test_infra/controllers/node_controllers/node_controller.py
- src/assisted_test_infra/test_infra/helper_classes/cluster.py
- src/assisted_test_infra/test_infra/helper_classes/cluster_host.py
- src/assisted_test_infra/test_infra/helper_classes/config/base_entity_config.py
- src/assisted_test_infra/test_infra/helper_classes/config/base_infra_env_config.py
- src/assisted_test_infra/test_infra/helper_classes/config/cluster_config.py
- src/assisted_test_infra/test_infra/helper_classes/day2_cluster.py
- src/assisted_test_infra/test_infra/helper_classes/entity.py
- src/assisted_test_infra/test_infra/helper_classes/infra_env.py
- src/assisted_test_infra/test_infra/helper_classes/kube_helpers/infraenv.py
- src/assisted_test_infra/test_infra/helper_classes/nodes.py
- src/assisted_test_infra/test_infra/utils/utils.py
- src/service_client/assisted_service_api.py
- src/tests/base_kubeapi_test.py
- src/tests/base_test.py
- src/tests/config/global_configs.py
- src/tests/test_day2.py
- src/tests/test_kube_api.py
- Do not prepare nodes before infraenv is being created.
- Create infraenv and get iso_download_path prepering the nodes.
- Remove the const iso_download_path from cluster configuration.
/cc @lalon4 @tsorya @osherdp
> MGMT-11109 - Prepare nodes only after having an infra_env

- scripts/install_environment.sh
When doing ``make setup`` twice, it fails on the ``swtpm`` dir already existing:
```
Install swtpm v0.7.1 from source
fatal: destination path 'swtpm' already exists and is not an empty
directory.
make: *** [Makefile:128: setup] Error 128
```
In addition, it leaves unstaged files in the repo that are not ignored by git.
This change will use a temporary dir from ``/tmp``, and will cleanup afterwards with a bash trap.
> Fix swtpm installation not being idempotent

- Dockerfile.assisted-test-infra
Install govc from the container registry instead of relying on github.
> MGMT-11449: govc installation from GitHub gets rate-limiter failures

- src/assisted_test_infra/test_infra/utils/utils.py
As detailed in Jira, the lack of a default OCP version fails this flow.
> MGMT-11491: kubeAPI flow should work with no default OCP version

- .dockerignore
- src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py
- src/assisted_test_infra/test_infra/helper_classes/kube_helpers/agent_cluster_install.py
- src/assisted_test_infra/test_infra/tools/terraform_utils.py
- src/assisted_test_infra/test_infra/utils/kubeapi_utils.py
- src/consts/consts.py
- src/tests/base_kubeapi_test.py
- src/tests/test_kube_api.py
In order to support vSphere platform on KubeAPI test introduced the following changes:
* Added 'platform_type' to ACI creation on kube_api_test
* VSphereController: get_ingress_and_api_vips func should return api_vip/ingress_vip params as dhcp is not supported using kube-api.
* Ensured _set_host_name_from_node logic is performed for both ipv4 and ipv6 (as setting the hostname is always required on vSphere).
* Removed unused set_agents_hostnames and set_agent_hostname funcs.
Note: pending on https://github.com/openshift/assisted-service/pull/4219
> MGMT-11415: add platform support to kubeapi test

- src/tests/test_kube_api.py
In case we override the hypershift-operator-image to the latest hypershift image (might happen because the setup_capi.sh script export a similar env) we might end up with a mismatch between the release we are installing and the hypershift control plane operator image
> Set hypershift operator image only when the HYPERSHIFT_OPERATOR_IMAGE env was provided

- .dockerignore
Following to minikube_home folder fix in https://github.com/openshift/release/pull/31365, vsphere-kube-api job should work without adding minikube to .dockerignore file.
> NO-ISSUE: remove minikube from dockerignore

- src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
- src/tests/test_day2.py
Currently we are running the "nodes  cleanup" on every test regardless the nodes status.
Each cluster name is unique so as the terraform configuration folder so there shouldn't be a case where a cluster is created with the same name.
Furthermore, we should not prepare the nodes twice in the same test. If for some reason we want to do it, we can always do it manually, e.g.
```python
...
nodes.prepare_nodes()
...
nodes.destroy_all_nodes()
nodes.prepare_nodes()
...
```
/cc @osherdp
> MGMT-11319 - Remove redundant `destroy_nodes` when preparing nodes

- src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
- src/assisted_test_infra/test_infra/controllers/node_controllers/node_controller.py
- src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
- src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py
- src/assisted_test_infra/test_infra/helper_classes/cluster.py
- src/tests/base_test.py
- src/tests/test_kube_api.py
- terraform_files/baremetal/main.tf
- terraform_files/baremetal_host/main.tf
- terraform_files/baremetal_infra_env/main.tf
- terraform_files/none/main.tf
The job e2e-metal-assisted-day2-single-node currently fails with the following error:
```
2022-07-22 05:43:31,208 - root - INFO - 139970722252608 - Asked hosts to
be in one of the statuses from ['known'] and currently hosts statuses
are [(1, 'eecb5396-0b83-422b-ae31-7418fee62663',
'test-infra-cluster-c717123a-worker-0', 'worker', 'insufficient', "Host
cannot be installed due to following failing validation(s): Couldn't
resolve domain name *.apps.test-infra-cluster-c717123a.redhat.com on the
host. To continue installation, create the necessary DNS entries to
resolve this domain name to your cluster's application ingress IP
address")]
```
assisted-test-infra does not currently create the wildcard DNS for the cluster because the terraform provider did not support that up until now.
Since the …
> MGMT-11337: Define wildcard DNS for ingress DNSes

- Makefile
Prevent skipper to use different container command than the command set on `CONTAINER_COMMAND`.
`get_container_runtime_command` prioritize `podman` and skipper prioritize `docker` as container runtime command.
/cc @osherdp
> NO-ISSUE - Align `CONTAINER_RUNTIME_COMMAND` with `CONTAINER_COMMAND`

- scripts/install_environment.sh
For Nutanix CI workflow we need the ability to connect to `nutanix-lts-dev` environment.
For that matter we need to connect to the environment VPN using openvpn.
/cc @osherdp
> NO-ISSUE - Install openvpn as dependency for nutanix CI

- src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
- src/assisted_test_infra/test_infra/controllers/node_controllers/node_controller.py
- src/assisted_test_infra/test_infra/controllers/node_controllers/nutanix_controller.py
- src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
- src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py
Back in https://github.com/openshift/assisted-test-infra/pull/1797 I accidentally used the wrong non-compatible default value for those functions (we'd like them to behave like previously defined).
> Fix default value for getting vips

- Makefile
- src/triggers/default_triggers.py
After https://github.com/openshift/assisted-service/pull/4158 SNO cluster must be none platform when enabling user-managed-networking 
/cc @osherdp
> MGMT-11852 - Update platform to none on sno installation

- Makefile
- requirements.txt
pytest tests are skipped when parameterized is empty - e.g. `openshift_version` on `test_install`.
This PR force the test to fail when pytest test is skipped
/cc @osherdp
> NO-ISSUE - Prevent tests from being skipped when test parameterized is empty

- src/assisted_test_infra/download_logs/download_logs.py
The download_logs.py didn't collect must-gahter logs in case of
hypershift cluster because it was failing to initalize the Hypershift
helper class
> NO-ISSUE: fix must-gather log collection in case of hypershift cluster

- scripts/install_environment.sh
Currently the `make install` command that installs the _swtpm_ package
and the `chmod` command that sets execution permission for the _libvirt_
cross network traffic hook are missing the `sudo` prefix, so they don't
work when using a non-root user. This patch fixes that.
> NO-ISSUE: Add missing sudo in install_environment.sh

- Makefile
- requirements.txt
Backport of https://github.com/openshift/assisted-test-infra/pull/1824
/cc @osherdp
> [release-ocm-2.6] NO-ISSUE - Prevent tests from being skipped when test parameterized is empty

- scripts/install_environment.sh
The more relevant change in the new version of _skipper_ is a fix to prevent leaking of mount points.
Related: https://github.com/Stratoscale/skipper/pull/155
Related: https://github.com/containers/podman/issues/15671
> NO-ISSUE: Update skipper to 1.34.0

- src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py
Same as Nutanix controller, there is some issue with the `force` flag on `python_terraform`. 
This PR disable the force flag allowing terraform to destroy the allocated resources properly.
```
2022-09-09 20:13:54,154  python_terraform WARNING  - 140588503791424 - 
error: 'Error: Failed to parse command-line flags\n\nflag provided but not defined: -force
For more help on using this command, run: terraform destroy -help' 	(/usr/local/lib/python3.10/site-packages/python_terraform/__init__.py:306)
```
/cc @osherdp
> MGMT-11981: FIx teardown on vsphere nodes

- Dockerfile.assisted-test-infra
- scripts/override_os_images.py
- scripts/override_release_images.py
- scripts/set_boot_order.by
- src/assisted_test_infra/test_infra/controllers/ipxe_controller/server/local_ipxe_server.py
- src/update_assisted_service_cm.py
Used in a self built image located at https://quay.io/repository/eerez/python-builder
We will do the asme for 3.11 that supposed to be released on October (3.11.0rc1 is already available for installation on `python-builder` repository)
/cc @osherdp
> NO-ISSUE - Upgrade to python3.10

- Dockerfile.assisted-test-infra
Latest test-infra image does not contain the ``virt-format`` command, as shown in QE tests:
```
def run_command(command, shell=False, raise_errors=True, env=None, cwd=None, run_in_background=False):
command = command if shell else shlex.split(command)
if run_in_background:
subprocess.Popen(command, shell=shell, env=env, cwd=cwd, stderr=subprocess.STDOUT)
return
process = subprocess.run(
command, shell=shell, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=env, universal_newlines=True, cwd=cwd
)
def _io_buffer_to_str(buf):
if hasattr(buf, "read"):
buf = buf.read().decode()
return buf
out = _io_buffer_to_str(process.stdout).strip()
err = _io_buffer_to_str(process.stderr).strip()
if raise_errors and process.returncode != 0:
>           raise RuntimeError(f"command: {command} exited with …
```
> fix virt-format command missing

- src/assisted_test_infra/download_logs/download_logs.py
The parameter and the function had the same name
> NO-ISSUE: fix describe_cluster_operators

- src/assisted_test_infra/test_infra/helper_classes/kube_helpers/agent_cluster_install.py
Ensures that the full path for kubeconfig file exists on download_kubeconfig of AgentClusterInstall.
> NO-ISSUE: ensure dest folder exists in download_kubeconfig

- src/tests/base_kubeapi_test.py
- src/tests/test_kube_api.py
On BaseKubeAPI test, download kubeconfig using secret ref in ACI.
> NO-ISSUE: download kubeconfig in BaseKubeAPI test

- src/update_assisted_service_cm.py
This patch changes the e2e tests so that the upgrade agent feature is explicitly enabled.
Related: https://issues.redhat.com/browse/MGMT-11706
> MGMT-11706: Run e2e tests with the upgrade agent feature enabled

- Makefile
On some cases the load balancer failed to start due to the following error
```
nginx: [emerg] bind() to 192.168.127.1:6443 failed (99: Cannot assign requested address)
```
This PR remove the conf file before each time we start it, also fixed the conf file path on the `stop_load_balancer` Makefile target 
See right path on https://github.com/openshift/assisted-test-infra/blob/master/terraform_files/none/main.tf#L170
/cc @osherdp @tsorya 
FYI @lalon4
> MGMT-12096: Fix errors accessing load-balancer http conf file

- src/assisted_test_infra/download_logs/download_logs.py
https://github.com/openshift/oc/pull/1178 introduced a breaking change
where the destination dir for the must-gather command must not contain a
colon.
This leads to our CI gather step to show this error:
```
2022-09-21 09:56:29,314  download_logs WARNING    - 140125667993408 - Failed to run must gather: command: oc --insecure-skip-tls-verify --kubeconfig=/tmp/artifacts/2022-09-21_09:15:17_e270331f-a66d-493d-9e01-fa72c71bb46c/kubeconfig-noingress adm must-gather --dest-dir /tmp/artifacts/2022-09-21_09:15:17_e270331f-a66d-493d-9e01-fa72c71bb46c/must-gather-dir > /tmp/artifacts/2022-09-21_09:15:17_e270331f-a66d-493d-9e01-fa72c71bb46c/must-gather-dir/must-gather.log exited with an error: error: --dest-dir may not contain special characters such as colon(:) code: 1 …
```
> NO-ISSUE: Change log folder time format to use dashes rather than colons

- scripts/install_environment.sh
In order to prevent potential races when multiple threads or processes try to modify iptables rules by using libvirt hook, we are introducing use of a temporary file as well as the lock. This should ensure that there are no concurrent attempts to -save and -restore the firewall configuration.
Co-authored-by: jhernand@redhat.com
Closes: [MGMT-11968](https://issues.redhat.com//browse/MGMT-11968)
> MGMT-11968: Use lock and tmp file when altering iptables rules

- terraform_files/nutanix-ci-machine/main.tf
Set CPU passthrough on Nutanix CI machine so that minikube could create a nested VM
> nutanix machine: enable nested virt

- packer_files/nutanix_centos_template/centos-config/ks.cfg
When install is finished, CDROM needs to be ejected, so that machine would boot from disk. Unlike vSphere Packer plugin it can't set boot order
> nutanix packer: eject cdrom

- src/assisted_test_infra/test_infra/controllers/node_controllers/nutanix_controller.py
- src/assisted_test_infra/test_infra/helper_classes/config/base_nutanix_config.py
In CI we might want to allocate VIPs and create DNS records using existing IPI steps. Nutanix controller should not use DHCP to allocate VIPs if these are already set using environment variables.
Being tested in https://github.com/openshift/release/pull/31726
> nutanix: don't allocation VIPs if DHCP allocation is not set

- Makefile
- src/tests/base_kubeapi_test.py
- src/tests/test_kube_api.py
Two issues:
1/
Since https://github.com/openshift/assisted-test-infra/pull/1852 the
loadbalancer configuration is cleaned up before starting it.
This change does not cleanup the configuration when `TEST_TEARDOWN` is
set to `false`.
It should fix the late binding job, that configures the nginx server
before running the tests.
2/
Since https://github.com/openshift/assisted-test-infra/pull/1849/files#diff-21e688d6eb3b87727264f6934118765f035f5bf7504dff17b3ab9fb388f4d054L416
The kubeconfig used for the hub cluster is replaced by the kubeconfig that points
to the sno cluster which leads to fail the conformance test as the DNS for this cluster
is not configured.
I made the parameter optional, as I guess the kubeconfig from the `AgentClusterInstall`
is not used in this case.
> NO-ISSUE: Fix late-binding job

- requirements.txt
This is required to fix boot order change when Nutanix VM is not yet started. Required for https://github.com/openshift/release/pull/31726
> requirements.txt: bump nutanix-api to 0.0.18

- Dockerfile.assisted-test-infra
> NO-ISSUE: Upgrade Python 3.11 that is now officially available

- terraform_files/vsphere-ci-machine/variables-vsphere.tf
Add more memory to the cluster machines so that periodic conformance tests would have a better chance of passing.
Todo:
> MGMT-11926: bump vsphere machine specs

- src/assisted_test_infra/test_infra/helper_classes/cluster.py
- src/consts/env_defaults.py
- src/tests/global_variables/env_variables_defaults.py
- src/triggers/default_triggers.py
Back on https://issues.redhat.com/browse/MGMT-10840 we changed the default value of vip_dhcp_allocation but left assisted-test-infra untouched causing vip_dhcp_allocation to stay `True` on some tests.
We need to remove vip_dhcp_allocation default from test-infra and allowing the service to set the default by itself.
/cc @osherdp
> MGMT-12381: Remove VIP DHCP allocation defaults from test-infra

- terraform_files/vsphere/main.tf
Seems vSphere throws HTTP 500 when a file is uploaded. `test` folder is unaffected, so lets use that temporarily
> vsphere: upload iso to test folder

- scripts/install_environment.sh
Manual revert of
https://github.com/openshift/assisted-test-infra/pull/1748.
The fixed versions of swtpm packages has landed for RHEL 8.7+8.6 as well as latest Rocky Linux 8 version.
It means we should not have any kind of flaky behavior as we previously had in CI (might still happen locally, but either way disk-encryption is not heavily prioritized for testing and development).
/cc @nmagnezi @eliorerz
> MGMT-8707: Revert swtpm installation from source

- src/assisted_test_infra/test_infra/tools/assets.py
It is possible to try reading a network interface that has been removed
while ``_fill_allocated_ips_and_bridges_by_interface`` traverses the
network interfaces. On those cases we get:
```
def _fill_allocated_ips_and_bridges_by_interface(self):
for interface in netifaces.interfaces():
self._add_allocated_net_bridge(interface)
>           for ifaddresses in
netifaces.ifaddresses(interface).values():
E           ValueError: You must specify a valid interface name.
```
This changes the code to allow getting ``ValueError`` and continueing to
the next interface.
/cc @eliorerz @lalon4
> Fix network interface getting removed intermediately

- scripts/utils.sh
Couldn't find any reference to those functions, and I think it's not longer needed for none-platform tests.
> Remove redundant none-platform code

- Dockerfile.assisted-test-infra
It is redundant ever since https://github.com/openshift/assisted-test-infra/pull/552.
> Remove redundant wget dependency

- Dockerfile.assisted-test-infra
Change the way we're installing the desired Python version. Instead of doing ``make install`` with provided code from the base image, this just uses a base image which has Python installed.
It reduces image size from 2.91GB to 2.54GB, as well as installation times (from 8m17 to 5m46).
> Using the new base python image

- src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
- src/tests/test_bootstrap_in_place.py
This allowing us to update node configurations after the cluster was created but before creating the nodes
e.g.
```python
class TestInstall(BaseTest):
def test_install(self, cluster, controller_configuration):
min_host_ocp_requirements = cluster.get_preflight_requirements()
controller_configuration.master_vcpu = min_host_ocp_requirements.ocp.master.quantitative.cpu_cores
cluster.prepare_for_installation()
cluster.start_install_and_wait_for_installed()
```
/cc @osherdp
> MGMT-12670: Set terraform parameters only on `create_nodes` and `destroy_nodes`

- src/assisted_test_infra/test_infra/controllers/node_controllers/node.py
Current nody.py get_disks function returns none instead of disks Fixed and added return.
> Add return to get_disks

- scripts/deploy_assisted_service.sh
For assisted test of OKD  we need to run AI w/ RELEASE_IMAGES set to current release and
custom OS_IMAGES. deploy_assisted_service should not override OS_IMAGES
if its already set.
Ref: https://github.com/openshift/release/pull/34404
> deploy_assisted: don't overwrite OS_IMAGES

- scripts/download_logs.sh
Currently getting:
```
15:53:17  ./scripts/download_logs.sh: line 100: unexpected EOF while
looking for matching `"'
15:53:17  make: *** [Makefile:293: download_cluster_logs] Error 2
```
E.g.:
http://assisted-jenkins.usersys.redhat.com/job/download_logs/44906/console
/cc @eranco74
> fix download-logs.sh script syntax

- src/consts/consts.py
https://github.com/openshift/assisted-service/blob/c0b3526c379e81df5925fd0f2d61e7559e9a41a7/internal/host/common.go#L39
> MGMT-12881: fix REBOOT_TIMEOUT message string to match the message in assisted-service

- src/assisted_test_infra/test_infra/helper_classes/nodes.py
When the machines started again the cached info must be refreshed.
In case machines state changed like stop/reboot cashed info may hide bugs in the node controllers or fail tests.
This patch is continuation of https://github.com/openshift/assisted-test-infra/pull/1947 Due to some mismach i created new patch.
> Current iptables fixture tears down nodes in order modify iptables.

- Dockerfile.assisted-test-infra
- ansible_files/ansible.cfg
- ansible_files/equinix_generic_destroy_infra_playbook.yml
- ansible_files/equinix_heterogeneous_create_infra_playbook.yml
- ansible_files/roles/common/setup_ipip_tunnel/tasks/main.yml
- ansible_files/roles/equinix/export_primary_device_connection_details/defaults/main.yml
- ansible_files/roles/equinix/export_primary_device_connection_details/tasks/main.yml
- ansible_files/roles/equinix/export_primary_device_connection_details/templates/ci-machine-config.sh.j2
- ansible_files/roles/equinix/generic_destroy_infra/tasks/main.yml
- ansible_files/roles/equinix/heterogeneous_create_infra/defaults/main.yaml
- ansible_files/roles/equinix/heterogeneous_create_infra/tasks/main.yml
- ansible_files/roles/equinix/heterogeneous_create_infra/templates/terraform.tfvars.j2
- ansible_files/vars/ci.yml
- ansible_files/vars/ci_equinix_infrastucture.yml
- ansible_files/vars/standalone_equinix_sample.yml
- requirements.txt
- terraform_files/equinix-ci-machine/main.tf
- terraform_files/equinix-ci-machine/output.tf
- terraform_files/equinix-ci-machine/variables_equinix.tf
This PR contains:
- a terraform module able to provision multiple devices from equinix metal
- Two ansible playbooks: 
-  create heterogeneous clusters, which is responsible to provision the devices from equinix using the terraform module above, and soon, configure both of the machines (ipip tunnel and libvirt)
- destroy the machines created by the first playbook
Here is CI definition if you want to check how the playbooks are used: https://github.com/openshift/release/tree/master/ci-operator/step-registry/assisted/equinix
> MGMT-12439: Deploy heterogeneous infrastructure

- skipper.yaml
When running hypervisor with rhel8.6 and containers with centos9, iptables rules with --dport value not submitted on hypervisor and all tcp traffic blocked. reproduced with skipper code on multiple setups. the rule set with port and sources and targets. on hpervisor side the --dport was not submitted but the NFT table updated with the dport.
Example when reproduced:
-A FORWARD -s 192.168.128.11/32 -p tcp -j DROP
Here we dont have the dport assigned and the rule blocks all tcp
versions we hit on the issue:
container centos 9 - >iptables v1.8.8 (nf_tables)
hypervisor (rhel 8.6) ->  iptables v1.8.4 (nf_tables)
The fix mount containers to the hypervisor iptables binary centos iptables version and rhel8.6 with same version and it works. -A FORWARD -s 192.168.128.11/32 -p tcp -m tcp --dport 443 …
> Iptables rules added without destination port due to iptables versions

- Dockerfile.assisted-test-infra
git was updated in centos 9 stream repository and now checks if the
owner of the files on the filesystem match the current user.
This change disables the check because Prow runs jobs with a random
user.
> MGMT-13038: Git fails to trust git repository because of mismatch with files

- ansible_files/equinix_heterogeneous_create_infra_playbook.yml
- ansible_files/roles/common/setup_libvirtd/handlers/main.yml
- ansible_files/roles/common/setup_libvirtd/tasks/main.yml
- ansible_files/roles/common/setup_ssh_key_pair/defaults/main.yml
- ansible_files/roles/common/setup_ssh_key_pair/tasks/main.yml
- ansible_files/roles/common/setup_ssh_key_pair/templates/config.j2
Install libvirtd and configure a throwable SSH key pair between both of
the machines, so the primary machine can control libvirtd on the ARM 
machine through SSH, e.g.:
```
virsh -c "qemu+ssh://secondary-host/system"
```
> MGMT-12441: Install libvirtd on the ARM machine

- src/assisted_test_infra/test_infra/utils/utils.py
Test failed when trying to remove proxy container squid Error message refers to running or paused containers cannot be removed The code stop && rm the podman but it might be that stop code not really blocked and waiting before we call remove.
Added sleep between stop to remove.
> Cannot remove container as it is running issue

- src/tests/test_bootstrap_in_place.py
In
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-test-infra/1883/pull-ci-openshift-assisted-test-infra-master-e2e-metal-single-node-live-iso/1607833190590844928 we get to a timeout for waiting for the installation, even though in the post must-gather logs it seems like installation finished successfully.
This increases the timeout by 10 minutes to make the job more stable.
> Extending SNO installation timeout to 70 mins

- terraform_files/baremetal/main.tf
- terraform_files/baremetal_host/main.tf
- terraform_files/baremetal_infra_env/main.tf
- terraform_files/none/main.tf
Release notes: https://github.com/dmacvicar/terraform-provider-libvirt/releases/tag/v0.7.1
> Bump terraform-provider-libvirt to v0.7.1

- scripts/hub-cluster/minikube.sh
In local environments, we sometimes hit the rate-limitter of docker hub when doing a lot of ``make destroy run``. This is because the registry addon of minikube relies on images that are not in ghcr.io but from docker-hub.
This change uses images from quay.io for the registry, as a simple fix.
> Setting minikube registry addon to use images from quay.io

- terraform_files/baremetal/main.tf
- terraform_files/baremetal_host/main.tf
- terraform_files/baremetal_infra_env/main.tf
- terraform_files/none/main.tf
Reverts openshift/assisted-test-infra#1883
The new provider introduced a regression where DNS gets enabled by default on networks which causes DNS issues on some CI jobs, reverting until this is fixed upstream
> Revert "Bump terraform-provider-libvirt to v0.7.1"

- scripts/download_logs.sh
For some reason, the names are not matching the actual container names used. It should be prefixed with ``assisted-installer`` (podman's pod name) and continue with the names ``db``, ``ui``, ``image-service`` and ``service``.
See:
https://github.com/openshift/assisted-service/blob/a1c6df56391b517f4bbf167ba841ffe040950ebd/deploy/podman/pod.yml#L8
> Fix podman container names on gather

- Dockerfile.assisted-test-infra
Currently, the sdist version fails to install because of an update of
setuptools: https://github.com/pypa/setuptools/issues/3772.
The wheel is not affected by this change.
Depending on the outcome of the setuptools ticket, we may have to
follow-up to provide a valid version scheme for the sdist package (or
just remove it?).
> MGMT-13341: Use assisted service client wheel

- scripts/deploy_assisted_service.sh
- scripts/override_os_images.py
- scripts/override_release_images.py
- src/assisted_test_infra/test_infra/utils/release_image_utils.py
- src/assisted_test_infra/test_infra/utils/utils.py
- src/service_client/logger.py
Currently we load all images from ``data/default_os_images.json`` in prow CI. It makes for a very long setup time for the image-service.
At least some of those images are not relevant to our CI at all, because we don't have a way to get the matching HW - namely the images for zSystems and PowerPC.
In addition, we don't need to load images for 4.8, 4.9, 4.10, etc. for most of the jobs as we rather use 4.11/4.12. So it should be beneficial to only load the relevant image based on existence of ``OPENSHIFT_VERSION`` or ``OPENSHIFT_INSTALL_RELEASE_IMAGE`` env-vars.
> MGMT-13210: only pull relevant OS images

- src/assisted_test_infra/test_infra/helper_classes/cluster.py
- src/service_client/assisted_service_api.py
- src/tests/base_test.py
We do not call the `/v2/clusters/{cluster_id}/supported-platforms` during the installation and as a result we do not verify that the installed platform do exist in the `supported-platforms` list.
This PR adds 2 calls to that API with that expected results:
- When there are no hosts - platform should be none
- When hosts are exist, validate that the cluster.platform is exists in the supported platforms list.
/cc @osherdp @adriengentil
> MGMT-12477: Validate that cluster platform is exists in `supported_platforms` API call result

- scripts/override_os_images.py
In the case that the user didn't specified ``OPENSHIFT_VERSION`` nor ``OPENSHIFT_INSTALL_RELEASE_IMAGE``, we still try to extract the version of a ``None`` version.
This allows computation to continue so that we won't get the following case (when those two are not defined):
```
++ skipper run ./scripts/override_os_images.py --src
./assisted-service/data/default_os_images.json
[skipper] Using build container: assisted-test-infra:latest
+ OS_IMAGES='Traceback (most recent call last):
File "/home/assisted-test-infra/./scripts/override_os_images.py", line
62, in <module>
main()
File "/home/assisted-test-infra/./scripts/override_os_images.py", line
45, in main
or
extract_version(os.environ.get("OPENSHIFT_INSTALL_RELEASE_IMAGE"))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
```
> MGMT-12996: fix os-override when no OCP version specified

- src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
- src/assisted_test_infra/test_infra/controllers/node_controllers/node_controller.py
- src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
- src/assisted_test_infra/test_infra/helper_classes/base_cluster.py
- src/assisted_test_infra/test_infra/helper_classes/cluster.py
- src/assisted_test_infra/test_infra/helper_classes/day2_cluster.py
- src/assisted_test_infra/test_infra/helper_classes/nodes.py
- src/tests/base_test.py
- src/tests/test_day2.py
Make common code between Day1 `Cluster` and `Day2Cluster` classes available in a new `BaseCluster` class
There are a lot of small hacks due to the fact that day2 cluster re-use the terraform stack of the day1 cluster, these hacks will disappear in a next PR where the day2 cluster will have its own terraform stack.
> MGMT-11111: refactor day2 cluster code

- src/assisted_test_infra/test_infra/helper_classes/cluster.py
- src/tests/global_variables/env_variables_defaults.py
- src/triggers/default_triggers.py
 When running test with NetworkType set as parametrized and `OpenshiftVersion < 4.12, NetworkType` is set to None instead of the desired value 
e.g the following test will result creating cluster with NetowkType=None
```python
@pytest.mark.parametrize("network_type", [consts.NetworkType.OpenShiftSDN])
def test_install(self, cluster, network_type): 
cluster.prepare_for_installation()
cluster.start_install_and_wait_for_installed()
```
/cc @osherdp @adriengentil
> MGMT-13438: Fix NetworkType trigger overrides parametrized values

- Dockerfile.assisted-test-infra
Backport selectively fix_uid.sh script that was introduced in a larger PR: https://github.com/openshift/assisted-test-infra/pull/1949
Should fix vsphere and nutanix jobs depending on it in `release-ocm-2.7`
branch: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-assisted-test-infra-release-ocm-2.7-e2e-vsphere-assisted-kube-api-periodic/1617673768342130688
> [release-ocm-2.7] Backport fix_uid.sh script

- Makefile
`e2e-metal-assisted-ha-kube-api-ipv6`, `e2e-metal-assisted-kube-api-late-binding-single-node`  and `e2e-metal-assisted-kube-api-late-unbinding-single-node` jobs are currently permafailing.
I suspect it's because the index not being aligned with branch version.
> [release-ocm-2.7] Update default tag for index and service

- scripts/install_k8s_clients.sh
use sudo for installation of oc clients to prevent permission denied errors
> Use sudo when installing oc client

- scripts/install_environment.sh
At some point of time, my machine was consuming 100% CPU on
iptables-restore/iptables-save and I had to reboot the machine to
recover it.
This change deletes only the rules that need to be deleted instead of
doing a full save/restore of all iptables rules. I expect this process
to be lighter.
> NO-ISSUE: update libvirt hook to be lighter

- src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
- src/assisted_test_infra/test_infra/helper_classes/base_cluster.py
- src/assisted_test_infra/test_infra/helper_classes/cluster.py
- src/assisted_test_infra/test_infra/helper_classes/config/base_day2_cluster_config.py
- src/assisted_test_infra/test_infra/helper_classes/config/base_nodes_config.py
- src/assisted_test_infra/test_infra/helper_classes/day2_cluster.py
- src/tests/base_test.py
- terraform_files/baremetal/main.tf
- terraform_files/baremetal/variables-libvirt.tf
In the scope of testing heterogeneous clusters, the day2 cluster must use
its own terraform stack. To implement that, I updated the code to create
day2 clusters in the same way we create day1 clusters, using the fixtures.
> MGMT-13379: dedicated terraform stack for day2 cluster

- ansible_files/ansible.cfg
- ansible_files/equinix_heterogeneous_create_infra_playbook.yml
- ansible_files/roles/common/setup_sftp_share/defaults/main.yml
- ansible_files/roles/common/setup_sftp_share/tasks/main.yml
- ansible_files/roles/common/setup_sftp_share/templates/rclone.service.j2
- ansible_files/roles/common/setup_ssh_key_pair/defaults/main.yml
- ansible_files/roles/common/setup_ssh_key_pair/tasks/main.yml
- ansible_files/roles/common/setup_ssh_key_pair/templates/config.j2
Create a shared mount between the heterogenous hosts, so when the ISO image is downloaded on the primary, the secondary (ARM machine) hosts as also access to it automatically.
This changes creates a new role to setup the sshfs mount, fixes some linter issues in the ssh role and lower the ansible log level.
> MGMT-12442: Sync iso images between heterogeneous hosts

- requirements.txt
When trying to build assisted-test-infra container image, it fails for the following error:
```
× Running setup.py install for libvirt-python did not run
successfully.
│ exit code: 1
╰─> [38 lines of output]
running install
running build
running build_py
Missing type converters:
int *:1
ERROR: failed virDomainFDAssociate
...
```
Apparently it was fixed by
https://gitlab.com/libvirt/libvirt-python/-/tags/v9.0.0 so this bumps the library version.
> MGMT-13642: bump python-libvirt library to handle build failure

- requirements.txt
When trying to build assisted-test-infra container image, it fails for the following error:
```
× Running setup.py install for libvirt-python did not run
successfully.
│ exit code: 1
╰─> [38 lines of output]
running install
running build
running build_py
Missing type converters:
int *:1
ERROR: failed virDomainFDAssociate
...
```
Apparently it was fixed by
https://gitlab.com/libvirt/libvirt-python/-/tags/v9.0.0 so this bumps the library version.
Manual cherry-pick from https://github.com/openshift/assisted-test-infra/pull/2045
> [release-ocm-2.6] MGMT-13642: bump python-libvirt library to handle build failure (#2045)

- scripts/install_environment.sh
From time to time, the hook can fail with the following error:
```
Error: error creating libvirt domain: Hook script execution failed:
internal error: Child process (LC_ALL=C
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
/etc/libvirt/hooks/network test-infra-net-b4cf9b98 port-created begin -)
unexpected exit status 1: iptables: Bad rule (does a matching rule exist
in that chain?).
```
It is likekly due to rules being deleted between the time we list the
rules and the time we try to delete them in the hook.
This change makes the deletion of the rules best-effort.
x-ref: https://ci-jenkins-csb-kniqe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-assisted-installer-virt-tf/5991/testReport/test_proxy/TestProxy/Run_assisted_installer_Functional_API_Tests___test_incorrect_http_proxy_values_htt …
> NO-ISSUE: Best effort deletion of iptables rules

- ansible_files/roles/common/setup_libvirtd/files/allow-cross-network-traffic.sh
- ansible_files/roles/common/setup_libvirtd/handlers/main.yml
- ansible_files/roles/common/setup_libvirtd/tasks/main.yml
- scripts/install_environment.sh
The libvirt hook is required on the secondary (aka ARM) host in order to
allow traffic with the libvirt hosts on the primary machine.
> MGMT-12442: Setup libvirt hook on ARM machine

- Makefile
- src/assisted_test_infra/test_infra/controllers/node_controllers/nutanix_controller.py
- src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
- src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py
- src/assisted_test_infra/test_infra/tools/terraform_utils.py
- src/tests/base_test.py
- src/tests/test_targets.py
terraform.tfvars.json is generated on the flight and not stored on the file system.
After gather steps we call 'test_destroy_terraform' test to fetch active clusters, regenerate terraform.tfvars.json and run terraform destroy using python interface.
This fixes deprovision for terraform-controlled platforms - Nutanix and VSphere
> Add test which destroys targets via terraform

- src/assisted_test_infra/test_infra/helper_classes/nodes.py
During test_proxy we hit on SSHException("Invalid key") parmiko tries to connect , looks like re-try when hit on failures with differnt method on failure, we should catch ssh exception and hanlde it to make the waiter return bool value
> Fix ssh waiter - catch SSHException

- ansible_files/equinix_heterogeneous_create_infra_playbook.yml
- ansible_files/roles/test-infra/export-heterogeneous-day2-configuration/templates/assisted-additional-config.j2
- scripts/deploy_assisted_service.sh
In the context of heterogeneous cluster, we want the service URL to
target the private IP of the primary Equinix machine in order to pull
the ingnition from the secondary machine.
> MGMT-12442: Make service URL cutomizable

- scripts/override_os_images.py
Some installs (OKD, experiments with RHEL9) may need overriding OS_IMAGES in tests. This change will merge overrides defined in OS_IMAGES env var to the default images set in the json
> scripts: allow overriding base images via OS_IMAGE env var

- terraform_files/limit_ip_dhcp_range.xsl
When we have a network `172.16.20.2`, the current transformation is
invalid and gives `172.16.128` in output.
This change fixes this problem by replacing only the last characters
of a given IP.
> MGMT-12442: Fix DHCP limit range XSLT

- Makefile
Removing `_destroy_terraform_controller` target from `destroy_nodes` as it refers to an old unrelevant target
> NO-ISSUE: Removing old Makefile target

- ansible_files/equinix_heterogeneous_create_infra_playbook.yml
- ansible_files/roles/common/setup_ipip_tunnel/tasks/main.yml
- ansible_files/roles/equinix/export_primary_device_connection_details/files/fix-uid.sh
- ansible_files/roles/equinix/export_primary_device_connection_details/files/packet-conf.sh
- ansible_files/roles/equinix/export_primary_device_connection_details/tasks/main.yml
- ansible_files/roles/equinix/heterogeneous_create_infra/defaults/main.yaml
- ansible_files/roles/test-infra/export-heterogeneous-day2-configuration/templates/assisted-additional-config.j2
- terraform_files/equinix-ci-machine/main.tf
Few tactical changes to made the e2e test to work:
- Add `packet-setup.sh` to make it compatible with `assisted-baremetal-*` steps (should be cleaned up once [MGMT-11816](https://issues.redhat.com/browse/MGMT-11816) is implemented)
- `cloud-init status --wait` should always pass because cloud-init always fails with `c3.large.arm64` (reported to Equinix)
- Add a check that pings the tunnel ips to ensure the tunnel is setup properly
- [workaround] Use the tunnel ip has much a possible (rclone, virsh) to allow the secondary machine to reach the primary machine, it's probably due to firewalld installed with test-infra, but I don't see any misconfiguration
> MGMT-12442: Use arm plan to run heterogeneous test

- src/assisted_test_infra/download_logs/resources/man_sosreport.sh
- Setup proxy, required at least for ipv6 job
- remove `podman pull ...` before calling `toolbox` because it seems to always fail with `Error: stat /run/user/0/containers/auth.json: no such file or directory`
- pipe `yes` into `toolbox` because `toolbox` is an interactive command, and it sometimes asks questions where we want to answer `y` all the time
> MGMT-13792: Setup proxy when downloading logs

- src/assisted_test_infra/download_logs/resources/man_sosreport.sh
On OCP<=4.10, toolbox is too old and runs a shell instead of running the
command specified in parameter.
This change detects if the version of toolbox is too old and downloads
a more recent version of it if needed.
> MGMT-13792: fix download_logs for OCP <= 4.10

- src/tests/test_bootstrap_in_place.py
Ensure that retrying_run_container/run_container gets 4 params
> bootstrap_in_place: fix number of params when running butane

- src/service_client/assisted_service_api.py
Sometimes when downloading artifacts for failed clusters we get 404 for getting cluster's hosts.
I suspect the reason to be that we allow fetching of unregistered cluster, but do not use that argument when fetching full details of the clusters (to take the hosts for them).
It's looking something like:
```
18:10:49    File
"/mnt-assisted-log/workspace/download_logs/assisted-test-infra/src/assisted_test_infra/download_logs/download_logs.py",
line 136, in download_logs
18:10:49      cluster["hosts"] =
client.get_cluster_hosts(cluster_id=cluster["id"])
18:10:49
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
18:10:49    File
"/mnt-assisted-log/workspace/download_logs/assisted-test-infra/src/service_client/assisted_service_api.py",
line 129, in get_cluster_hosts
18:10:49 …
```
> Allow reading unregistered cluster details

- src/assisted_test_infra/test_infra/helper_classes/day2_cluster.py
Current flow for day2 installation try to approve workers csr while the node is rebooting and we keep trying in the waiter.
Added sshable waiter after day2 installation to verify that node really returns from reboot and approve the csr when node is up and running.
We have failures in kni-auto with day2 and it might be a timeing issue depends on reboot time of the installed node.
> Day2 post installation triggers node reboot while addding csr

- src/service_client/assisted_service_api.py
Reverts openshift/assisted-test-infra#2081
Apparently only admin users can read unregistered clusters, which makes QE tests fail (as they also go into this path of getting cluster details).
Reverting for now. Later on I'll prepare a patch which only requests unregistered clusters when asked for (and not for all cases).
> Revert "Allow reading unregistered cluster details"

- scripts/install_environment.sh
Not much in the release notes, but it did get a major code change:
https://github.com/Stratoscale/skipper/releases/tag/2.0.0
> bump skipper to v2.0.0

- scripts/download_logs.sh
Making it possible to run it as either:
* ``make download_cluster_logs`` - then it downloads logs for all available clusters.
* ``make download_cluster_logs CLUSTER_ID=...`` - then it downloads logs for the specified cluster ID.
Without this change ``make download_clsuter_logs`` just tries to do:
```
skipper run ... src.assisted_test_infra.download_logs ... --cluster-id # parameter value left empty
```
which doesn't download any log.
> Improve usability of download-logs

- src/assisted_test_infra/download_logs/download_logs.py
Currently test-infra tries to download ``kubeconfig-ingress`` even if we're not using it for gathering must-gather logs.
In triage logs download process we're having this kind of behavior, even though it doesn't succeed due to roles scheme. It produces a warning like:
```
18:23:56  2023-03-21 16:23:55,895  download_logs WARNING    -
140242975606592 - Suppressed ApiException from download_logs:246 :
(403)
18:23:56  Reason: Forbidden
18:23:56  HTTP response headers: ...
18:23:56  HTTP response body:
b'{"code":403,"message":"<user>: Unauthorized to access
route (insufficient role read-only-admin)"}'
```
This only does the download if configured to try and gather must-gather, making it produce less warning logs.
> Do not download kubeconfig if must-gather wasn't requested

- src/assisted_test_infra/download_logs/download_logs.py
- src/assisted_test_infra/test_infra/helper_classes/cluster.py
- src/service_client/assisted_service_api.py
Currently the method for fetching infra-env objects is as follows:
* Listing all existing clusters (including ones that are logically removed)
* Fetching cluster object from API (mainly to get the associated hosts which are not retrived in the first stage)
* Fetching infra-env objects from API based on IDs in the host objects
The problem is step 3, as infra-env objects might get deleted in the meantime, meaning those IDs no longer reference to existing infra-envs.
To minimize the problem, this change ignores infra-env IDs in the host objects, and just do another request for the infra-envs that are associated with a certain cluster ID.
It guarantees a more recent representation of current DB state, but more importantly we shouldn't get 404 for requesting those objects. Later on we download …
> Fix stale references to infra-envs

- scripts/download_logs.sh
Reverts openshift/assisted-test-infra#2093
This change causes the gathering of all clusters in triage process (including the ones succeeding installation).
Reverting for now because it's much more important to fix the triage process than local runs of ``make download_cluster_logs``
> MGMT-14117: Revert "Improve usability of download-logs"

- src/assisted_test_infra/test_infra/helper_classes/config/base_cluster_config.py
- src/assisted_test_infra/test_infra/helper_classes/config/base_config.py
- src/assisted_test_infra/test_infra/helper_classes/config/base_infra_env_config.py
- src/tests/config/global_configs.py
- src/tests/test_bootstrap_in_place.py
- Fix wrong casting type on base configuration
- Fix issues caused by the duplication of `cluster_name` and `entity_name` on `ClusterConfig`.
/cc @eliorerz
> NO-ISSUE: Fix multiple bugs

- src/assisted_test_infra/download_logs/download_logs.py
The format used for exceptions that happen when fetching SOS reports fail is incorrect. This patch fixes that.
> NO-ISSUE: Fix SOS report exception message format

- src/assisted_test_infra/test_infra/controllers/node_controllers/node.py
In some cases when trying to init ssh connection we may get paramiko.ssh_exception.SSHException: Invalid key
While trying to connect to multiple ips we may catch it to prevent raising it back till we complete ssh tries
> Add SSHException catch when ssh_connection

- src/service_client/assisted_service_api.py
When searching for all infra-envs binding to a particular cluster, we
should ignore infra-envs that are not binding to any cluster, instead of
crashing
See failure http://assisted-jenkins.usersys.redhat.com/job/download_logs/51070/console
> Don't crash on non-binding infra-envs

- src/assisted_test_infra/test_infra/utils/operators_utils.py
- src/tests/global_variables/env_variables_defaults.py
Allow to pass multiple OLM operators using environment variables 
e.g.
```bash
OLM_OPERATORS=lvm,cnv make test
```
or
```bash
OLM_OPERATORS=lvm cnv make test
```
/cc @osherdp @adriengentil
> NO-ISSUE: Fix parsing olm operator env var list

- Makefile
During the tests `e2e-metal-assisted-kube-api-late-binding-single-node` and `e2e-metal-assisted-kube-api-late-unbinding-single-node`
The installation of the Assisted Service Operator fails on the hub due to a catalog source error
```
{
"message": "constraints not satisfiable: no operators found in channel ocm-2.8 of package assisted-service-operator in the catalog referenced by subscription assisted-service-operator, subscription assisted-service-operator exists",
"reason": "ConstraintsNotSatisfiable",
"status": "True",
"type": "ResolutionFailed"
}
```
This PR addresses that issue by making sure that the correct version of the assisted service and the correct version of assisted-service-index are used in the test.
Prior to this PR, the service was using the latest image, as was the index.
> MGMT-14411: Fix for OCM 2.8 test failures

- Makefile
In Makefile, ensure ADDITIONAL_MANIFEST_DIR exists before trying to move its content.
Needed for trying to resolve the issue in
e2e-metal-single-node-live-iso job[*]
```
mv /root/sno-additional-manifests/* /home/sno/sno-additional-manifests/
mv: cannot stat '/root/sno-additional-manifests/*': No such file or directory
make: *** [Makefile:280: deploy_ibip] Error 1
```
Note: could be related to https://github.com/openshift/release/pull/39064
[*] https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_assisted-test-infra/2143/pull-ci-openshift-assisted-test-infra-master-e2e-metal-single-node-live-iso/1655682994788110336/build-log.txt
> NO-ISSUE: ensure ADDITIONAL_MANIFEST_DIR exists

- Makefile
- README.md
- src/assisted_test_infra/test_infra/helper_classes/cluster.py
- src/assisted_test_infra/test_infra/helper_classes/day2_cluster.py
- src/assisted_test_infra/test_infra/helper_classes/entity.py
- src/tests/test_targets.py
Currently `deploy_nodes` target is deploying nodes and preparing the networking. 
Due to QE request we need to split this targets and allowing deploy the nodes without setting the network configurations.
In this PR:
- `prepare_for_installation`  function was split into two new functions - `prepare_nodes` and `prepare_networking`
- `deploy_nodes`  target is deploying the nodes without setting up the networking
- `deploy_nodes_with_networking` target was added - same logic as the previous `deploy_nodes`
/cc @osherdp @lalon4
> MGMT-14563: Make deploy_nodes target to deploy nodes without networking

- skipper.yaml
- src/assisted_test_infra/test_infra/controllers/iptables.py
IptableRule class supports v4 address rules for actions. Added ip6tables to support ipv6 rules.
The flow is the same only the iptables binaries changed from iptable to ip6table
> Add support for ip6tables to handle ipv6 rules

- src/assisted_test_infra/test_infra/helper_classes/cluster.py
Adding timeout variable for waiting to all host to reach progress stage
Before this PR we were limited by the default  CLUSTER_INSTALLATION_TIMEOUT / 2
> Add timeout on wait_for_hosts_stage

- src/tests/test_upgrade_agent.py
The upgrade agent prepares a cluster for installation with an old agent image and then checks that it can be upgraded to the latest one. But that old image is no longer capable to move the cluster to ready because of changes to the DNS resolution validation. To address that issue this patch changes the test to use a newer old image.
Related: https://issues.redhat.com//browse/MGMT-14526
Related: https://github.com/openshift/assisted-service/pull/5208
Related: https://github.com/openshift/assisted-installer-agent/pull/542
> Update old image used by upgrade agent test

- src/assisted_test_infra/test_infra/controllers/node_controllers/__init__.py
- src/assisted_test_infra/test_infra/controllers/node_controllers/node_controller.py
- src/assisted_test_infra/test_infra/controllers/node_controllers/nutanix_controller.py
- src/assisted_test_infra/test_infra/controllers/node_controllers/tf_controller.py
- src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py
- src/tests/global_variables/env_variables_defaults.py
This PR is prerequisite to OCI controller https://github.com/openshift/assisted-test-infra/pull/2170
After merge the code will be removed from the draft PR.
This controller will replace in the future the current `TerraformController` + `LibvirtController`.
The hierarchy should be as followed:
```
├── NodeController
├── TFController
│   ├── NutanixController
│   ├── VsphereController
│   ├── OciController  --> Not implemented yet (will be on https://github.com/openshift/assisted-test-infra/pull/2170)
│   └── LibvirtController  --> Not implemented yet
│
└──  LibvirtController  --> Will be deprecated in the future 
└──  TerraformController  --> Will be deprecated in the future
```
/cc @eliorerz
> MGMT-14737: Add base terraform controller for both vsphere and nutanix.

- src/assisted_test_infra/test_infra/utils/utils.py
Allow getting default value for `openshift_version` in case the service is not present or in case that `assisted-service/data/default_release_images.json` is missing
/cc @adriengentil @osherdp
> MGMT-14808: Fallback to local default OCP version in case that there are no service present

- src/assisted_test_infra/test_infra/helper_classes/cluster.py
- src/assisted_test_infra/test_infra/utils/waiting.py
- src/tests/test_upgrade_agent.py
Currently the agent upgrade test uses a non existing image to ensure that all the hosts have stopped using the previous image. This causes timeouts because when hosts try to register using that non existing image they fail and then wait for one hour. To avoid that this patch changes the test so that it doesn't use that non existing image, instead of that it explicitly waits till all the hosts have upgraded to the new image.
Related: https://issues.redhat.com//browse/MGMT-14526
> Don't use non existing image for agent upgrade test

- src/consts/consts.py
As part of the effort to remove support for openshift version 4.8, I remove related traces in `test-infra`
> MGMT-14630: removing support for openshift version <= 4.8

- src/assisted_test_infra/test_infra/helper_classes/config/base_config.py
- src/tests/base_test.py
- src/tests/global_variables/default_variables.py
- src/triggers/env_trigger.py
We currently can only differ if variable is set as environment variable or not.
This PR add the option to know the origin of a variable - where it was set
> MGMT-15018: Add option to mark variable origin

- Dockerfile.assisted-test-infra
- ansible_files/ansible.cfg
- ansible_files/oci_generic_destroy_ci_machine_playbook.yml
- ansible_files/roles/oci/create_infra/tasks/main.yml
- ansible_files/roles/oci/export_connection_details/files/packet-conf.sh
- ansible_files/roles/oci/export_connection_details/tasks/main.yml
- ansible_files/roles/oci/setup_oci_for_test_infra/templates/assisted-additional-config.j2
- scripts/bring_assisted_service.sh
- scripts/hub-cluster/kind/kind.sh
- scripts/hub-cluster/minikube.sh
- scripts/install_k8s_clients.sh
- scripts/utils.sh
- src/assisted_test_infra/test_infra/controllers/node_controllers/oci_controller.py
- src/assisted_test_infra/test_infra/controllers/node_controllers/tf_controller.py
- src/assisted_test_infra/test_infra/utils/utils.py
- src/triggers/default_triggers.py
- terraform_files/oci-ci-machine/02_network_security_groups.tf
- terraform_files/oci-ci-machine/03_compute.tf
- terraform_files/oci/01_network_security_groups.tf
- terraform_files/oci/03_compute.tf
Fix several fixes in order to make the OCI e2e test work in Prow:
- Fix NSGs on clusters nodes
- Allow communications between them
- Allow communications from the nodes to the LB 
- Prevent the creation of DNS entries on the CI machine, it's not required since we setup DNS in OCI 
- Implemented various retries, I observed a lot of flakiness from OCI
- Force user managed networking to true when platform is OCI
> MGMT-14240: Plug OCI platform e2e test into CI

- src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
- src/assisted_test_infra/test_infra/controllers/node_controllers/node.py
- src/assisted_test_infra/test_infra/controllers/node_controllers/node_controller.py
- src/assisted_test_infra/test_infra/controllers/node_controllers/nutanix_controller.py
Added iso file path when user change the boot order. It will allow us in a cluster to boot nodes with different iso files uscases:
- Day2 master must be in the same network as day1 masters, we can re-use one of the existing nodes to become a day2 master by overriding iso file
- Static network changes requires to download the iso again but we dont want to override all nodes iso path
- Validate re-download iso file when different configurations (proxy)
- Add support for re-usable nodes plus check how we manage multiple iso in a cluster deployment
In case we want to re-use the node with same network params. node.set_boot_order(cd_first=True, cdrom_iso_path="/tmp/test.iso) node.start()
> Add support to update iso file for set_boot_order

- src/assisted_test_infra/test_infra/controllers/node_controllers/ssh.py
It seems like paramiko has a known issue where sometimes keys are not treated with the right encryption method (in our case as DSA instead of RSA):
https://github.com/paramiko/paramiko/issues/1839
[an example for such an error](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-ipv4v6-periodic/1677886652934000640)
Until there's a fix, this works around this issue by creating the key object with the intended encryption method RSA.
> Fix paramiko incorrectly auto-detects private key method

- .github/dependabot.yml
Following instructions at
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups, this makes dependabot to only open one PR for updating all the Python third-party dependencies, which should save some costs for us (as we don't need to run several e2e tests for each dependency being changed).
/cc @adriengentil @eliorerz
> Group dependabot updates in one PR

- src/tests/base_test.py
- src/tests/test_targets.py
Sometimes for testing purposes we want to create nodes on one platform and set the cluster platform with another, e.g.
```bash
make test TF_PLATFORM=nutanix PLATFORM=baremetal
``` 
Also remove unused code that uses `get_terraform_controller` method
/cc @osherdp @adriengentil
> NO-ISSUE: Fix issue that prevent deploying nodes on platform different from cluster platform

- terraform_files/oci/03_compute.tf
- terraform_files/oci/variables.tf
- Tag cluster nodes with a specific tag
- Create a dynamic group for the master nodes based on tag
- Create a policy based on the dynamic group in order to allow the masters/CCM to be authorized to manage instances/networks/load-balancers in OCI
> MGMT-15312: Create  policy for OCI CCM in terraform

- src/assisted_test_infra/download_logs/download_logs.py
We currently are storing it as 'tar' which can confuse some extraction utilities.
> Fix must-gather extension to '*.tar.gz'

- terraform_files/oci-ci-machine/00_main.tf
- terraform_files/oci-ci-machine/03_compute.tf
- terraform_files/oci-ci-machine/variables.tf
- terraform_files/oci/00_main.tf
OS images are updated regulary and old ones expire. In order to avoid
spending time to update OS images when job start to fail, use a regex to
select the right OS image.
I took the opportunity of this PR to update OCI provider version.
> NO-ISSUE: Use a regex to select OS image in OCI

- ansible_files/oci_generic_cleanup_playbook.yml
- ansible_files/roles/oci/cleanup_resources/defaults/main.yml
- ansible_files/roles/oci/cleanup_resources/tasks/main.yml
Create a new playbook that will be called periodically to cleanup
dangling resources in OCI CI compartment.
The task cleans up almost all created resources during CI test except:
- dynamic groups, created in root compartment
- DNS records, which are missing metadata and creation date to remove
them easily
These two missing elements will be implemented later.
> MGMT-14094: Cleanup dangling resources in OCI

- ansible_files/ansible.cfg
- ansible_files/oci_generic_cleanup_playbook.yml
- ansible_files/roles/oci/cleanup_resources/defaults/main.yml
Few changes:
- Fix how credentials are passed
- Exclude `oci_load_balancer_backend_set`, it will be deleted along the
LB it belongs to
- Improve ansible output
> MGMT-14094: Fix oci cleanup

- ansible_files/roles/oci/cleanup_resources/tasks/main.yml
Add cleanup for network load balancers. Use another field to determine
at which time the resource was created, because `time_created` format is
not consistent accross resources.
> MGMT-14094: Cleanup network load balancers in OCI

- src/consts/consts.py
- src/triggers/default_triggers.py
To enable s390x architecture a trigger is necessary to set the required values for user_managed_networking (true) and iso_image_type (full_iso).
> MGMT-15707: Add s390x trigger

- ansible_files/roles/oci/cleanup_resources/defaults/main.yml
- ansible_files/roles/oci/cleanup_resources/tasks/cleanup_resources.yml
- ansible_files/roles/oci/cleanup_resources/tasks/main.yml
Check that a state file was generated by the import process. When no
state file is present, it means no resources were found in the
compartment.
Exclude network load blancer backend, backend_set and listener resources
from deletion as they will be deleted when the parent LB is deleted.
> MGMT-14094: Manage case when no resources are found in OCI

- src/service_client/assisted_service_api.py
A recent change to Assisted Service changed the default behaviour of the manifest list functionality. By default, the manifest list will only return manifests that were supplied by the user and will exclude system generated manifests.
This PR works in conjunction with a PR to the service https://github.com/openshift/assisted-service/pull/5498/files  (and corresponding Python client) to supply an additional parameter
"include_system_generated" and set this to "true" so that assisted-test-infra will fetch all manifests irrespective of type.
> MGMT-15598: Bugfix - list all cluster manifests irrespective of type

- requirements.txt
Dependabot updates are failing because Kubernetes library requires urlib3 < 2.0.
x-ref: https://github.com/openshift/assisted-test-infra/pull/2280
> NO-ISSUE: use urlib3 < 2.0

- ansible_files/roles/oci/cleanup_resources/defaults/main.yml
- ansible_files/roles/oci/cleanup_resources/tasks/cleanup_resources.yml
2 resources were deleted too early because we don't know when they were
created.
- `oci_core_network_security_group_security_rule`: exclude it from
deletion, the parent network security group will delete it
- `oci_objectstorage_object`: exclude it from deletion if its parent
bucket is already excluded
> NO-ISSUE: fix oci cleanup

- Makefile
By default in release-ocm-2.9 branch, pull ocm-2.9 tag for service and index images.
> MGMT-15945: Pull service and index images from ocm-2.9 tag

- src/assisted_test_infra/test_infra/controllers/node_controllers/node_controller.py
- src/assisted_test_infra/test_infra/helper_classes/cluster.py
tf_platform represents the instrastructure that test-infra is
provisionning. We don't want to provision a LB when we deploy an
external platform cluster on top of OCI.
> MGMT-15695: check tf_platform to know if LB is required

- src/service_client/logger.py
With this change we will print to log the function called by the line. example:
Adding rule - [path]/nat_controller.py:98)->_insert_rule (/home/benny/assisted-test-infra/src/tests/base_test.py:82)->update_parameterize
> Add function name caller to test-infra logs

- src/service_client/logger.py
Current code shows thread id in log file, the problem in parallel run that we create multiple proccesses and each one create threads. Due to that we may see same thread_id when calling threading.get_ident() under different services.
solution is to add the process id to the thread and create combination thread_id:proccess_id . i think under the same proccess we may not see duplicate thread id.
by default python store the thread_id and proccess_id unless user disable it. logging.logThreads = True
logging.logProcesses = True
> Fix thread id in test-infra.log file

- src/assisted_test_infra/test_infra/helper_classes/cluster.py
This method called from many places in kni test.
I changed the function signiture to simple str and move the logic dictionay in the functions for next changes if we will have
> Add set_ingress_and_api_vips function to cluster

- terraform_files/equinix-ci-machine/main.tf
- terraform_files/equinix-ci-machine/variables_equinix.tf
Due to deprecation of `facilities`  we are moving to use `metro` instead 
1. This change won't effect CI, the CI configured to use `any` which is default
2. after merge, we will hard coded which metros to use.
```yaml
env:
...
- name: PACKET_FACILITY
default: any
....
```
> MGMT-15772: Moving Equinix to use Metros

- terraform_files/equinix-ci-machine/main.tf
- terraform_files/equinix-ci-machine/variables_equinix.tf
Reverts openshift/assisted-test-infra#2347
* cannot use metro as `any` `null` or a list
> Revert "MGMT-15772: Moving Equinix to use Metros"

- scripts/deploy_assisted_service.sh
- src/assisted_test_infra/test_infra/utils/utils.py
- src/tests/conftest.py
Allow using custom `OCP` release when we create cluster - Within the CI environment, our aim is to load the fewest possible number of ISO images because the image-service takes a significant amount of time to load each one. Conversely, for scenarios outside of CI, we aim to facilitate the installation of each `OCP` release using test-infra, necessitating the loading of all ISO images.
> MGMT-16499: Allow using custom OCP release when we create cluster

- src/assisted_test_infra/test_infra/controllers/node_controllers/node_controller.py
- src/assisted_test_infra/test_infra/controllers/node_controllers/tf_controller.py
- src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py
- src/assisted_test_infra/test_infra/helper_classes/entity.py
- src/assisted_test_infra/test_infra/helper_classes/nodes.py
- src/tests/test_targets.py
Currently the controllers are initialized before the cluster creation causing the terraform resources names to be different than the given ones (only in case where the cluster has a different name than the generated one - e.g create cluster via the UI and pass CLUSTER_ID)
Currently, the node controllers are initialized before the cluster creation, causing the Terraform resources names to be different from the ones provided (but only in cases where the cluster has a different name than the generated one). For example, if you create a cluster using the UI and pass CLUSTER_ID, this issue occurs.
> MGMT-15510: Initialize terraform controller after cluster registration

- src/tests/test_e2e_install.py
We have removed support for SDN from OCP 4.15 onward. This will throw explicit error early in case of misusage of assisted-test-infra
/cc @eifrach @adriengentil
> MGMT-16330: disallow SDN network type testing for 4.15 and above

- src/assisted_test_infra/test_infra/utils/utils.py
add `status_info` to logging  if cluster installation fails
> NO-ISSUE: add info for cluster status

- terraform_files/equinix-ci-machine/main.tf
At the moment, 1.25.0 fails to be downloaded. Use 1.24.0 to unblock the
CI.
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_assisted-service/5892/pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted/1747851387535888384
> NO-ISSUE: Set version 1.24.0 for equinix provider

- src/assisted_test_infra/test_infra/helper_classes/cluster.py
- src/consts/consts.py
- src/triggers/default_triggers.py
Update assert against `get_cluster_supported_platforms` in order to pass if platform name is `oci`, in order to be able to to provision a cluster using SaaS in production. It is required because the external platform is not fully enabled yet in production.
> NO-ISSUE: Update OCI check to test against stage/prod

- src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
Current add_interface set the interface speed to 100M and limit the internal traffic between nodes when set the interface as CIDR and VIP Added default to virtio, configured the attach interface speed as N/A
> Add default model when libvirt add_intrerface

- terraform_files/oci-ci-machine/00_main.tf
- terraform_files/oci/00_main.tf
- terraform_files/oci/01_network_security_groups.tf
Open port 6443 when installing a cluster on OCI so we can run the OPCT
test suite directly from Prow.
Since the access is authenticated, and the cluster is ephemeral, it
should not be security issue to open this port to the world.
> MGMT-16493: Open KAS port when installing OCI cluster

- Makefile
By default in release-ocm-2.10 branch, pull ocm-2.10 tag for service and
index images.
> [release-ocm-2.10] MGMT-16877: Pull ocm-2.10 tag

- ansible_files/roles/oci/cleanup_resources/defaults/main.yml
The OPCT test job can run for up to 7 hours, this change adjust the OCI
cleanup process accordingly.
> NO-ISSUE: Adjust cleanup in OCI

- Makefile
Move it under a better maintained place (at `edge-infrastructure` project).
> Move dynamic-load-balancer image

- terraform_files/equinix-ci-machine/main.tf
- terraform_files/equinix-ci-machine/variables_equinix.tf
Move Equinx to use metro
1. updating provider version to 1.32
2. setting metro instead of facilities
3. default `metro` is DA ( dallas )
metro DA has all need metal servers including ARM based
* note: there is one more metro with ARM images which is DC
> MGMT-15772: change facilities to metro

- src/assisted_test_infra/test_infra/controllers/ipxe_controller/server/Dockerfile
Change to use a base python image to run the iPXE server as the other one was from a private repository.
> NO-ISSUE: Use legit python image for failing ipxe CI test

- packer_files/nutanix_centos_template/centos-config/ks.cfg
- packer_files/nutanix_centos_template/sources.pkr.hcl
- packer_files/nutanix_centos_template/variables.pkr.hcl
Use the public ssh key that is CI vault instead of the one hard-coded in nutanix packer configuration files
> NO-ISSUE: Add generic CI SSH key for nutanix packer

- scripts/create_full_environment.sh
- scripts/install_environment.sh
- scripts/utils.sh
- terraform_files/baremetal_host/main.tf
Currently, `assisted-test-infra` is only compatible with `Rocky8`, `RHEL8`, and `CentOS8`. As `RHEL8` approaches end-of-life (`EOL`) at the end of this month, we aim to also support `Rocky9`, `RHEL9`, and `CentOS9`. A primary challenge with `stream9` is the absence of `xinetd` in these releases. To address this, I have replaced the port forwarding mechanism with `systemd` socket to listen (with `socat`) and service to forward. This solution should work on all versions.
> MGMT-17250: Support RHEL9

- requirements.txt
Some package names were incorrectly written with erroneous characters, causing certain IDEs to mistakenly believe that the packages were not present.
Also update `pycharm-remote-debugger` to latest
/cc @danmanor @adriengentil
> NO-ISSUE: Update `requirements.txt` to match the package naming conventions of the interpreter.

- src/assisted_test_infra/test_infra/helper_classes/cluster.py
- src/assisted_test_infra/test_infra/utils/waiting.py
Getting host status is not enough , we would like to catch a host in detailed status info.
Example:
installing-in-progress Waiting for bootkube and others
> Add status_info for waiting for specific host

- packer_files/vsphere_centos_template/build.pkr.hcl
- packer_files/vsphere_centos_template/variables.pkr.hcl
- src/assisted_test_infra/test_infra/controllers/node_controllers/node_controller.py
- src/assisted_test_infra/test_infra/controllers/node_controllers/tf_controller.py
- src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py
- src/assisted_test_infra/test_infra/helper_classes/entity.py
- src/assisted_test_infra/test_infra/helper_classes/nodes.py
- src/tests/test_targets.py
- Update vsphere packer plugin. 
- Update default iso_url image ISO
- Remove image ISO default checksum 
This PR completes the work done on https://github.com/openshift/release/pull/52387
Also this PR reverts https://github.com/openshift/assisted-test-infra/pull/2353 due to error in vsphere and nutanix jobs 
```
'NoneType' object has no attribute 'get_resources' AttributeError Traceback (most recent call last):
File "/root/.pyenv/versions/3.12.0/lib/python3.12/site-packages/junit_report/decorators/_junit_decorator.py", line 51, in _wrapper
value = self._execute_wrapped_function(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/root/.pyenv/versions/3.12.0/lib/python3.12/site-packages/junit_report/decorators/_junit_fixture_test_case.py", line 80, in …
```
> NO-ISSUE: Update vsphere packer plugin and packer base ISO

- src/assisted_test_infra/download_logs/__main__.py
- src/assisted_test_infra/test_infra/helper_classes/config/base_nodes_config.py
- src/service_client/assisted_service_api.py
As part of the triage process, we download logs for all the failed cluster installations and create jira tickets for each failed installation.
Currently, we download all the logs time and time again, and this PR adds additional optional argument, a file containing a list of cluster ids, which we can exclude from downloading.
Also, since SSO_URL is a required env var, I added an exception in case it is not set.
> MGMT-17246: add support for ignoring clusters that already exist on jira

- src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
- src/assisted_test_infra/test_infra/helper_classes/config/base_nodes_config.py
- src/tests/base_test.py
- src/tests/config/global_configs.py
In this PR:
- Changed in `BaseTest` methods:
- `get_nodes` - Unused fixture - Removed
- `get_cluster` - Unused fixture - Removed
- `wait_for_controller` - Unused method - Removed
- `verify_no_logs_uploaded` - Unused method - Removed
- `_collect_virsh_logs` - Moved to `utils.logs_utils.py`
- Added some of missing hint annotations in `BaseTest`. 
- Add `get_base_asset` method to be under `Day2ClusterConfig` instead of const under `BaseTest.prepared_day2_controller_configuration`.
> NO-ISSUE: Remove unused methods from `BaseTest` class and add missing type hint annotations

- terraform_files/oci-ci-machine/00_main.tf
- terraform_files/oci-ci-machine/03_compute.tf
Use Rocky Linux instead of Oracle Linux in order to be consistent with our other workload, and avoid issues like 'crb' repo being unavailable.
Since Rocky is provided by the OCI marketplace, we need to fetch the image from there, and create the necessary resources to accept the agreement to use that OS.
See https://blogs.oracle.com/cloud-infrastructure/post/using-terraform-for-marketplace-images
> MGMT-18118: Use Rocky Linux 9 on OCI

- src/assisted_test_infra/test_infra/helper_classes/cluster.py
- src/assisted_test_infra/test_infra/helper_classes/infra_env.py
- src/tests/base_test.py
- src/tests/conftest.py
This PR fixes multiple bugs related to cluster configuration:
- Fix cluster configuration name is not properly set on update cluster
- Update cluster configurations when `cluster_id` is provided.
- Allow getting `api_client` fixture without failing on kube api.
- Update infra-env iso-image-type when infra-env is exists
> NO-ISSUE: Fix cluster configuration name is not properly set on update cluster

- scripts/install_environment.sh
Add fallback installation with `crb` repository as it is included by default in some `RHEL9` versions and causes an error when specified
> NO-ISSUE: Add fallback installation with crb repository as it is included by default in some OS variants and causes an error when specified

- src/consts/consts.py
- Set OCP 4.16 as default OCP version
- Enable OCP 4.17 installation
> MGMT-18077: Set OCP 4.16 as default, add OCP 4.17 option

- .gitignore
- Dockerfile.assisted-test-infra
- Makefile
- README.md
- scripts/bring_assisted_service.sh
- scripts/create_full_environment.sh
Currently, we generate python client for assisted-service inside its primary Dockerfile. In order to generate the python client, we need the repository git tags. This behavior collisions with Konflux behavior because Konflux builds the image, searching for the tags in the fork instead of the upstream repository. As a result developers currently need to periodically push git tags to their fork for konflux to build successfully. 
This PR generates generated assisted-service client during assisted-test-infra image build, so later we could follow with a PR to remove assisted-service's generation
reference - https://redhat-internal.slack.com/archives/C035X734RQB/p1719496182644409
> MGMT-18333: Generate python client instead of using the one from assisted-service image

- terraform_files/oci-ci-machine/03_compute.tf
The name to fetch Rocky Linux in OCI was updated
> NO-ISSUE: Fix name to fetch Rocky in OCI

- src/assisted_test_infra/test_infra/controllers/ipxe_controller/ipxe_controller.py
- src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
Curren iPXE script contains links redirected to https, PXE can not run the downloaded script directly from node.
Steps: (as descibied in UI)
Download the example iPXE script file
Download the assets in the script file to your iPXE server Inside the example script file, customize the asset URLs to your local server address
- Added support for libvirt undefine network
- Added new flag local_pxe_assets to keep support "other" without modifying the pxe content
- Download the ipxe , decode to utf-8 and download http links to the container directoy
- Modify the iPXE scrips link to download from container.
iPXE script should contain local address  http://192.168.XXX.1:8500/ for each image type  pxe-initrd, kernel, rootfs
> iPXE assets download to container and modify iPxe script

- Makefile
- src/tests/templates/day2_baremetal.yaml.j2
- src/tests/templates/day2_machine.yaml.j2
- src/tests/test_ctlplane_scaleup.py
This pull request adds a new test to scale the control plane up to 5 nodes and check if etcd is running correctly.
This is a new feature added by the etcd team in [ETCD-540](https://issues.redhat.com/browse/ETCD-540) for versions 4.17+
> MGMT-18626: Add TestClusterScaleUp for baremetal spanned clusters

- .gitignore
- src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
- terraform_files/baremetal/main.tf
- terraform_files/baremetal/variables-libvirt.tf
When deploying static networking the network has DHCP.
In some cases where the IP config is invalid the installation continues using DHCP
> MGMT-18852: disable DHCP for static networking

- scripts/override_images/override_release_images.py
To avoid having to set `OPENSHIFT_INSTALL_RELEASE_IMAGE = ""` in the CI jobs
> MGMT-19039: Prioritize OPENSHIFT_VERSION over OPENSHIFT_INSTALL_RELEASE_IMAGE when overriding images

- src/assisted_test_infra/test_infra/controllers/node_controllers/oci_api_controller.py
Sometimes during stack apply we hit on:
Error: 400-InvalidParameter, Failed to validate tags: TagNamespace openshift-test-infra-cluster-b1c19bff does not exists Suggestion: Please update the parameter(s) in the Terraform config as per error message Failed to validate tags: TagNamespace openshift-test-infra-cluster-b1c19bff does not exists
Set the param in terraform.
description = "Name of tag namespace to create or use for tagging OCI resources". Defaults to "openshift-{cluster_name}"
> OCI: Add default tag_namespace_name for terraform variables.

- Dockerfile.assisted-test-infra
When running `make setup` on a clean Centos stream 9 machine, we get a timeout when running `terraform ... init` for the equinix plugin.
Increasing the time solved the issue.
---
/cc @eliorerz
> Increasing Terraform's timeout.

- src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
Libvirt allows to boot from network and set order per interface with <boot order= /> When try to add support for boot order when disk exists it rejected by libvirt: unsupported configuration: per-device boot elements cannot be used together with os/boot elements
Adding support to clean network from os boot and from interfaces.
In case of boot from iSCSI we must add the provision interface as primary interface to boot from.
> MGMT-17556: Add network to clean os boot data

- Dockerfile.assisted-test-infra
- skipper.yaml
- src/assisted_test_infra/test_infra/controllers/__init__.py
- src/assisted_test_infra/test_infra/controllers/iscsi_target_controller.py
- src/tests/base_test.py
Create iqn class - represent iqn format
Create a reciever - a callback run the tatgetcli command on concrete device (ssh or local)
The isciTargetController gets from the user requested configuration to apply, passing the configuration to a builder .
> MGMT-17556: Add iscsi target controller , allow to boot from iscsi or attach

- scripts/download_logs.sh
The current logs gathering step for assisted-service fails downloading some logs from assisted-service as it assmes minikube deployment.
> NO-ISSUE: Fix logs gathering for kind deployment in the CI

- scripts/download_logs.sh
- scripts/utils.sh
- enable sourcing utils.sh in function calls
- Fix download_logs url
The logs are collected now -  https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_assisted-test-infra/2576/pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted/1861049718910488576/artifacts/e2e-metal-assisted/assisted-common-gather/artifacts/2024-11-25_15-05-40_85b00325-b4ac-4ec9-bd07-00c1292f2162/
> NO-ISSUE: Enable sourcing utils.sh in function calls

- src/service_client/assisted_service_api.py
Remove deletion of `control_plane_count` field during cluster creation as it was replaced in https://github.com/openshift/assisted-test-infra/pull/2569 to conditionally adding this field
> NO-ISSUE: Remove deletion of `control_plane_count` field during cluster creation

- scripts/bring_assisted_service.sh
Enable assisted-service fetching by specific commit reference in order to match the python client version used by QE in integration / stage / prod environments to assisted-service image deployed there
> MGMT-19336: Enable assisted-service fetching by specific commit reference

- src/consts/olm_operators.py
- src/triggers/default_triggers.py
- Testing with 3 masters and 3 workers, the osc operator can be installed. 
- Testing with SNO, the osc operator can be installed.
> MGMT-19236: Add Openshift sandboxed containers operator(OSC) support

- README.md
- scripts/deploy_assisted_service.sh
- scripts/override_images/override_os_images.py
- scripts/override_images/override_release_images.py
- src/assisted_test_infra/test_infra/helper_classes/cluster.py
- src/assisted_test_infra/test_infra/utils/utils.py
- src/consts/consts.py
- src/tests/global_variables/default_variables.py
- src/tests/global_variables/env_variables_defaults.py
Adjust the correct `cpu_architecture` which should be used for cluster, infraenv creation
> MGMT-19278: Use multi-arch OCP release images with OPENSHIFT_VERSION configuration

- src/tests/test_e2e_install.py
```
File "/root/.pyenv/versions/3.12.0/lib/python3.12/site-packages/semver/version.py", line 646, in parse
raise ValueError(f"{version} is not valid SemVer string")
ValueError: 4.14-multi.0 is not valid SemVer string
```
> NO-ISSUE: Fix networking test OCP version handling

- scripts/override_images/override_release_images.py
`suffix` is `-multi` not `multi` in this case
> NO-ISSUE: Fix multi-arch version usage with OPENSHIFT_VERSION

- .flake8
- src/assisted_test_infra/test_infra/helper_classes/cluster.py
- src/assisted_test_infra/test_infra/utils/utils.py
- src/consts/__init__.py
- src/consts/consts.py
Adding validation for static IP's.
This will check the current IP  vs the static config and return validation error if one or more are not matching  
log example:
```console
2024-12-15 14:48:19,302  root INFO       - 140045960247104 - Static IP validation: host network {'02:00:00:ef:b6:0e': {'ipv4_addresses': ['192.168.128.33/24']}, '02:00:00:24:fd:ad': {'ipv4_addresses': ['192.168.146.33/24']}, '02:00:00:7e:21:90': {'ipv4_addresses': ['192.168.128.31/24']}, '02:00:00:cb:86:0d': {'ipv4_addresses': ['192.168.14
6.31/24']}, '02:00:00:8f:c7:71': {'ipv4_addresses': ['192.168.128.30/24']}, '02:00:00:9d:f2:fe': {'ipv4_addresses': ['192.168.146.30/24']}, '02:00:00:cc:82:6e': {'ipv4_addresses': ['192.168.128.32/24']}, '02:00:00:b8:82:49': {'ipv4_addresses': ['192.168.146.32/24']}, …
```
> MGMT-18852: Static IP validation

- src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
In case we have a failure in a test before the concrete resource created, We may return another failure in teardown when network does not exist
Cached exception in case the libvirt network not created.
> Fix collect log raise exception when network does not exist

- src/tests/test_kube_api.py
Fix DNS setting in kube api tests:
```
Trying to pull registry.build01.ci.openshift.org/ci-op-02vcdx9p/pipeline@sha256:cc3ce78e311b6d94bdaa9170212d1b901534ded6f61f81e3fa0c478c8c13ad94...
[2024-12-29 06:52:03] Error: initializing source docker://registry.build01.ci.openshift.org/ci-op-02vcdx9p/pipeline@sha256:cc3ce78e311b6d94bdaa9170212d1b901534ded6f61f81e3fa0c478c8c13ad94: pinging container registry registry.build01.ci.openshift.org: Get "https://registry.build01.ci.openshift.org/v2/": dial tcp: lookup registry.build01.ci.openshift.org on 127.0.0.1:53: read udp 127.0.0.1:57990->127.0.0.1:53: read: connection refused == *\f\a\i\l\e\d\ 
```
> NO-ISSUE: Fix DNS setting in k8s API test

- src/assisted_test_infra/test_infra/controllers/iscsi_target_controller.py
iSCSI target by default fails on data out timeout on hypervisor when multiple nodes. The error was:
Unable to recover from DataOut timeout while in ERL=0
> Increase iSCSI target dataout timeout due to failures in multi nodes

- src/assisted_test_infra/test_infra/controllers/node_controllers/zvm_controller.py
Fix following error:
if platform == consts.CPUArchitecture.S390X:
>           return ZVMController(controller_configuration, cluster_configuration)
E           TypeError: Can't instantiate abstract class ZVMController without an implementation for abstract methods 'destroy_network', 'get_cluster_network', 'set_per_device_boot_order'
when running download_iso test case.
> MULTIARCH-5289: download_iso fix issue when downloading iso for s390x

- src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
- src/assisted_test_infra/test_infra/helper_classes/cluster.py
- src/assisted_test_infra/test_infra/helper_classes/config/base_cluster_config.py
- src/assisted_test_infra/test_infra/helper_classes/config/base_entity_config.py
- src/tests/test_kube_api.py
- terraform_files/baremetal/main.tf
- terraform_files/baremetal/variables-libvirt.tf
This PR enables testing of user-managed LB with hosts on different subnets for both RESTAPI and k8s API.
This PR essentially facilitates testing for - https://github.com/openshift/assisted-service/pull/7204
> MGMT-19510: Enable automatic testing of user-managed load balancer using test-infra with hosts on different subnets

- src/assisted_test_infra/test_infra/controllers/iscsi_target_controller.py
Increase the keepalive time between client to target solves issue related to multinode installation Solve issue related to libvirt slow performance
Did not receive response to NOPIN on CID: 0, failing connection
> Add nopin_timeout to iSCSI installation

- terraform_files/baremetal/main.tf
- terraform_files/baremetal_host/main.tf
- terraform_files/baremetal_infra_env/main.tf
- terraform_files/none/main.tf
Bump Terraform Libvirt provider to `0.8.1` mainly to include https://github.com/dmacvicar/terraform-provider-libvirt/pull/945
> NO-ISSUE: Bump Terraform Libvirt provider to the latest version

- src/consts/consts.py
- src/triggers/default_triggers.py
master_count is used to set the total masters, same value as control_plane_count created auto trigger and updated the "enum" like class.
> Update control plane count from trigger

- src/assisted_test_infra/test_infra/helper_classes/cluster.py
Let test-infra find the common network for all hosts in the cluster which should contain the load balancer IP as well in order to avoid providing additional configuration for the load balancer cidr
> MGMT-19831: Let test-infra provide the machine network for vSphere umlb dynamically

- Makefile
- src/tests/test_targets.py
When running `make deploy_nodes` all the test methods that starting with `test_deploy_nodes` are executed causing some targets to create 2 clusters instead on one.
This PR changes the `test_target_deploy_nodes_oci` and `test_target_destroy_nodes_oci` tests
/cc @eifrach
> NO-ISSUE: Fix running two targets when running make deploy_nodes

- src/consts/olm_operators.py
This PR adds support for installing 3 new operators:
1. `Node Healthcheck Operator`
2. `Self Node Remediation`
3. `Fence Agents Remediation`
> MGMT-20164: Add NHO alongside its remediators

- src/assisted_test_infra/test_infra/helper_classes/cluster.py
static configuration should support case when no address assigned.
example:
interfaces:
- ipv4: auto-dns: false auto-gateway: false auto-routes: false dhcp: true  -----------> we can set it to false without ip for testing enabled: true
In case we dont have any address assigned format_host_from_config_mapping_file returns empty dictionary and validation fails.
> Fix ip static validations.

- src/consts/olm_operators.py
[MGMT-20216](https://issues.redhat.com//browse/MGMT-20216): Remove memory and CPU requirements
The assisted installer should not make any assumptions regarding the operator resource requirements unless those are specifically stated in official documentation. Nmstate operator has no such requirements.
> MGMT-20216: Remove nmstate operator memory and CPU requirements

- src/assisted_test_infra/test_infra/__init__.py
- src/assisted_test_infra/test_infra/helper_classes/base_cluster.py
- src/tests/base_kubeapi_test.py
- src/tests/base_test.py
- src/tests/test_kube_api.py
[MGMT-20256](https://issues.redhat.com//browse/MGMT-20256): removed importing the Nodes from test_infra module because it assumes that assisted-service is being deployed and test_infra module can be called before assisted-service deployment
> MGMT-20256: fix 'wait_for_api_readiness' timeout error

- README.md
- src/assisted_test_infra/test_infra/helper_classes/config/base_infra_env_config.py
- src/assisted_test_infra/test_infra/helper_classes/kube_helpers/infraenv.py
- src/tests/global_variables/env_variables_defaults.py
- src/tests/test_kube_api.py
Adds new environment variable `SET_INFRAENV_VERSION` that allows the openshift version to be set on the InfraEnv for tests.
> MGMT-20168: Allow osImageVersion to be set on InfraEnv

- src/assisted_test_infra/test_infra/controllers/node_controllers/adapter_controller.py
The apapter controller allows us to run node commands from cluster api. When cluster deleted we can not use adapter resources and we should handle failures when calling node.
In case cluster deleted or in cleanup due to error , the adpater will return empty resources.
> Baremetal adapter controller on cleanup

- src/assisted_test_infra/test_infra/helper_classes/cluster.py
- src/assisted_test_infra/test_infra/helper_classes/config/base_cluster_config.py
- src/consts/__init__.py
- src/tests/global_variables/env_variables_defaults.py
- src/triggers/default_triggers.py
Simplified MetalLB setup by removing the need to provide IPs (api_ip, ingress_ip) during installation.
Users can now enable MetalLB and configure IPs later, post-installation.
/cc @danmanor @eliorerz
> MGMT-14822: Add MetalLB operator

- scripts/deploy_ui.sh
The UI image is currently broken, and we don't have a use case for the UI in CI jobs
> NO-ISSUE: Avoid deploying the UI in CI jobs
