openshift/assisted-test-infra

Makefile
Hide cd bm-inventory error if folder is not yet existing
=> Hide cd bm-inventory error

discovery-infra/bm_inventory_api.py
This is not compatible with setting content-length
=> Do not use chunked read for S3 downloads

README.md
Added ROUTE53_SECRET and BASE_DNS_DOMAINS.
=> readme: updated OS params details

GUIDE.md, README.md
=> Add Install Guide

discovery-infra/start_discovery.py
Handle custom cluster name when 'base-dns-domains' is specified
(cluster_name + random_postfix).
=> discovery: custom cluster name when domain specified

discovery-infra/start_discovery.py
run black formatter on start_discovery.py
=> start_discovery: run black

.github/workflows/pre-commit.yml
Uses pre-commit github action as additional test for validating PR's
=> Use Precommit GitHub Action

scripts/run_minikube.sh
need to increase minikube memory in order to run prometheus & grafana
@ronniel1 @eranco74 please approve
=> increase minikube memory

README.md
Signed-off-by: Moti Asayag <masayag@redhat.com>
=> Update README with customized images OS params

.pre-commit-config.yaml, .yaspeller.json, GUIDE.md, README.md, scripts/test_ui.sh
=> Remove OS from line as we can do either RHEL or CentOS

.gitignore, README.md
Add Table of contents, fix section ordering (config table) and levels of sections for hierarchy
=> Add TOC, fix document ordering and levels for sections

README.md
Signed-off-by: Moti Asayag <masayag@redhat.com>
=> Update README with service repository variables

scripts/utils.sh
=> OCPBUGSM-16067 Agent failed to connect to service due to xinetd connection limit

scripts/install_environment.sh, scripts/utils.sh
Reset libvirtd only if needed (which in most cases not really needed).
No need to reset libvirt after add-port command.
=> Fixed bug where libvird is reset while other job was running

Makefile
Since it make more sense that it will be done there.
=> Makefile: Moved tf directory deletion from 'destroy' to 'destroy_nodes'

discovery-infra/day2.py, discovery-infra/start_discovery.py, scripts/assisted_deployment.sh
Added namespace to cluster name in set_dns and removed ui_cluseter_name.
=> MGMT-2242: fixed set dns for cluster name

discovery-infra/consts.py, discovery-infra/node_controlers/node_controler.py, discovery-infra/node_controlers/qe_vm_controler.py, discovery-infra/tests/base_test.py, discovery-infra/tests/conftest.py, discovery-infra/tests/test_cancel_and_reset.py, discovery-infra/utils.py
=> Added new test cancel reset test after boot

discovery-infra/add_triage_signature.py, discovery-infra/create_triage_tickets.py
Also added anther tool to add "signarures" to the triaging tickets.
Currently there is only one such signature - add hosts information.
More work should be done in order to be able to easily extend the
signatures, and also to add the signatures when creating the tickets
=> Added too to create jira ticket for triaging failed clusters.

discovery-infra/add_triage_signature.py, discovery-infra/create_triage_tickets.py
Added 2 new signatures:
- host extra details
- version information
=> triaging ticket signature improvements

README.md
I found that the table is long enough to make it a cumbersome trying to find a
specific variable name, so I sorted it.
Replaces #144
=> sorts table of environment variables in README

discovery-infra/assisted_service_api.py, discovery-infra/start_discovery.py
~~Requires https://github.com/openshift/assisted-service/pull/310~~
Merged
=> Add a call to the new endpoint for updating the discovery ignition

discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py, discovery-infra/tests/test_wrong_boot_order.py
list_nodes to return list of Host obj instead of dict
=> refactor list_nodes

discovery-infra/tests/test_general.py
Added a test for selecting hosts roles.
=> e2e: test_select_roles

discovery-infra/start_discovery.py, discovery-infra/utils.py
=> MGMT-2773 - add logs while waiting for CVO to become available

scripts/deploy_assisted_service.sh, scripts/deploy_ui.sh, scripts/ocp.sh
Used 'tee /dev/tty' for sending output to stdout while storing in a variable.
=> day2: display output of deploy process

discovery-infra/test_infra/controllers/node_controllers/host.py, discovery-infra/test_infra/helper_classes/cluster.py, discovery-infra/test_infra/utils.py, discovery-infra/tests/base_test.py, discovery-infra/tests/test_cancel_and_reset.py
Adding new method to get the bootstrap node
Adding new method to kill_installer
Adding new cancel reset e2e test
=> add cancel reset test on failed installation

discovery-infra/test_infra/helper_classes/cluster.py, discovery-infra/test_infra/utils.py, discovery-infra/tests/pytest.ini, discovery-infra/tests/test_cancel_and_reset.py
Refactor tests to use cluster obj
Added sanity mark (happy flow)
Finished uncompleted test
=> fix e2e tests

Makefile, scripts/deploy_assisted_service.sh, scripts/deploy_controller.sh, scripts/ocp.sh
- Added controller deployment to deploy_on_ocp_cluster target.
- Added deploy_controller.sh for invoking deploy_controller function on ocp.sh.
- Pass SERVICE_BASE_URL to service deploy (required for inventory-url
in the controller configmap).
=> MGMT-2465: day2 - deploy controller

Makefile, discovery-infra/day2.py, discovery-infra/ocp.py, discovery-infra/start_discovery.py, discovery-infra/utils.py, scripts/deploy_assisted_service.sh
=> MGMT-2837 - add day2 on ocp test flow

scripts/deploy_controller.sh
Service port on OCP cluster should be 7000.
=> MGMT-2465: fix port on deploy_controller

discovery-infra/tests/test_validations.py
Need to be able to run full regression from CI
=> Skip validation flow

discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py, discovery-infra/test_infra/controllers/node_controllers/node_controller.py, discovery-infra/test_infra/helper_classes/cluster.py, discovery-infra/tests/conftest.py, discovery-infra/tests/test_dhcp.py
Testing https://github.com/openshift/assisted-installer-agent/pull/92
=> MGMT-2219 Add unique vip hostname test

discovery-infra/test_infra/controllers/node_controllers/node.py, discovery-infra/test_infra/helper_classes/cluster.py, discovery-infra/test_infra/utils.py, discovery-infra/tests/pytest.ini, discovery-infra/tests/test_cancel_and_reset.py, discovery-infra/tests/test_validations.py, discovery-infra/tests/test_wrong_boot_order.py
- Adding 4 validations e2e tests
=> Adding validation e2e tests

discovery-infra/test_infra/utils.py, scripts/install_environment.sh
Since RHEL8.3 there was a downgrade to libcrypt-1.8.3
Further information on https://bugzilla.redhat.com/show_bug.cgi?id=1828681
Machines that were with lower version were patched with LIBVIRTD_ARGS
--listen flag. If a machine libvirt package got upgraded, we should
remove this flag (comment it).
libvirt is trying to use iptables since it was
started before firewalld.
Restarting libvirtd after firewalld.
Further explanation on dev-scripts PR openshift-metal3/dev-scripts#1170
There's a known bug for libvirt version 6.0.0 https://bugzilla.redhat.com/show_bug.cgi?id=1840307
When calling net-dhcp-leases from time to time the data isn't synced
Replaced to use xmldump output until upgrading libvirt version
=> Install libcrypt-1.8.5 and fix libvirtd upgrade 

discovery-infra/test_infra/utils.py
Previously, if we were pulling an image which required authentication,
we would fail when trying to execute `oc adm release info` unless
we had logged in with docker, before running.
This uses the pull secret env var to pull the image which should work
as we would need the same auth when deploying the cluster.
=> NO-ISSUE Handle auth when querying release info

discovery-infra/test_infra/assisted_service_api.py
In some cases the ISO does not download completely
This PR adds a retry to download the image if the size of the resultant image does not match the content length and raises a clear exception in the case the retry failed as well
=> Verifying ISO is downloaded completely

discovery-infra/test_infra/controllers/iptables.py, discovery-infra/test_infra/controllers/node_controllers/node.py, discovery-infra/test_infra/helper_classes/cluster.py, discovery-infra/test_infra/helper_classes/nodes.py, discovery-infra/tests/base_test.py
This PR adds an iptables controller and fixture in base_test.
This allows to add and remove iptables rules from within the tests based on node ips
=> adding iptables fixture and controller

discovery-infra/start_discovery.py, discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py, discovery-infra/test_infra/helper_classes/cluster.py, discovery-infra/test_infra/helper_classes/nodes.py, discovery-infra/test_infra/tools/tf_network_pool.json, discovery-infra/test_infra/utils.py, discovery-infra/tests/conftest.py
- Add environment variables
- Add IP protocol logic
This is a preparation to ipv6 test in another repo
/cc @tsorya 
/cc @empovit
=> MGMT-3341 - IPv6 changes for e2e tests

discovery-infra/start_discovery.py
=> Fix networks_names variable typo

Dockerfile.test-infra, Jenkinsfile.download_logs, discovery-infra/download_logs.py
Always chmod download_logs output_folder.
On build image - always upgrade the assisted-service-client package.
On Jenkins download_logs job - Add Init stage running image_build.
=> Add download_logs jobs improvements

discovery-infra/tests/base_test.py
Added a fixture for attaching disks / cleaning up after
=> MGMT-3292 - Added attach disk fixture

discovery-infra/tests/base_test.py, scripts/install_environment.sh
- Add port 3129 to firewall
/cc @nshidlin 
/cc @YuviGold
=> MGMT-3504 Move proxy_server fixture to base_test

README.md, discovery-infra/test_infra/utils.py, scripts/deploy_assisted_service.sh
=> Change DEPLOY_TARGET podman-localhost to onprem

scripts/install_environment.sh
sudo seems to have been accidentally left off the daemon restart in install_environment.sh
=> Add sudo to restart chrony daemon

discovery-infra/test_infra/consts.py, discovery-infra/test_infra/helper_classes/cluster.py
/cc @YuviGold @lalon4 @nshidlin 
Add wait for stages:
one including reboot stage
and second is passed reboot stage
=> Fixing reboot issue

discovery-infra/start_discovery.py
Mo need to wait for insufficient in case of single node
=> Adding support for single node in assisted service flow

scripts/install_environment.sh
=> Change cat to tee for sudo

discovery-infra/tests/base_test.py, terraform_files/baremetal/consolemodel.xsl, terraform_files/baremetal/main.tf
This PR:
- defines a console log file for VMs in maif.tf
- adds collection of console log files in the case of test failure
=> collect vm console logs

discovery-infra/test_infra/utils.py
The exception is missing from the logs.
=> Set log.exception for is_cvo_available exceptions

discovery-infra/test_infra/assisted_service_api.py, discovery-infra/test_infra/consts.py, discovery-infra/test_infra/helper_classes/cluster.py
Adding NTP validation timeout, and removing redundant PENDING_FOR_INPUT const
=> Adding enable host method

discovery-infra/test_infra/assisted_service_api.py, discovery-infra/test_infra/consts.py, discovery-infra/test_infra/helper_classes/cluster.py
This PR:
- adds generate_image method to cluster 
- add const `PROXY_SETTINGS_CHANGED`
=> Adding method to generate image in cluster

discovery-infra/tests/base_test.py
This PR adds:
- request argument to nodes fixture in order to set vm creation parameters at the test level
- modifies attach_disk fixture to support multiple disks
=> allowing setting node variables from test

discovery-infra/download_logs.py, discovery-infra/test_infra/logs_utils.py
=> MGMT-3693 Add wait loop for must-gather logs in download_logs

scripts/install_environment.sh
=> MGMT-3607: configure OS to enable IPv6 via sysctl

scripts/assisted_deployment.sh
=> MGMT-3722 Set next hop DNS server on host dnsmasq for IPv6

discovery-infra/bootstrap_in_place.py
=> MGMT-3726: use the new command for generation BIP ignition file

discovery-infra/test_infra/logs_utils.py, discovery-infra/tests/base_test.py
Used in tests to wait for controller and cause cluster error status
=> Add wait for controller method

discovery-infra/bootstrap_in_place.py, discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
/cc @tsorya @YuviGold 
A better solution will come in the future
=> MGMT-3790: fix deploy-ibip DNS entries

scripts/install_minikube.sh
=> NO-ISSUE: retry curl command when fetching oc

discovery-infra/test_infra/consts.py
Added an event const for minimal-iso and modified the current to full-iso.
=> MGMT-3336 consts: added event for minimal-iso

ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/boot_iso/defaults/main.yml, ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/boot_iso/tasks/dell.yml, ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/boot_iso/tasks/dell_idrac.yml, ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/boot_iso/tasks/dell_redfish.yml, ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/create_iso/defaults/main.yml, ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/host_iso/defaults/main.yml
Some small modifications needed to playbook due to latest AI changes and fixes.
=> Adding new variables and slight changes to playbook to incorp latest changes

ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/disconnected_registry/defaults/main.yml, ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/disconnected_registry/handlers/main.yml, ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/disconnected_registry/meta/main.yml, ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/disconnected_registry/tasks/disconnected_registry.yml, ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/disconnected_registry/tasks/main.yml, ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/disconnected_registry/templates/install-config-appends.j2, ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/disconnected_registry/tests/inventory, ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/disconnected_registry/tests/test.yml, ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/disconnected_registry/vars/main.yml, ansible-bm-install/playbook_assisted_installer_disconnected_registry.yml
Adding to the playbook the ability to create a one-off disconnected registry
=> Adding the ability to create a disconnected registry

README.md
=> NO-JIRA Update README with IPv6 flags and targets

README.md
The previous note was hardly noticable.
Signed-off-by: Alexander Chuzhoy <achuzhoy@redhat.com>
=> Emphasizing the note re not doing things from /root

discovery-infra/start_discovery.py, terraform_files/baremetal/main.tf
- Do not set machine CIDR in none-platform
- Enable second network on SNO
=> MGMT-3684 Do not set machine CIDR in none-platform

scripts/install_environment.sh
=> NO-ISSUE: use latest available libgcrypt version

discovery-infra/test_infra/consts.py, discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py, discovery-infra/test_infra/helper_classes/cluster.py, discovery-infra/test_infra/helper_classes/nodes.py, discovery-infra/tests/base_test.py, discovery-infra/tests/conftest.py
=> MGMT-3571 Changes for single node IPv6

scripts/install_minikube.sh
=> NO-ISSUE: retry on every error cURL has, even non-transient ones

discovery-infra/download_logs.py
API got broken on https://github.com/openshift/assisted-test-infra/pull/434
=> Call verify_logs_uploaded with check_oc param

scripts/deploy_assisted_service.sh
Matches https://github.com/openshift/assisted-service/pull/1034
=> MGMT-3959 Update OCP versions JSON before deployment

terraform_files/baremetal/limit_ipv6_dhcp_range.xsl, terraform_files/baremetal/main.tf
/cc @ronniel1 @ori-amizur
tell me if it's more understandable
=> NO-ISSUE: add documentation for the DHCP limiting via XSL transformer

scripts/deploy_assisted_service.sh
In addition, generate on prem environment after release image override
=> Update default_ocp_versions only if override image provided

discovery-infra/test_infra/consts.py, discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py, discovery-infra/test_infra/controllers/node_controllers/node.py, discovery-infra/test_infra/controllers/node_controllers/node_controller.py, discovery-infra/tests/base_test.py
This PR implement new methods to create new Network, create new Interface, and attach it to a single node.
=> Add new interface to VM

terraform_files/baremetal/main.tf, terraform_files/none/main.tf
/hold
/cc @eranco74 @romfreiman
=> MGMT-4096: add canary-openshift-ingress DNS entry on terraform to enable ingress operator full operation

discovery-infra/day2.py
Allow passing a proxy configuration to day 2 clusters.
If not present, it will be copied from the original day 1 cluster.
=> MGMT-3611 Pass proxy configuration for day 2 cluster

Jenkinsfile, Jenkinsfile.download_all_logs, Jenkinsfile.download_logs, Makefile, scripts/download_logs.sh
Support onprem and k8s logs with getting `ADDITIONAL_PARAMS` environment variable. i.e. `--must-gather`, `--download-all`, `--update-by-events`.
/cc @osherdp
=> MGMT-4100 Move download logs logic to download_logs.sh script

scripts/download_logs.sh
…vided
Fixes getting remote cluster logs without trying to use local minikube, that might not exist.
/cc @osherdp
=> MGMT-4100 Set local service url only if REMOTE_SERVICE_URL wasn't provided

discovery-infra/test_infra/helper_classes/cluster.py
=> MGMT-4156: wrap IPv6 address with square-brackets

scripts/deploy_assisted_service.sh
This reverts commit 92300735cb517482dfc88ee1c3d3fc17dfb7521b.
=> Revert "MGMT-3370: Allow running in kube api mode (#528)"

README.md
Document  on PULL_SECRET_FILE usage
=> docs(README.md): document on PULL_SECRET_FILE usage

discovery-infra/bootstrap_in_place.py
=> NO-ISSUE: use a newer rhcos image to handle usage of ignition version 3.2

discovery-infra/bootstrap_in_place.py, discovery-infra/test_infra/helper_classes/nodes.py
=> NO-ISSUE: allow operators status check errors be transient

Dockerfile.test-infra
=> NO-ISSUE: use curl instead of wget when installing terraform

discovery-infra/test_infra/utils.py
/cc @YuviGold @tsorya 
It's a bit of a more generalized solution than before.
/hold
=> NO-ISSUE: use PULL_SECRET env-var when doing 'oc adm release extract'

discovery-infra/tests/base_test.py
Adding the ability to enable\disable attach_disk teardown
=> Disable attach_disk teardown

Dockerfile.test-infra, scripts/download_logs.sh
Adding all events in namespace assisted-installer, to investigate eviction errors.
/hold
/cc @YuviGold @tsorya
=> NO-ISSUE: save events of each relevant pod on a separate file

discovery-infra/test_infra/logs_utils.py
=> NO-ISSUE fix sporadic read error in CI when opening controller tar

discovery-infra/test_infra/helper_classes/cluster.py
In order to write end to end tests for cnv we need ability to enable cnv operator.
Signed-off-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>
=> MGMT-4079 Set CNV

discovery-infra/test_infra/tools/static_network.py
/cc @yevgeny-shnaidman @empovit
=> Fixing route destitation for ipv6 static network configuration flow

discovery-infra/test_infra/logs_utils.py
/hold
dmesg and journal logs should be collected on all nodes in case of an error
=> MGMT-3463 collect full journal logs on error

discovery-infra/test_infra/logs_utils.py
This reverts commit bb4f9d2ca2712c3b8ecb48a77c88884e86972076.
=> Revert "MGMT-3463 collect full journal logs on error"

Makefile, discovery-infra/delete_nodes.py, discovery-infra/start_discovery.py, discovery-infra/test_infra/controllers/load_balancer_controller.py, discovery-infra/test_infra/controllers/nat_controller.py, discovery-infra/test_infra/helper_classes/cluster.py, scripts/install_environment.sh, terraform_files/none/main.tf
None platform additional changes
- Add ports 443 and 80 to libvirt firewall for none platform
- Make DNS queries local in terraform
- Make load balancer access workers for ports 80 and 443
- Add NAT iptables rules for none platform IPv4 since it is using route forwarding mode
@YuviGold 
@tsorya
=> MGMT-3420 None platform additional changes

discovery-infra/bootstrap_in_place.py
Bootstrap in place script node should have more resources to handle the e2e testing suite
This commit will be reverted in-case we see that this doesn't help
=> NO-ISSUE - Bootstrap-in-place node with more resources

discovery-infra/test_infra/helper_classes/cluster.py, discovery-infra/test_infra/logs_utils.py, discovery-infra/test_infra/utils.py
=> MGMT 3854 - e2e test to log info

discovery-infra/test_infra/helper_classes/kube_helpers.py
An Agent CRD will be created for each registered host. In order to start the
installation all agents must be approved.
=> MGMT-4624: Added Agent CRD

Makefile, discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py, discovery-infra/test_infra/helper_classes/cluster.py, discovery-infra/tests/conftest.py
…load_balancer target with test target
TerraformController now take the PLATFORM environment variable and copy the none terraform files accordingly 
https://issues.redhat.com/browse/MGMT-3335
=> MGMT-3335 - Add None Platform support 

discovery-infra/events.html
=> Add colors to the log level column in events file

discovery-infra/test_infra/helper_classes/kube_helpers/__init__.py, discovery-infra/test_infra/helper_classes/kube_helpers/agent.py, discovery-infra/test_infra/helper_classes/kube_helpers/base_resource.py, discovery-infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py, discovery-infra/test_infra/helper_classes/kube_helpers/common.py, discovery-infra/test_infra/helper_classes/kube_helpers/secret.py
Since it is a large file that will only get bigger,
it will be better to split it to a sub package.
=> NO-ISSUE: split kube helpers file

Jenkinsfile.download_logs
This script create triaging tickets for failed jobs, as marked in testgrid
=> Added call to create_testgrid_tickets.py to the download_logs job

scripts/install_environment.sh, skipper.yaml
=> NOISSUE: Updated skipper to v1.29.2

Makefile, discovery-infra/delete_nodes.py, discovery-infra/start_discovery.py, discovery-infra/test_infra/controllers/nat_controller.py, discovery-infra/test_infra/helper_classes/cluster.py
=> MGMT-4761 Clear all nat iptables rules when tearing down tests using user-managed-networking

discovery-infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py
and small cosmetics to cluster_deployment.py
=> NOISSUE: deploy_default_cluster_deployment with objects instead of dict

discovery-infra/test_infra/helper_classes/kube_helpers/agent.py
Since it may take a few seconds before key is created by
the operator.
In addition, small cosmetics and convention alignment.
=> NOISSUE: Agent - wait for status

.gitignore
=> NO-ISSUE ignore .env file to enable customization

Makefile
Set service replica count to 1 if kube-api is enabled
=> NO-ISSUE disable kube-api by default

discovery-infra/start_discovery.py, discovery-infra/test_infra/helper_classes/kube_helpers/__init__.py, discovery-infra/test_infra/helper_classes/kube_helpers/installenv.py, discovery-infra/test_infra/helper_classes/kube_helpers/nmstate_config.py
It's subject to changes, as work on the API is still on-going.
/cc @RazRegev 
/hold
=> MGMT-4870 Add nmstate via kube-api automation

discovery-infra/install_cluster.py, discovery-infra/start_discovery.py, discovery-infra/test_infra/kubeapi_utils.py
replace any rest api call to edit resources in assisted service
with matching kube-api call instead.
=> NOISSUE: remove any rest api call from kube api flow

discovery-infra/start_discovery.py
=> NO-ISSUE do not use an explicit kubeconfig path

discovery-infra/start_discovery.py, discovery-infra/test_infra/helper_classes/kube_helpers/__init__.py, discovery-infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py, discovery-infra/test_infra/helper_classes/kube_helpers/cluster_image_set.py, discovery-infra/test_infra/utils.py, scripts/deploy_assisted_service.sh
Includes required changes for testing functionality implemented in https://github.com/openshift/assisted-service/pull/1319:
* Added ClusterImageSet and ClusterImageSetReference
* Created a ClusterImageSet as part of execute_day1_flow.
* Defined OPENSHIFT_VERSIONS env var in deploy_assisted_service.
=> MGMT-4577 kube_helpers: Added ClusterImageSet class

README.md, discovery-infra/test_infra/helper_classes/nodes.py, discovery-infra/test_infra/utils.py, discovery-infra/tests/base_test.py, discovery-infra/tests/conftest.py, discovery-infra/tests/test_install.py
Test SNO and None platform given required environment variables using `make test` target
=> MGMT-4918 Support configurations for test-infra pytest

scripts/deploy_assisted_service.sh
Fixed check for ENABLE_KUBE_API env var on deploy_assisted_service
=> MGMT-5269 fix ENABLE_KUBE_API check on deploy service

discovery-infra/bootstrap_in_place.py, discovery-infra/day2.py, discovery-infra/delete_nodes.py, discovery-infra/download_logs.py, discovery-infra/install_cluster.py, discovery-infra/log_scrap.py, discovery-infra/oc_utils.py, discovery-infra/ocp.py, discovery-infra/start_discovery.py, discovery-infra/test_infra/__init__.py, discovery-infra/update_assisted_service_cm.py, discovery-infra/virsh_cleanup.py
Warn users while using discovery-infra scripts for the upcoming deprecation
=> MGMT-5189 - Add deprecation warning on pending deprecation scripts.

discovery-infra/test_infra/__init__.py
=> NO-ISSUE - Fix deprecation message on pytest execution

discovery-infra/start_discovery.py
/hold
/cc @YuviGold @filanov @tsorya
=> refactor kube-api flow a bit to remove non-needed if branch

discovery-infra/test_infra/helper_classes/cluster.py
=> Adding wait for cluster status

discovery-infra/test_infra/controllers/proxy_controller/proxy_controller.py
Move PROXY_USER and PROXY_USER_PASS to the class scope instead of the module scope
=> NO-ISSUE - Move PROXY_USER and PROXY_USER_PASS to class scope

discovery-infra/download_logs.py
/hold
Need to change on assisted-installer-deployment as well
=> NO-ISSUE fix typo of metadata file name

discovery-infra/bootstrap_in_place.py, discovery-infra/download_logs.py, discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py, discovery-infra/test_infra/utils.py
Adding a CLI option for gathering sosreport-like data via SSH.
/cc @eranco74 @tsorya
=> MGMT-5381 gather sosreport from nodes

discovery-infra/bootstrap_in_place.py, discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
=> NO-ISSUE fix gathering sosreport on ibip flow

discovery-infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py, discovery-infra/test_infra/helper_classes/kube_helpers/cluster_image_set.py, discovery-infra/test_infra/helper_classes/kube_helpers/common.py, discovery-infra/test_infra/helper_classes/kube_helpers/idict.py, discovery-infra/test_infra/helper_classes/kube_helpers/infraenv.py
PART of https://issues.redhat.com/browse/MGMT-5347
=> MGMT-5347 - Create IDict class for kube_helpers classes

discovery-infra/test_infra/helper_classes/kube_helpers/__init__.py, discovery-infra/test_infra/helper_classes/kube_helpers/agent.py, discovery-infra/test_infra/helper_classes/kube_helpers/base_resource.py, discovery-infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py, discovery-infra/test_infra/helper_classes/kube_helpers/cluster_image_set.py, discovery-infra/test_infra/helper_classes/kube_helpers/common.py, discovery-infra/test_infra/helper_classes/kube_helpers/infraenv.py, discovery-infra/test_infra/helper_classes/kube_helpers/nmstate_config.py, discovery-infra/test_infra/helper_classes/kube_helpers/secret.py
PART of https://issues.redhat.com/browse/MGMT-5347
=> MGMT-5347 - Fix PEP8 violations on kube_helpers 

discovery-infra/test_infra/helper_classes/cluster.py
Use isort and black to reformat cluster.py
=> NO-ISSUE - Fix PEP8 issues on cluster.py

README.md, discovery-infra/test_infra/helper_classes/kube_helpers/agent_cluster_install.py, discovery-infra/test_infra/utils/utils.py, discovery-infra/tests/test_kube_api.py
Add kube_api test from d/s to u/s
- Making more agentClusterInstall waiting more verbose.
- Set verify=False when getting ISO from HTTPS service.
=> MGMT-5274 Add test_kube_api suite including sno_ipv4 happy flow

Jenkinsfile, discovery-infra/test_infra/utils/utils.py, scripts/deploy_assisted_service.sh
Matches https://github.com/openshift/assisted-service/pull/1713
=> MGMT-6466 Move default_ocp_versions.json to data directory

discovery-infra/test_infra/helper_classes/cluster.py
Controller already exists in cluster.nodes.controller, No need to pass it to any function.
=> MGMT-5453 - Use Nodes controller in cluster.py instead of passing it to the function

discovery-infra/delete_nodes.py, discovery-infra/start_discovery.py, discovery-infra/test_infra/controllers/iptables.py, discovery-infra/test_infra/controllers/nat_controller.py, discovery-infra/test_infra/helper_classes/nodes.py, discovery-infra/tests/base_test.py
- Fix PEP8 violations.
- Change NatController class to be none static class
- Nodes class handles the Nat and the Assets
=> MGMT-6534 - Allow create instances form NatController class

discovery-infra/resources/man_sosreport.sh
/cc @YuviGold @tsorya @ori-amizur
=> gather bootkube, kubelet and crio service logs

discovery-infra/log_scrap.py
Add a field to stashing that is the inventory URL. 
this will give the option to filter by the data source
=> NO-ISSUE inventory_url to ES for source filtering

discovery-infra/test_infra/utils/logs_utils.py
- The utility checks that logs from the input category
(worker, master, bootstrap) were not uploaded
- This utility is needed for a fix in the log tests
that currently check this is an implicit way that
is unreliable
=> NO-ISSUE utility to check if logs are not uploaded

Makefile, discovery-infra/start_discovery.py, discovery-infra/test_infra/controllers/load_balancer_controller.py, discovery-infra/test_infra/controllers/nat_controller.py, discovery-infra/test_infra/helper_classes/cluster.py, discovery-infra/test_infra/helper_classes/nodes.py, discovery-infra/tests/base_test.py
The network_conf attribute is not part of the base controller but implemented only for the terraform controller
Nodes class shouldn't deal with the networking because it's not related so extracting this code to the BaseTest class
=> MGMT-5276 No network_conf attribute MGMT-6805 None platform test has failed 

Dockerfile.test-infra, discovery-infra/install_cluster.py, discovery-infra/start_discovery.py, discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py, discovery-infra/test_infra/tools/terraform_utils.py, terraform_files/baremetal/main.tf, terraform_files/baremetal/terraform.tfvars.json, terraform_files/baremetal/variables-libvirt.tf, terraform_files/none/terraform.tfvars.json
=> Add assisted service DNS record for libvirt networks to be resolved to SNO ip or ingress VIP

discovery-infra/test_infra/helper_classes/nodes.py, discovery-infra/test_infra/utils/utils.py
=> NO-ISSUE - Fetch all masters from primary and secondary networks when IPv6 is set with None platform.

scripts/assisted_deployment.sh
Revert "Add localhost nameserver on set_dns (#878)"
This reverts commit 81245f2c7147243622f3277a3f1fd0d25ec03cec.
Revert "Set main host IP instead of localhost 127.0.0.1 for set_dns (#883)"
This reverts commit a8e5cd4100c7b298e48152d5711916babac9a754.
=> revert localhost nameserver

Makefile
Fix case when DEBUG is not defined
=> NO-ISSUE - Fix vscode debug or statement

discovery-infra/tests/base_test.py
Prevent case where `prepare_nodes` is failing and `_nodes` is not defined on teardown
=> NO-ISSUE - Rearrange nodes data on get nodes fixture

discovery-infra/test_infra/tools/assets.py
Set network parameters assets properly for IPv6, i.e
machine_cidr6, provisioning_cidr6.
=> MGMT-7059: Fixed assets for IPv6

discovery-infra/start_discovery.py, discovery-infra/test_infra/helper_classes/kube_helpers/common.py, discovery-infra/tests/base_test.py, discovery-infra/tests/test_kube_api.py
=> MGMT-6648:CRs shouldn't be deleted if TEST_TEARDOWN=false

discovery-infra/log_scrap.py
* Add grace of 1 sec for ES doc to flush
* Add host data to metadata
* Add processed props field to event doc and remove post log
=> NO-ISSUE Fixes for event ES collector

discovery-infra/install_cluster.py, discovery-infra/test_infra/consts/consts.py, discovery-infra/test_infra/helper_classes/kube_helpers/agent.py
Before starting the agent cluster install, check if the agent's status is Validated, ReadyForInstallation, and Installed.
Ref: https://issues.redhat.com/browse/MGMT-6660
=> MGMT-6660: Check agent statuses

Makefile, discovery-infra/test_infra/helper_classes/cluster.py, scripts/assisted_deployment.sh, skipper.yaml, terraform_files/baremetal/main.tf, terraform_files/baremetal/variables-libvirt.tf, terraform_files/none/main.tf, terraform_files/none/variables-libvirt.tf
- Created DNS forwarding file(s) in /etc/NetworkManager/dnsmasq.d by using terraform.
=> MGMT-7115: When running test_parallel, VIPs DNS cannot be resolved from host

discovery-infra/test_infra/helper_classes/cluster.py
- In this case set API VIP in terraform after cluster is ready for installation
/cc @YuviGold
=> MGMT-7124: Update API VIP in pytest flow when using vip DHCP

Makefile, scripts/install_environment.sh
Creates correct path so we do not see issues when running load_balancer container
=> Fix path for nginx config files

discovery-infra/test_infra/helper_classes/cluster.py, discovery-infra/test_infra/helper_classes/nodes.py
Print cluster and nodes config on `prepare_for_installation`
=> NO-ISSUE - Add log on prepare_for_installation

discovery-infra/logger.py, discovery-infra/test_infra/helper_classes/cluster.py
Fix logs to use `SensitiveFormatter` on cluster.  Add support to `SensitiveFormatter` for filtering object printing.
=> MGMT-7151 - Fix logs to use SensitiveFormatter on cluster. 

discovery-infra/test_infra/controllers/proxy_controller/proxy_controller.py, discovery-infra/tests/base_test.py
=> NO-ISSUE - Fix proxy to support ipv4 addresses

discovery-infra/test_infra/helper_classes/cluster.py
=> MGMT-7156: Set DNS configuration for single node pytest flow

discovery-infra/test_infra/helper_classes/cluster.py
=> NO-ISSUE: Fix DNS setting for IPv6 flow

discovery-infra/events.html
=> NO-ISSUE: add colors for critical level event

ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/boot_iso/tasks/main.yml, ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/boot_iso/tasks/ovirt.yml, ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/clean/defaults/main.yml, ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/clean/meta/main.yml, ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/clean/tasks/main.yml, ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/clean/tasks/ovirt.yml, ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/host_iso/tasks/main.yml, ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/host_iso/tasks/ovirt.yml, ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/validations/tasks/main.yml, ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/validations/tasks/ovirt.yml, ansible-bm-install/inventory/hosts_without_os.sample, ansible-bm-install/requirements.yml
Add support to run oVirt VMs on 'assisted_installer' ansible collection.
=> NO-ISSUE: Support oVirt on ansible collections

discovery-infra/download_logs.py
=> MGMT-7202: Collect custom manifests yaml when downloading cluster logs

.github/dependabot.yml
=> Update dependabot.yml to support docker as well

discovery-infra/download_logs.py
=> MGMT-7291: Collect degraded clusters

discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py, discovery-infra/test_infra/controllers/node_controllers/node_controller.py, discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py, discovery-infra/test_infra/controllers/node_controllers/vsphere_controller.py, discovery-infra/test_infra/helper_classes/cluster.py, discovery-infra/test_infra/helper_classes/cluster_host.py, discovery-infra/test_infra/helper_classes/nodes.py, discovery-infra/test_infra/utils/global_variables/global_variables.py, discovery-infra/test_infra/utils/network_utils.py, discovery-infra/tests/base_test.py, discovery-infra/tests/test_kube_api.py
support vsphere dhcp vip allocation mode
move dns libvirt specific code to the controllers
=> Mgmt 7153 vsphere platform configure networking

discovery-infra/tests/base_test.py, discovery-infra/tests/test_targets.py
Makefile targets will be handled in different PR
/cc @michaellevy101 @YuviGold
=> MGMT-6417- Add pytest deploy_nodes target

discovery-infra/tests/test_targets.py
Prevent running `test_install_with_deploy_nodes` when running `test_install`
/cc @YuviGold
=> NO-ISSUE - Rename target tests names

discovery-infra/test_infra/consts/consts.py
=> NO-ISSUE - Bump default openshift version to 4.8

discovery-infra/test_infra/consts/consts.py
This PR address this failure: https://auto-jenkins-csb-kniqe.apps.ocp4.prod.psi.redhat.com/job/ocp-assisted-installer-virt/2436/testReport/junit/test_events/TestEvents/Run_assisted_installer_Functional_API_Tests___test_events_e2e/
=> Update CVO event message

Makefile
=> Update deploy_nodes makefile target to use the new pytest workflow

discovery-infra/tests/base_test.py
=> NO-ISSUE - Fix missing nodes prevent creating cluster on some cases

discovery-infra/download_logs.py
/cc @YuviGold @eliorerz 
/hold
=> NO-ISSUE: fix keyword argument of Controller c'tor

Jenkinsfile.download_logs
=> Merge Jenkinsfile.download_logs create tickets commands under a single stage

discovery-infra/download_logs.py
Collect custom manifests json when downloading cluster logs
=> Add custom manifest new format file

discovery-infra/test_infra/helper_classes/config/base_entity_config.py, discovery-infra/test_infra/helper_classes/config/base_infra_env_config.py, discovery-infra/test_infra/helper_classes/config/cluster_config.py
=> MGMT-7727 - Remove redundant cluster and entity config properties

discovery-infra/tests/base_test.py
- Fix base test prepare_nodes fixtures.
- PEP8 fixes.
=> NO-ISSUE - Fix base test prepare_nodes fixtures.

discovery-infra/bootstrap_in_place.py, discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py, discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py, discovery-infra/test_infra/helper_classes/cluster.py, discovery-infra/test_infra/helper_classes/config/base_entity_config.py, discovery-infra/test_infra/helper_classes/config/base_infra_env_config.py, discovery-infra/test_infra/helper_classes/config/cluster_config.py, discovery-infra/test_infra/helper_classes/infra_env.py, discovery-infra/test_infra/utils/cluster_name.py, discovery-infra/test_infra/utils/entity_name.py, discovery-infra/test_infra/utils/infra_env_name.py, discovery-infra/test_infra/utils/kubeapi_utils.py, discovery-infra/tests/config/global_configs.py
=> MGMT-7731 -	Rearrange entities operations

discovery-infra/test_infra/assisted_service_api.py
Remove invalid character from create_infra_env
/cc @YuviGold @tsorya
=> NO-ISSUE - Fix PEP8 violations on assisted_service_api.py.

discovery-infra/test_infra/helper_classes/config/controller_config.py, discovery-infra/test_infra/utils/global_variables/env_variables_defaults.py, discovery-infra/test_infra/utils/global_variables/global_variables.py, discovery-infra/tests/base_test.py
Rename _EnvVariablesUtils to _EnvVariablesDefaults
=> NO-ISSUE - Make _EnvVariablesUtils singleton.

README.md
=> NO-ISSUE: readme update

Dockerfile.test-infra, Makefile, discovery-infra/test_infra/consts/consts.py, discovery-infra/test_infra/utils/utils.py, scripts/deploy_assisted_service.sh, scripts/install_environment.sh, scripts/test_ui.sh, scripts/utils.sh, skipper.yaml
upgrade podman to 3.2.3 and start podman socket
upgrade skipper to the latest version
work on skipper with podman-remote only
=> MGMT-7173: podman support

Dockerfile.test-infra, Makefile, discovery-infra/test_infra/consts/consts.py, discovery-infra/test_infra/utils/utils.py, scripts/deploy_assisted_service.sh, scripts/install_environment.sh, scripts/test_ui.sh, scripts/utils.sh, skipper.yaml
This reverts commit f4d6c4847b02b1deb803cefa106d8c3ee45f49be.
=> Revert "MGMT-7173: podman support (#1101)"

scripts/deploy_assisted_service.sh
kube-api flow requires only the OS images list (instead of openshift_versions map).
Since assisted-service is using defaults values if OS_IMAGES is missing,
pass empty objects for OPENSHIFT_VERSIONS and RELEASE_IMAGES.
=> MGMT-7786: remove openshift_version in kube-api flow

discovery-infra/test_infra/assisted_service_api.py, discovery-infra/test_infra/consts/consts.py, discovery-infra/test_infra/controllers/node_controllers/node_controller.py, discovery-infra/test_infra/helper_classes/kube_helpers/agent.py, discovery-infra/test_infra/helper_classes/kube_helpers/infraenv.py, discovery-infra/test_infra/utils/entity_name.py, discovery-infra/test_infra/utils/utils.py, discovery-infra/tests/base_test.py, discovery-infra/tests/test_kube_api.py, pyproject.toml
See individual [commits](https://github.com/openshift/assisted-test-infra/pull/1098/commits) for change descriptions
There's @YuviGold commit to make the regular kubeapi tests work. Ignore it for now until his PR is merged
=> MGMT-7523 - Added initial kube-api late binding test

discovery-infra/test_infra/consts/consts.py
Remove unused vars from consts.py
/cc @osherdp
/cc @eliorerz
=> NO-ISSUE: remove reduntant consts

Dockerfile.test-infra
=> NO-ISSUE: fix default python version used

.github/workflows/pre-commit.yml, .pre-commit-config.yaml, Makefile, isort.cfg
=> MGMT-4990 - Add linter for creating uniform styling conventions

scripts/install_minikube.sh
Trying to solve those kind of problems:
```
Installing arkade...
sh: line 1: syntax error near unexpected token `newline'
sh: line 1: `<!DOCTYPE html>'
```
(taken from https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-service/2809/pull-ci-openshift-assisted-service-master-e2e-metal-assisted-multi-version/1451159569270050816)
/cc @eliorerz 
/hold
=> NO-ISSUE: trying to retry curl request for arkade installation code

discovery-infra/download_logs.py, discovery-infra/junit_log_parser.py, discovery-infra/logger.py, scripts/download_logs.sh
=> MGMT-8087 - Show service logs failures on PROW spyglass

Makefile, scripts/install_environment.sh
Using the externally provided image: https://quay.io/repository/odepaz/dynamic-load-balancer?tab=info
/cc @yevgeny-shnaidman @tsorya 
/hold
=> NO-ISSUE: use an external image for dynamic load balancing

discovery-infra/test_infra/assisted_service_api.py
/cc @nshidlin @osherdp @eliorerz
=> Fix download kubeconfig-noingress

discovery-infra/test_infra/consts/__init__.py, discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py, discovery-infra/test_infra/helper_classes/cluster.py, discovery-infra/test_infra/helper_classes/entity.py, discovery-infra/test_infra/helper_classes/infra_env.py, discovery-infra/tests/base_test.py, discovery-infra/tests/test_e2e_install.py
/cc @osherdp @nshidlin @tsorya
=> MGMT-7990 - Unite test-infra Cluster and InfraEnv objects under same base object

discovery-infra/tests/config/global_configs.py
=> NO-ISSUE - Fix empty `entity_name` when `cluster_name` is already set

discovery-infra/test_infra/helper_classes/nodes.py
=> NO-ISSUE - Set `wait_for_networking` as best effort

discovery-infra/junit_log_parser.py
Some logs has different format then the service logs. This fix also parse the leader election logs that exist on the service log
=> NO-ISSUE - parse leader election logs to junit report

discovery-infra/test_infra/assisted_service_api.py, requirements.txt
=> MGMT-8176 - Show service events failures on PROW spyglass

discovery-infra/test_infra/utils/logs_utils.py
/cc @lalon4 @osherdp @eliorerz
=> Fix for logs test on V1

OWNERS
=> remove yuval from approver list

Makefile, discovery-infra/log_scrap.py, discovery-infra/monitoring/docker-compose.yml, discovery-infra/monitoring/process.py, requirements.txt
This reverts commit ace571f3fb68c1db1f252c5648beadd0a6b14903.
/cc @michaellevy101
=> Revert "NO-ISSUE: remove all elasticsearch-related code (#1237)"

Makefile
This will remove the load balancer container on some more cases which I've encountered.
@tsorya @eranco74
=> remove load-balancer container even if it stopped

scripts/install_minikube.sh
Fail the script in upon first command that fail
(except commands that are part of the test following the if or elif reserved words, or part of any command executed in a '&&' or '||' pipeline)
=> NO-ISSUE: Retry to download minikube in case of failure

discovery-infra/test_infra/utils/utils.py
=> MGMT-8529 - Raise exception on ISO download failure

scripts/utils.sh
=> NO-ISSUE - Fix failing download_logs job due to unbound PYTHONPATH

Makefile
Remove addressing test full path during CI.
e.g. https://github.com/openshift/release/blob/745a5b845211206555230dacda43a3f4ac993414/ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml#L645
/cc @osherdp
=> NO-ISSUE - Remove project path dependency from CI

Makefile
=> NO-ISSUE - Fix redundant quotes on PYTHONPATH and PATH causing jobs to fail

src/assisted_test_infra/test_infra/helper_classes/hypershift.py, src/tests/test_kube_api.py
Hypershift require 2 nodes to be happy
=> MGMT-8602: Updated capi test to add 2 worker nodes

scripts/download_logs.sh, src/junit_log_parser.py
=> MGMT-8666 - Fix onprem logs destination in prow

src/assisted_test_infra/test_infra/helper_classes/cluster.py, src/assisted_test_infra/test_infra/helper_classes/infra_env.py, src/tests/base_test.py
=> MGMT-8520 - Clear infraenv unused resources on test teardown

scripts/setup_capi_provider_agent_env.sh
Update hypershift default image to use quay.io
Update the setup capi env script to wait for hypershift ready status
=> Mgmt 8845 Setup capi env should wait for HyperShift to be ready

src/junit_log_parser.py
Currently, errors on assisted-service logs are shown as separate JUNIT test-case, causing PROW to "split" each test case to new row under `Flaky` section (multiple entries in the Flaky table)
Here instead of 17 lines of failures on `github.com/openshift/assisted-service/internal/controller/controllers.(*ClusterDeploymentsReconciler).Reconcile` with the error `error setting owner reference`, we can see it under single table entry (as single string) without the need to expand multiple entries.
=> MGMT-8363 - Join flaky tests results on prow spyglass

scripts/setup_capi_env.sh, src/assisted_test_infra/test_infra/helper_classes/hypershift.py
Also adds a space to the hypershift create command
=> Unbound variable

scripts/download_logs.sh
Try to look for the namespace with the pod name the provider get in case it's installed by Hypershift
Note that if this the capi-provider runs as part of Hypershift control plane
we will collect the logs of all the pods running as part of the
Hypershift control plane as well
=> NO-ISSUE: Handle case where download_log.sh fail to find the capi-provider namespace

src/consts/olm_operators.py
Signed-off-by: Rewant Soni <resoni@redhat.com>
=> MGMT-7230: Add resource requirement for ODF operator

scripts/download_logs.sh
This should allow us to better understand what happened in case capi_test fails
=> NO-ISSUE: Added few CRs to the CAPI_PROVIDER_CRS list in download_logs.sh

src/assisted_test_infra/test_infra/helper_classes/kube_helpers/infraenv.py, src/tests/base_kubeapi_test.py, src/tests/base_test.py, src/tests/test_kube_api.py
Reorganize test_kube_api.py file. Remove duplicated code and add type hint annotation.
/cc @osherdp
=> NO-ISSUE - Reorganize test_kube_api.py file and remove duplicated code

scripts/setup_capi_env.sh
This change is needed due to recent changes made in HyperShift build job
https://github.com/openshift/release/pull/25438/files
=> MGMT-8998: Updated default HYPERSHIFT_IMAGE to quay.io/hypershift/hypershift-operator:latest

src/service_client/logger.py
=> NO-ISSUE - Add colors to logging

.ci-operator.yaml, Dockerfile.assisted-test-infra, Makefile, discovery-infra/test_infra/consts/consts.py, discovery-infra/tests/conftest.py, scripts/install_environment.sh
Backport of:
- https://github.com/openshift/assisted-test-infra/pull/1255
- https://github.com/openshift/assisted-test-infra/pull/1410
- https://github.com/openshift/assisted-test-infra/pull/1258
- https://github.com/openshift/assisted-test-infra/pull/1348
- https://github.com/openshift/assisted-test-infra/pull/1173 
- https://github.com/openshift/assisted-test-infra/pull/1269
- https://github.com/openshift/assisted-test-infra/pull/1198
- https://github.com/openshift/assisted-test-infra/pull/1372
=> [release-ocm-2.4] MGMT-9102: Change the base image the same as in master

src/tests/test_e2e_install.py
=> NO-ISSUE - Remove static-ip from networking job

discovery-infra/test_infra/consts/consts.py, discovery-infra/test_infra/helper_classes/kube_helpers/agent.py, discovery-infra/test_infra/helper_classes/kube_helpers/common.py, discovery-infra/test_infra/utils/entity_name.py, discovery-infra/test_infra/utils/kubeapi_utils.py, discovery-infra/tests/base_kubeapi_test.py, discovery-infra/tests/base_test.py, discovery-infra/tests/test_kube_api.py, scripts/install_environment.sh
Partial backport of:
- https://github.com/openshift/assisted-test-infra/pull/1389
- https://github.com/openshift/assisted-test-infra/pull/1379
- https://github.com/openshift/assisted-test-infra/pull/1286
- https://github.com/openshift/assisted-test-infra/pull/1245
Waiting for https://github.com/openshift/assisted-service/pull/3279
/cc @osherdp @tsorya
=> [release-ocm-2.4 ] MGMT-9102: Backport kube-api test

Makefile, discovery-infra/test_infra/assisted_service_api.py
=> MGMT-9102: fix kubeapi client default value

Makefile
=> [release-ocm-2.4] NO-ISSUE - Change parallel kube api job to be single threaded

Makefile
=> NO-ISSUE - Change pytest default workers count to 3

src/assisted_test_infra/test_infra/helper_classes/cluster.py, src/consts/consts.py
Deleting wait_for_event as it not being used anymore by kni repo.
We use events_handler fixture instead
=> Support cluster & infra-env & hosts events

Makefile
Backport of https://github.com/openshift/assisted-test-infra/pull/1197 
/cc @osherdp @lranjbar
=> [release-ocm-2.4] MGMT-9102: Backport - Add logic to detect if running in Openshift CI assisted-service PR

requirements.txt
=> Bump junit-report v0.2.5

src/assisted_test_infra/test_infra/helper_classes/cluster.py
=> add get_preflight_requirements to cluster

src/assisted_test_infra/test_infra/helper_classes/cluster.py, src/assisted_test_infra/test_infra/helper_classes/infra_env.py, src/tests/base_test.py
=> NO-ISSUE - Fix cluster and infra_env object cleanup

packer_files/vsphere_centos_template/centos-config/centos8-ks.cfg, packer_files/vsphere_centos_template/sources.pkr.hcl, packer_files/vsphere_centos_template/variables.pkr.hcl
Updating Centos8 to Centos8 stream mirror
Support connecting using ssh key
Support bastion ssh connection for testing (The vsphere env isn't exposed to the world)
=> VSphere Centos8 packer improvement

src/assisted_test_infra/download_logs/download_logs.py, src/service_client/assisted_service_api.py
For better debugging, adding infraenv events collection.
=> Download infra-env events log

src/assisted_test_infra/test_infra/helper_classes/config/base_config.py, src/triggers/default_triggers.py
=> NO-ISSUE - Fix OVNKubernetes job failure

src/tests/base_kubeapi_test.py, src/tests/test_kube_api.py
=> MGMT-9268: Fix kube-api conformance tests are failing

src/assisted_test_infra/test_infra/helper_classes/infra_env.py
=> add update_static_network_config to infra_env

scripts/install_minikube.sh
- Update `arkade` domain https://github.com/alexellis/arkade/commit/d7d1e59e18663c74ae538270cc3b4d9b3a637c24
- Fail setup on arkade installation failed 
/cc @osherdp
=> NO-ISSUE - Update `arkade` domain

Makefile, discovery-infra/test_infra/utils/global_variables/global_variables.py, discovery-infra/test_infra/utils/utils.py, discovery-infra/tests/base_kubeapi_test.py, discovery-infra/tests/test_kube_api.py
- Remove default openshift version from configurations.
- Set CI flag to true as default
/cc @osherdp
=> [release-ocm-2.4] MGMT-9197 - Fix kubeapi test

Makefile
Reverting https://github.com/openshift/assisted-test-infra/pull/1469 back to ocpmetal
/cc @eliorerz
=> NO-ISSUE - Go back to ocpmetal service index

src/assisted_test_infra/test_infra/helper_classes/cluster.py
Adding wait for cluster to be installing
=> NO-ISSUE: fail earlier in case prepare for installation failed

src/triggers/default_triggers.py
=> NO-ISSUE - Add ODF trigger

src/assisted_test_infra/test_infra/__init__.py, src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py, src/assisted_test_infra/test_infra/helper_classes/config/__init__.py, src/assisted_test_infra/test_infra/helper_classes/config/vsphere_config.py, src/tests/base_test.py, src/tests/config/__init__.py, src/tests/config/global_configs.py
- Fix vsphere controller not implementing all abstract methods
- Rename vsphere controller to match the configurations naming convention
/cc @michaellevy101
=> NO-ISSUE - Fix vsphere controller not implementing all abstract methods.

scripts/install_minikube.sh
=> NO-ISSUE - Remove unused downloaded executable

src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
=> NO-ISSUE: Increase libvirt wait for machine IP timeout from 360 to 600

src/tests/base_test.py
Add more fixtures to JUNIT report 
/cc @osherdp
=> NO-ISSUE - Add junit test cases to some base fixtures

Dockerfile.assisted-test-infra
Add retry to curl commands during image-build process 
/cc @osherdp
=> MGMT-9765 - Fix assisted-test-infra image build failure during CI

src/junit_log_parser.py
Test cases and suites random names are causing explosive test growth in tooling, sippy and more
/cc @osherdp
=> NO-ISSUE - Fix random tests names while parsing assisted logs and events

src/assisted_test_infra/test_infra/utils/utils.py, src/tests/global_variables/env_variables_defaults.py
=> NO-ISSUE - Update openshift default version to 4.10

scripts/pull_dockerfile_images.sh
- Fix missing images when using multi-stage builds
- Make logs more clear
- Sleep between retries
- Ignore images aliases using regex
/cc @adriengentil
=> MGMT-9852 - Fix image-pulling script

requirements.txt, src/service_client/assisted_service_api.py
Fixed random cluster events suite and test case names
Partially fixed on https://github.com/openshift/assisted-test-infra/pull/1567
/cc @osherdp
=> NO-ISSUE - Fix cluster events random suite/test names

Makefile, scripts/pull_dockerfile_images.sh
=> NO-ISSUE - Remove pull-always flag from PULL_PARAMS

packer_files/vsphere_centos_template/centos-config/centos8-ks.cfg, packer_files/vsphere_centos_template/variables.pkr.hcl
=> Allocating all the storage to the root filesystem

terraform_files/vsphere/main.tf
The vsphere folder is created during a perior step in the CI workflow
=> Pre-existing vSphere folders should not be created

Makefile
=> NO-ISSUE: [release-ocm-2.4]: Change catalog image to one that's actually being updated

src/triggers/default_triggers.py, src/triggers/env_trigger.py, src/triggers/olm_operators_trigger.py
Add the ability to not just activate trigger on "equal" condition, but also define the condition as lambda 
/cc @osherdp
=> MGMT-9555 - Add more complex triggers conditions comparison methods

src/assisted_test_infra/test_infra/helper_classes/cluster.py
=> NO-ISSUE - Add type hint annotations for set_disk_encryption

requirements.txt, src/service_client/assisted_service_api.py
Manual backport of https://github.com/openshift/assisted-test-infra/pull/1618
/cc @vrutkovs  @osherdp
=> NO-ISSUE - junit: don't add cluster_id to class names

src/tests/conftest.py
Fail the test if missing pull secret 
@osherdp
=> NO-ISSUE - Assert if no PULL_SECRET provided

GUIDE.md, README.md
Add documentation for adding a new e2e test to test-infra
/cc @eliorerz
=> MGMT-10112 - Add info about how to add a new e2e test

src/consts/consts.py, src/tests/global_variables/env_variables_defaults.py
=> NO-ISSUE - Add 4.11 to available openshift versions

src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py, src/assisted_test_infra/test_infra/utils/utils.py, src/consts/resources.py
Used to download the cluster log files from the installed cluster by the gather step of the vsphere CI workflow
=> Update etc hosts file append a mapping to the api and ingress vips

Dockerfile.assisted-test-infra
Updating to latest available Terraform version v1.2.2.
=> bump terraform to v1.2.2

scripts/install_environment.sh, src/assisted_test_infra/test_infra/controllers/__init__.py, src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py, src/assisted_test_infra/test_infra/controllers/tang_controller/tang_controller.py, src/assisted_test_infra/test_infra/helper_classes/cluster.py, src/assisted_test_infra/test_infra/helper_classes/config/cluster_config.py, src/consts/consts.py, src/consts/resources.py, src/tests/base_test.py
Signed-off-by: Ido Ovadia <iovadia@redhat.com>
=> Adding support for tang server for encryption tests

src/assisted_test_infra/test_infra/controllers/node_controllers/node_controller.py, src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py, src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py, src/assisted_test_infra/test_infra/helper_classes/cluster.py, src/assisted_test_infra/test_infra/utils/utils.py, src/consts/resources.py, src/tests/test_kube_api.py, terraform_files/baremetal/main.tf, terraform_files/baremetal/variables-libvirt.tf, terraform_files/baremetal_infra_env/main.tf, terraform_files/baremetal_infra_env/variables-libvirt.tf, terraform_files/none/main.tf, terraform_files/none/variables-libvirt.tf
Remove dnsmasq configuration file creation duplication
=> Add api and ingress vips mapping to the skipper container /etc/host file

src/assisted_test_infra/test_infra/helper_classes/cluster.py
adds a function to modify network type of cluster (SDN,OVN)
function needed to support kni tests modifying  network type
=> NO-ISSUE - Add function to modify cluster network type

Jenkinsfile.download_logs
=> MGMT-10849: Install Insights rules from private RHT repository

Jenkinsfile.download_logs
=> Use pip3 instead of pip in Jenkins job

OWNERS
/cc @gamli75 @adriengentil @omertuc
=> adding some more approvers to the list

src/assisted_test_infra/test_infra/controllers/proxy_controller/proxy_controller.py
=> NO-ISSUE - Fix missing constructor arguments on proxy controller.

requirements.txt
It's already being defined above
=> Remove redundant dependency

scripts/install_environment.sh
The rootfs is now downloaded from the assisted-image-service instead of
internet.
As a consequence, when we try to setup a cluster located out of the hub
cluster network, the machine that boots the assisted ISO fails to
retrieve the rootfs because libvirt denies the traffic between guest
networks.
This change sets up a hook in libvirt that drops the rules denying
forwarded traffic between guest networks.
Here is a job failing because of this issue:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-assisted-service-master-edge-e2e-metal-assisted-kube-api-late-binding-single-node-periodic/1544506948760637440
=> NO-ISSUE: allow cross network traffic

Makefile
/cc @osherdp @danielerez 
FYI @lalon4
=> NO-ISSUE - Clear previous tests images and logs only if `TEST_TEARDOWN!=false`

scripts/install_environment.sh, scripts/setup_capi_env.sh
This should enable routing between guests without losing accept rules
=> NO-ISSUE: remove reject rules from LIBVIRT_FWI chain instead of flushing the chain

.flake8, requirements-dev.txt, src/assisted_test_infra/download_logs/download_logs.py, src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py, src/assisted_test_infra/test_infra/helper_classes/hypershift.py, src/assisted_test_infra/test_infra/helper_classes/kube_helpers/agent.py, src/assisted_test_infra/test_infra/helper_classes/kube_helpers/agent_cluster_install.py, src/assisted_test_infra/test_infra/helper_classes/kube_helpers/cluster_image_set.py, src/assisted_test_infra/test_infra/utils/operators_utils.py
=> NO-ISSUE - Remove flake8 select plugin limitations. Fix PEP8 violations.

Makefile, src/tests/test_targets.py
=> NO-ISSUE - Add makefile target for deleting all exist clusters

scripts/deploy_assisted_service.sh
=> NO-ISSUE - Prevent from using the same assisted-service image while using DEBUG_SERVICE flag

Dockerfile.assisted-test-infra, Makefile, scripts/install_environment.sh, scripts/run_minikube.sh, scripts/test_ui.sh, scripts/utils.sh, skipper.yaml, src/assisted_test_infra/test_infra/controllers/ipxe_controller/ipxe_controller.py, src/assisted_test_infra/test_infra/controllers/tang_controller/tang_controller.py, src/assisted_test_infra/test_infra/utils/utils.py, src/consts/consts.py, src/tests/test_bootstrap_in_place.py
This PR supports podman-remote for test-infra, now the images will be visible to the host container tool.
=> Support podman-remote

scripts/install_environment.sh
Existing code is good for Rocky Linux and Alma Linux, but for RHEL we'll need to install it differently.
/cc @nmagnezi @eranco74
=> Fix EPEL installation for RHEL and CentOS

scripts/deploy_assisted_service.sh, scripts/install_environment.sh, scripts/utils.sh
Wrong  bash syntax  and service name
bash just ignores this issue and try installing podman always
=> fixing podman installation script

src/assisted_test_infra/download_logs/download_logs.py
They hold important information, e.g. static network config
=> NO-ISSUE: `download_logs.py` should include cluster infra-envs in `metadata.json`

scripts/install_environment.sh
Fixing a couple of issues:
* Bash syntax was completely off. I get locally:
```
./scripts/install_environment.sh: line 173: [!: command not found
Failed to retrieve unit state: Unit name ].service is neither a valid
invocation ID nor unit name
```
* Getting the podman version does not work. ``head -n1 <(podman version) | awk '{print $2}'`` returns ``Podman`` for me...
* I simplified the branching a bit to make code look better.
/cc @michaellevy101 @eliorerz 
/hold
(not completely tested yet)
=> Fix podman verification code

scripts/install_environment.sh
Handling several issues related to a QE environment that had an outdated (v2) version of podman:
* When installing podman, use ``--best`` to allow it to upgrade the package if that's possible.
* For RHEL 8, enable ``container-tools:4.0`` in order to be able to install later podman versions than v2.x.
=> install podman from 4.0 stream on RHEL 8 machines

src/consts/consts.py
=> MGMT-11580 - Make OCP 4.11 default on test-infra

src/assisted_test_infra/test_infra/utils/utils.py
Contributes-to: [MGMT-8890](https://issues.redhat.com//browse/MGMT-8890)
Contributes-to: [MGMT-11494](https://issues.redhat.com//browse/MGMT-11494)
/cc @paul-maidment
=> MGMT-8890: Add support for cpu_architectures in release images

src/assisted_test_infra/test_infra/helper_classes/cluster.py, src/triggers/default_triggers.py
=> NO-ISSUE - Use baremetal platform on SNO

src/consts/consts.py
=> MGMT-11586 - Add 4.12 to available openshift versions

OWNERS
=> NO-ISSUE: Remove michaellevy101 from owners

src/assisted_test_infra/test_infra/utils/env_var.py
When a trigger overrides an environment variable, it uses the [copy()](https://github.com/openshift/assisted-test-infra/blob/master/src/tests/global_variables/default_variables.py#L41) method which [sets](https://github.com/openshift/assisted-test-infra/blob/master/src/assisted_test_infra/test_infra/utils/env_var.py#L60) the new value for that environment variable.
But the call to [value()](https://github.com/openshift/assisted-test-infra/blob/master/src/assisted_test_infra/test_infra/utils/env_var.py#L46-L54) always re-evaluates against the current environment and does not take into account that the value was overridden by a trigger.
=> MGMT-12026: do not reset trigger values

src/tests/base_kubeapi_test.py, src/tests/test_kube_api.py
BASE_DOMAIN env var should be passed on ClusterDeployment creation.
=> NO-ISSUE: pass base_domain var on CD creation

terraform_files/vsphere/main.tf
Hardware version 15 is required for CSI tests to pass
=> MGMT-11926: vsphere: create machines with HW 15

packer_files/nutanix_centos_template/build.pkr.hcl, packer_files/nutanix_centos_template/centos-config/ks.cfg, packer_files/nutanix_centos_template/sources.pkr.hcl, packer_files/nutanix_centos_template/variables.pkr.hcl, packer_files/nutanix_centos_template/vars.json, terraform_files/nutanix-ci-machine/main.tf, terraform_files/nutanix-ci-machine/output.tf, terraform_files/nutanix-ci-machine/variables-nutanix.tf
This adds Packer files to prepare CentOS8-based image to run minikube with assisted-service.
The second commit adds Terraform files to start this machine in Nutanix cluster.
Ref: https://github.com/openshift/release/pull/31726
=> MGMT-11274: Add Packer and Terraform files to run AI test machine

src/assisted_test_infra/download_logs/download_logs.py
Replace pull-secret field in install-config.yaml with asterisk characters
=> MGMT-11856: Removing pullSecret from install-config.yaml

Makefile, requirements.txt
Backport of https://github.com/openshift/assisted-test-infra/pull/1824
/cc @osherdp
=> [release-ocm-2.5] NO-ISSUE - Prevent tests from being skipped when test parameterized is empty

src/assisted_test_infra/test_infra/utils/logs_utils.py
Patching CVE-2007-4559
(https://github.com/advisories/GHSA-gw9q-c7gh-j9vm) which might allow attackers to overwrite arbitrary files which are not under destination path.
Implementation inspiration: https://github.com/openshift/assisted-test-infra/pull/1898
=> sanitize tar archives due to CVE

requirements.txt
1. Update pycharm_remote_debugger dependency to newer version. 
2. Update nutanix-api to 0.0.19
/cc @osherdp
=> NO-ISSUE: Update requirements.txt

src/assisted_test_infra/test_infra/helper_classes/cluster.py, src/consts/consts.py
This is required due to https://github.com/openshift/assisted-service/pull/4586
=> NO-ISSUE: update statusRebootTimeout message

terraform_files/nutanix/main.tf
Sync up provider version with CI machine terraform
=> Nutanix: use 1.7.1 provider

Dockerfile.assisted-test-infra
=> OCPBUGSM-46219: OCPBUGSM-46220: Update golang version to 1.18.1

src/assisted_test_infra/test_infra/helper_classes/infra_env.py
=> MGMT-12545: Rename "discovery kernel arguments" to "kernel arguments" in infra-env context

Makefile, scripts/hub-cluster/create.sh, scripts/hub-cluster/delete.sh
Back in https://github.com/openshift/assisted-test-infra/pull/1915 I forgot to allow setup for onprem/podman installation mode.
This should fix it.
=> Allow 'onprem' deploy-target in hub-cluster setup

.gitignore, Dockerfile.assisted-test-infra, terraform_files/baremetal/main.tf, terraform_files/baremetal/variables-libvirt.tf, terraform_files/baremetal_host/main.tf, terraform_files/baremetal_host/variables.tf, terraform_files/baremetal_infra_env/main.tf, terraform_files/baremetal_infra_env/variables-libvirt.tf, terraform_files/none/main.tf, terraform_files/none/variables-libvirt.tf, terraform_files/nutanix-ci-machine/main.tf, terraform_files/nutanix-ci-machine/output.tf, terraform_files/nutanix-ci-machine/variables-nutanix.tf, terraform_files/nutanix/main.tf, terraform_files/nutanix/variables_nutanix.tf, terraform_files/nutanix/virtual_machines.tf, terraform_files/vsphere-ci-machine/main.tf, terraform_files/vsphere-ci-machine/variables-vsphere.tf, terraform_files/vsphere/main.tf, terraform_files/vsphere/variables-vsphere.tf
- removed `experiments = [module_variable_optional_attrs]` as it is not
experimental anymore
- ran `terraform fmt` on all our modules
- ignored more terraform files in `.gitignore`
=> NO-ISSUE: Update to terraform 1.3.6

Dockerfile.assisted-test-infra, ansible_files/equinix_heterogeneous_create_infra_playbook.yml, ansible_files/roles/common/setup_ipip_tunnel/defaults/main.yml, ansible_files/roles/common/setup_ipip_tunnel/tasks/main.yml
Setup an IPIP tunnel between both devices.
Requires https://github.com/openshift/assisted-test-infra/pull/1949
=> MGMT-12440: Configure IPIP tunnel with heterogeneous setup

src/consts/consts.py
=> MGMT-13300: Add support with 4.13 dev preview images

src/consts/consts.py
=> MGMT-12976: Make OCP 4.12 default on test-infra

src/assisted_test_infra/download_logs/download_logs.py, src/assisted_test_infra/download_logs/resources/man_sosreport.sh, src/assisted_test_infra/test_infra/controllers/node_controllers/nutanix_controller.py, src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py
Use sos report along with toolbox to gather the logs from cluster
nodes.
https://github.com/openshift/assisted-test-infra/pull/1929 + feedback addressed
=> MGMT-11712: Gather logs using sos report on nodes

Makefile
For QEmu installs "_destroy_virsh" target is used
=> Makefile: _destroy_terraform should actually run terraform

scripts/hub-cluster/kind/kind.sh
use sudo for installation of kind to prevent permission denied errors
=> Use sudo for installation of kind

src/assisted_test_infra/test_infra/helper_classes/nodes.py
When starting a node and we need access to the node it may take some time till node will be ready and sshable from outside.
ping or verify ip is not enough in cases ssh service not ready.
Added a waiter in nodes.py
=> Add waiter for ssh to nodes

ansible_files/equinix_heterogeneous_create_infra_playbook.yml, ansible_files/roles/common/setup_ipip_tunnel/tasks/main.yml, ansible_files/roles/common/setup_ssh_key_pair/defaults/main.yml, ansible_files/roles/common/setup_ssh_key_pair/tasks/main.yml, ansible_files/roles/test-infra/export-heterogeneous-day2-configuration/defaults/main.yml, ansible_files/roles/test-infra/export-heterogeneous-day2-configuration/tasks/main.yml, ansible_files/roles/test-infra/export-heterogeneous-day2-configuration/templates/assisted-additional-config.j2
Export day2 configuration into assisted-additional-config that will be
sourced by the CI.
Had to refactor the existing tasks to set the facts properly at host
level.
=> MGMT-13247: Export day2 configuration

Makefile, src/assisted_test_infra/test_infra/controllers/node_controllers/nutanix_controller.py, src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py, src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py, src/assisted_test_infra/test_infra/tools/terraform_utils.py, src/tests/base_test.py, src/tests/test_targets.py
Backport of https://github.com/openshift/assisted-test-infra/pull/2031
/cc @vrutkovs @adriengentil
=> NO-ISSUE: Add test which destroys targets via terraform

ansible_files/roles/common/setup_libvirtd/tasks/main.yml, ansible_files/roles/equinix/export_primary_device_connection_details/tasks/main.yml, ansible_files/roles/equinix/export_primary_device_connection_details/templates/ci-machine-config.sh.j2, ansible_files/roles/equinix/export_primary_device_connection_details/templates/inventory.j2
Build a basic inventory that allows the gather step from the CI to build
an sos report on the ARM machine.
=> MGMT-12454: Dump inventory to get sosreport from ARM machine

src/assisted_test_infra/download_logs/download_logs.py
Between listing all clusters (including deleted ones) and getting their information, quite some time can pass where they can get garbage collected.
This change does 2 things in that regard:
* Change the retry interval from 5 minutes (!) to 5 seconds. Reason it's fine is because Jenkins job itself is configured to run every 0.5 hours, so it's not necessary to wait for too long in the scope of a single run.
* If we're getting an API error for a deleted cluster, we can assume it got garbage collected. We only log it for tracking purposes.
=> Fix inspection of deleted clusters

src/assisted_test_infra/test_infra/helper_classes/cluster.py
- Added set_ignored_validations
- Added get_ignored_validations
=> Add function call to cluster ignore_validation

scripts/deploy_assisted_service.sh
=> NO-ISSUE: Fix service remote debugger

src/assisted_test_infra/test_infra/helper_classes/cluster.py, src/service_client/assisted_service_api.py
To test baselineCapabilitySet=None param before starting installation.
=> Add support for update_install_config

README.md
To trigger to 2.9 FF 
/cc @eliorerz
=> NO-ISSUE: Fix readme file

src/tests/test_targets.py
- Fix vSphere and Nutanix teardown
- Making `destroy_terraform` target to work with all platforms.
/cc @eliorerz
=> MGMT-14518: Fix vSphere and Nutanix teardown

src/assisted_test_infra/test_infra/helper_classes/cluster.py, src/assisted_test_infra/test_infra/utils/operators_utils.py, src/consts/olm_operators.py, src/triggers/default_triggers.py, src/triggers/env_trigger.py, src/triggers/olm_operators_trigger.py
Tested locally, will be tested as part of https://github.com/openshift/assisted-service/pull/5203
/cc @gamli75 @adriengentil
=> MGMT-14602: Add MCE operator support

src/consts/consts.py
=> MGMT-14355: Make OCP 4.13 default on test-infra

src/consts/consts.py
=> MGMT-14369: Add 4.14 as valid version on test-infra

README.md, packer_files/nutanix_centos_template/variables.pkr.hcl, packer_files/vsphere_centos_template/variables.pkr.hcl, terraform_files/nutanix-ci-machine/variables-nutanix.tf, terraform_files/vsphere/variables-vsphere.tf
=> NO-ISSUE: Update vsphere and nutanix packer machine RAM to 16GiB

src/assisted_test_infra/test_infra/exceptions.py, src/assisted_test_infra/test_infra/helper_classes/cluster.py, src/assisted_test_infra/test_infra/utils/waiting.py, src/tests/test_e2e_install.py
=> MGMT-14660: Fail on pending input during installation instead of waiting for timeout

src/consts/olm_operators.py
=> NO-ISSUE: Remove extra disk from mce test

src/consts/olm_operators.py
=> No issue remove extra disk from SNO MCE test

src/assisted_test_infra/test_infra/helper_classes/cluster.py, src/assisted_test_infra/test_infra/utils/operators_utils.py
=> MGMT-14674: Add operators status log when waiting for operators to finish

Makefile, scripts/override_os_images.py, src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py, src/tests/test_targets.py
Supposed to fix the vsphere-kube-api tests 
/cc @eliorerz
=> MGMT-14518: Fix kubeapi vSphere and Nutanix teardown

src/assisted_test_infra/test_infra/helper_classes/config/base_config.py
Fix for this issue - https://github.com/openshift/assisted-test-infra/pull/2181#discussion_r1211263389
/cc @adriengentil @osherdp
=> MGMT-14819: Allow use Optional type hint in parameterized test

src/assisted_test_infra/test_infra/helper_classes/cluster.py, src/consts/__init__.py, src/consts/olm_operators.py, src/triggers/default_triggers.py
- Add support with MetalLB operator.
- Allow setting operator properties 
- Add missing methods for MCE operator 
/cc @osherdp @gamli75 @adriengentil
=> MGMT-14823: Allow installing MetalLB operator using test-infra

scripts/create_full_environment.sh
=> MGMT-14737: Add Support with Oracle Linux

Makefile
/cc @osherdp @adriengentil @gamli75
=> NO-ISSUE: Fix vsphere kubeapi CI teardown for ocm-2.7

src/assisted_test_infra/test_infra/helper_classes/events_handler.py, src/service_client/assisted_service_api.py
Enabling use all parameter of list events
e.g. limit and offset in order test pagination
/cc @eliorerz @osherdp @lital @danmanor
=> Enabling use all parameter of list events

src/assisted_test_infra/test_infra/utils/logs_utils.py
Added more capabilites to the verify action on logs
- Repeated names under directory
- Repeated md5sum under directory - indicate if we have same content
- Included file name inside other files - sub names in other names
- Exceed limit size (1MB) under directory
- Minimal file size (17 Bytes) when '-- No entries --' in logs
Added support for md5sum calculation
Added extraction for tar.gz files
=> Extend and refactor verify_logs_uploaded

terraform_files/oci/00_main.tf, terraform_files/oci/03_compute.tf, terraform_files/oci/variables.tf
=> MGMT-14999: Add virtualization support for OCI nodes

src/assisted_test_infra/test_infra/utils/operators_utils.py
=> MGMT-15131: Raise more indicative exception on operator deployment failure

src/assisted_test_infra/test_infra/utils/operators_utils.py
=> NO-ISSUE: Add info to the raised exception instead of exception chaining

src/assisted_test_infra/test_infra/helper_classes/cluster.py, src/assisted_test_infra/test_infra/tools/terraform_utils.py, src/tests/test_targets.py
=> NO-ISSUE: Delete terraform folder after cleaning all resources, add logs to destroy_available_terraform.

terraform_files/nutanix/main.tf
=> NO-ISSUE: Update nutanix terraform version

src/consts/consts.py
Add event for MCE operator installation completed
=> MCE operator event

terraform_files/vsphere/main.tf, terraform_files/vsphere/variables-vsphere.tf
=> MGMT-14651: Add the option to create multiple disks on vSphere platform installation

src/assisted_test_infra/test_infra/tools/assets.py
In parallel tests we may get a list of all networks but testcase cleanup may delete the netowrk object from the test. We get here all libvirt network and we must consider case when one of the network no more available while we in the loop.
=> Fix assets.py listAllNetworks

Dockerfile.assisted-test-infra, packer_files/vsphere_centos_template/variables.pkr.hcl
/cc @adriengentil @osherdp @gamli75
=> MGMT-15703: Update vsphere ci machine base image and update packer version

OWNERS
=> NO-ISSUE: Riccardo and I as approvers

src/consts/consts.py
=> MGMT-16078: Add 4.15 as valid version

Dockerfile.assisted-test-infra
Since we have issues with vsphere infrastructure, let's make sure to use the latest version of terraform.
=> NO-ISSUE: Upgrade to terraform 1.6.3

src/tests/base_test.py
Added new structure return when SNO node, get_ip_for_single node returns string. In case exception bubbled up we handle it and set "" as address
Fix config_etc_hosts call , changed param to api_vip
=> Fix api_vip for  update_oc_config function

scripts/install_environment.sh
=> [release-ocm-2.9] NO-ISSUE: Upgrade pip ocm 2.9

OWNERS
=> NO-ISSUE: add avishayt as approver

src/assisted_test_infra/test_infra/controllers/node_controllers/__init__.py, src/assisted_test_infra/test_infra/controllers/node_controllers/zvm_controller.py, src/assisted_test_infra/test_infra/helper_classes/cluster.py, src/consts/consts.py, src/tests/base_test.py
Add new zVMController (as stub) to in later PRs the necessary code be able to create a zVM Cluster.
The code is "disabled" for the time being.
=> MULTIARCH-3980: Add new Controller (as stub) for zVM

src/tests/test_e2e_install.py
Ensure openshift version has semver compatible value
=> ensure version has semver compatible value

README.md, scripts/hub-cluster/minikube.sh
* Add ability to configure minikube setup
* allows to change all minikube configuration using env values
*  default setup has not change
=> NO-ISSUE: add ability to configure minikube

src/consts/consts.py
=> MGMT-16276: Add 4.16 ocp version

packer_files/nutanix_centos_template/build.pkr.hcl, packer_files/nutanix_centos_template/centos-config/ks.cfg, packer_files/nutanix_centos_template/sources.pkr.hcl, packer_files/nutanix_centos_template/variables.pkr.hcl
- change Default size to 100
- move kick start to percent to auto adjust when overwriting size
depends on [#49968](https://github.com/openshift/release/pull/49968)
=> fix nutanix default disk size

README.md, src/assisted_test_infra/test_infra/utils/__init__.py, src/assisted_test_infra/test_infra/utils/k8s_utils.py, src/tests/test_e2e_install.py
add a test for MCE + storage functionality
we need to make sure the right objects are deployed correctly and the defined storage classes are matching
This will be added to the current MCE job
=> MGMT-17080: test mce and storage

src/service_client/logger.py
Moved colored to enum object
Added colorized support for file handler to distinguish between different logging levels.
=> Add colorized file handler same as stream handler

packer_files/nutanix_centos_template/centos-config/ks.cfg
Update packer nutanix public ssh key
/cc @danmanor
=> NO-ISSUE: Fix Nutanix fail to login ssh key

packer_files/nutanix_centos_template/centos-config/ks.cfg
=> NO-ISSUE: Update nutanix packer ssh key

packer_files/nutanix_centos_template/centos-config/ks.cfg
=> NO-ISSUE: Revert ssh key nutanix

OWNERS
=> NO-ISSUE: Add my account in OWNERS

requirements.txt
=> NO-ISSUE: Fix missing distutils when trying to `override_release_images`

src/assisted_test_infra/test_infra/helper_classes/entity.py
=> NO-ISSUE: Fix failures when there are no nodes on entity initialization

requirements.txt
=> [release-ocm-2.10] NO-ISSUE: fix for missing distutils

src/assisted_test_infra/download_logs/__main__.py, src/assisted_test_infra/test_infra/helper_classes/config/base_nodes_config.py, src/service_client/assisted_service_api.py
Reverts openshift/assisted-test-infra#2450
Must be merged only after this [PR](https://gitlab.cee.redhat.com/assisted-installer-ops/assisted-installer-cicd/-/merge_requests/239).
=> Revert "MGMT-17246: add support for ignoring clusters that already exist on jira"

requirements.txt
=> [release-ocm-2.8] NO-ISSUE: fix for missing distutils

requirements.txt
=> [release-ocm-2.9] NO-ISSUE: fix for missing distutils

scripts/install_environment.sh
fix for OCM branches
need to cherry pick for ocm 2.8-2.10
=> NO-ISSUE: Fix for OCM branches

src/assisted_test_infra/download_logs/__main__.py
Change argument name to match command line argument name
=> MGMT-17246: Bug fix - change argument name to match command line argument name

packer_files/nutanix_centos_template/build.pkr.hcl, packer_files/nutanix_centos_template/centos-config/ks.cfg, packer_files/nutanix_centos_template/sources.pkr.hcl
=> NO-ISSUE: Use centos 9 as default. Upgrade Nutanix packer plugin to latest

requirements.txt
The package allows us to sort complicated versions with numbers and naming. Using this package in custom ocp tests, getting a list of versions and sorting for last element .
Package info: https://pypi.org/project/natsort/
=> NO-ISSUE: Add natsort package to requirements.txt

.gitignore, Dockerfile.assisted-test-infra, Makefile, README.md, scripts/bring_assisted_service.sh, scripts/create_full_environment.sh, scripts/utils.sh
Tailored backport of https://github.com/openshift/assisted-test-infra/pull/2486
=> [release-ocm-2.8] MGMT-18333: Generate python client instead of using the one from assisted-service image

.gitignore, Dockerfile.assisted-test-infra, Makefile, README.md, scripts/bring_assisted_service.sh, scripts/create_full_environment.sh
Tailored backport of https://github.com/openshift/assisted-test-infra/pull/2486
=> [release-ocm-2.9] MGMT-18333: Generate python client instead of using the one from assisted-service image

scripts/deploy_assisted_service.sh, scripts/utils.sh
1. improving port forward configuration ( socat)
2. adding  LB ports to firewall policy 
3. enabling forward for `libvirt-routed` zone
4. adding teardown config
=> [MGMT-18102] fix for platform none/external on RHEL9

src/consts/olm_operators.py
fixing tests on PR [#6645](https://github.com/openshift/assisted-service/pull/6645)
=> MGMT-18378: fix for LVMs with worker nodes

scripts/deploy_ui.sh
Fix UI pod readiness condition in UI deployment script the actually wait for it to be ready
=> NO-ISSUE: Fix UI pod readiness condition in UI deployment script

src/assisted_test_infra/test_infra/controllers/node_controllers/oci_api_controller.py
Added interval value to reduce the total log messages. The message in log will be:
counter and job status every minute
_apply_job_from_stack: 12 -> IN_PROGRESS
Ticket:  https://issues.redhat.com/browse/MGMT-18603
=> MGMT-18603: OCI Add wait_callback while applying stack configuration

src/assisted_test_infra/test_infra/helper_classes/cluster.py, src/service_client/assisted_service_api.py
Set `control_plane_count` new cluster create param for PR - https://github.com/openshift/assisted-test-infra/pull/2562
=> MGMT-19080: Setup test infra for testing new control_plane_count field in https://github.com/openshift/assisted-service/pull/6917

src/consts/olm_operators.py, src/triggers/default_triggers.py
This patch adds the OpenShift AI OLM operator.
Related: https://issues.redhat.com/browse/MGMT-19248
Related: https://issues.redhat.com/browse/MGMT-19056
=> MGMT-19248: Add OpenShift AI operator

src/assisted_test_infra/test_infra/controllers/containerized_controller.py, src/assisted_test_infra/test_infra/controllers/ipxe_controller/ipxe_controller.py
The code will allow to change containers files when its up boot from iscsi volume requires different pxe setting per node. Instead of creating multiple pxe, re-using existing pxe by changing the pxe disk volume.
=> [MGMT-17556] Allow to modify files inside running container.

Makefile, src/assisted_test_infra/test_infra/helper_classes/kube_helpers/agent_cluster_install.py, src/assisted_test_infra/test_infra/utils/k8s_utils.py, src/consts/consts.py, src/tests/test_kube_api.py
Enable testing k8s API flow for - https://github.com/openshift/assisted-service/pull/7096
=> MGMT-19509: Enable automatic testing of user-managed load balancer in a k8s api flow

src/assisted_test_infra/test_infra/helper_classes/cluster.py
Fixing issue where the static IP validation was not working when using `bond` interfaces
=> MGMT-19569: validate static IP in bond

src/consts/olm_operators.py, src/triggers/default_triggers.py
enabling Kubernetes NMState Operator option in assisted-test-infra
=> MGMT-19668: Adding nmstate operator to assisted installer

README.md
Reverts openshift/assisted-test-infra#2635
=> Revert "NO-ISSUE: Trigger new image promotiom to ocm-2.14 image stream"

src/assisted_test_infra/test_infra/helper_classes/cluster.py, src/assisted_test_infra/test_infra/helper_classes/config/base_cluster_config.py, src/tests/global_variables/env_variables_defaults.py
This is a temporary patch to enable testing of https://github.com/openshift/assisted-service/pull/7272. Later on more generic code will be added
=> MGMT-19831: Enable automatic testing user-managed load balancer with vSphere

src/consts/olm_operators.py
For testing - https://github.com/openshift/assisted-service/pull/7444
=> MGMT-20190: Add Node Maintenance Operator

OWNERS
Eran has left Assisted Installer team
=> NO-ISSUE: Remove eran ifrach account from OWNERS

OWNERS
Eran has left Assisted Installer team
=> [release-ocm-2.13] NO-ISSUE: Remove eran ifrach account from OWNERS

src/consts/olm_operators.py
For testing - https://github.com/openshift/assisted-service/pull/7462
=> MGMT-20191: Add Kube Descheduler Operator

src/assisted_test_infra/download_logs/download_logs.py
`instal-config.yaml` is `json` now, therefore regex doesn't catch
=> MGMT-20334: Fix pull-secret censor

README.md, docs/assisted-deployment.md, docs/assisted-service-client.md, docs/assisted-testing.md, docs/build-image.md, docs/getting-started.md, docs/overview.md, docs/prerequisites.md, docs/setup.md, docs/warning.md
The docs will be added in parts to reduce the review size
=> MGMT-20218: Add documentation to test-infra - getting started doc to ease the use of new users

src/assisted_test_infra/test_infra/controllers/node_controllers/oci_api_controller.py
Added support to change masters count for 1,3,4,5 masters run on oracle.
=> Add masters_count to oci api

Makefile
=> [release-ocm-2.14] NO-ISSUE: Update assisted-service image tag to ocm-2.14

ansible_files/aws_ec2_region_cleanup.yml
This playbook will be used by Prow periodic jobs that will ensure no leaked resources exist
Slack message:
=> MGMT-20779: Add AWS cleanup playbook

src/assisted_test_infra/download_logs/download_logs.py, src/consts/consts.py
This PR removes certain cluster files (`bootstrap.ign`, `master.ign`, and `worker.ign`) from the AITRIAGE download process. 
These files can contain sensitive information and are generally not needed for most installation failure investigations.
=> MGMT-20382: Adjust AITRIAGE File Collection

ansible_files/aws_ec2_region_cleanup.yml
https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_instance_info_module.html#requirements
=> NO-ISSUE: Add ansible aws module requirements to aws cleanup playbook

src/consts/olm_operators.py
to test https://github.com/openshift/assisted-service/pull/7828
=> MGMT-21173: Add COO, NUMA Resources and OADP operators

ansible_files/README.md, ansible_files/roles/setup_sftp_share/tasks/main.yml
The error:
```
Aug 11 02:04:23 ip-172-31-71-203.ec2.internal rclone[13901]: ERROR+4: Fatal error: failed to mount FUSE fs: fusermount: exec: "fusermount3": executable file not found in $PATH
```
Fix the docs as well
=> MGMT-21416: Fix heterogeneous workflow by installing fuse3

scripts/sno-ip-change/README.md, scripts/sno-ip-change/flows/secondary-ip-change.sh, scripts/sno-ip-change/remote/dual-node-actions.sh, scripts/sno-ip-change/tests/test-secondary-ip-change.sh
Simulate actual ipv6 uplink -> ipv4 uplink change
=> NO-ISSUE: Add Primary IP parameter for secondary ip change script
